// autogeneratedPrimaryKeyBySequence draws the primary key from a named DB
// sequence (typed only on mariaDB / oracle / postgreSql / sqlServer), distinct
// from the autogenerated IDENTITY/SERIAL PK the engine fills implicitly. The
// emitted INSERT references the sequence's next-value (the exact form is
// per-dialect, pinned by the snapshot). SQLite and MySQL don't expose the
// method (their connection types omit it), so the test is NOT-APPLICABLE there
// with a paired compile-time negative in the dialect's types.negative/ folder.

import { afterAll, beforeAll, beforeEach, describe } from '../../../../lib/testRunner.js'
import { ctx } from './setup.js'

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    // NOT-APPLICABLE: autogeneratedPrimaryKeyBySequence is not typed on SqliteConnection (SQLite has no CREATE SEQUENCE).
    /*
    test('insert-with-sequence-primary-key-references-the-sequence', async () => {
        // The PK value comes from the sequence, so the INSERT references its
        // next-value rather than relying on an IDENTITY/SERIAL default. A
        // committing transaction + reseed is used because the sequence bump is
        // non-transactional (a rollback would leave the counter advanced).
        //
        // B-6 / T3-e: tAuditEntry.id carries the autogeneratedPrimaryKeyBySequence
        // TRAILING TypeAdapter overload (plusOffsetAdapter, read +1000). The
        // emitted INSERT/RETURNING SQL is unchanged by the adapter (it only
        // transforms the read), so the returned id surfaces OFFSET: the mock
        // queues the raw DB id 50, which the adapter reads back as 1050; on a real
        // DB the id is the raw sequence value (>= 1) + 1000, so id >= 1001.
        await ctx.withCommit(async () => {
            ctx.mockNext(50)
            const id = await ctx.conn.insertInto(tAuditEntry)
                .values({ action: 'archived' })
                .returningLastInsertedId()
                .executeInsert()

            expect(ctx.lastSql).toMatchInlineSnapshot()
            expect(ctx.lastParams).toMatchInlineSnapshot()
            assertType<Exact<typeof id, number>>()
            if (!ctx.realDbEnabled) expect(id).toBe(1050)
            else expect(id).toBeGreaterThanOrEqual(1001)
        })
    })
    */

    // NOT-APPLICABLE: SQLite has no CREATE SEQUENCE DDL and `connection.sequence(...)` is not typed on SqliteConnection.
    /*
    test('insert-with-explicit-sequence-next-value-as-a-column-value', async () => {
        // `issueIdSeq.nextValue()` passed directly as an INSERT column value emits
        // the raw sequence next-value in the VALUES list (no bound param), so
        // tInvoice's invoice_no scaledTenthAdapter never fires — the column receives
        // the raw sequence value. withCommit + reseed because the sequence bump is
        // non-transactional.
        await ctx.withCommit(async () => {
            ctx.mockNext(1)
            const affected = await ctx.conn.insertInto(tInvoice)
                .values({ invoiceNo: ctx.conn.issueIdSeq.nextValue(), total: 1200 })
                .executeInsert()

            expect(ctx.lastSql).toMatchInlineSnapshot(`"insert into invoice (invoice_no, total) values (nextval('issue_id_seq'), $1)"`)
            expect(ctx.lastParams).toMatchInlineSnapshot(`
              [
                1200,
              ]
            `)
            assertType<Exact<typeof affected, number>>()
            if (!ctx.realDbEnabled) expect(affected).toBe(1)
            else expect(typeof affected).toBe('number')
        })
    })
    */
})
