// Behavioral coverage of `connection.insertInto(t).defaultValues()`,
// which triggers `_buildInsertDefaultValues` in each SqlBuilder. Each
// dialect emits a different form: SQLite/PostgreSQL emit
// `INSERT INTO t DEFAULT VALUES`; MySQL/MariaDB emit
// `INSERT INTO t () VALUES ()`; Oracle expands all sequence-backed
// columns explicitly. No existing test exercises this path.

import { afterAll, beforeAll, beforeEach, describe, expect, test } from '../../../../lib/testRunner.js'
import { Table } from '../../../../../src/Table.js'
import { DBConnection } from '../../domain/connection.js'
import { ctx } from './setup.js'

// Local-only table whose only column is an autogenerated PK. On SQLite
// `RequiredColumnsForSetOf` resolves to `never` here, so `.defaultValues()`
// types correctly with no cast needed.
class TDefaultsOnly extends Table<DBConnection, 'TDefaultsOnly'> {
    id = this.autogeneratedPrimaryKey('id', 'int')
    constructor() { super('defaults_only_table_only_for_sql_test') }
}
const tDefaultsOnly = new TDefaultsOnly()

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    test('insert default values', async () => {
        // SQLite types `.defaultValues()` correctly here (the local table's
        // only column is an autogenerated PK, so there are no required
        // columns for set). The table is intentionally absent from the
        // schema — it exists only to pin the DEFAULT VALUES SQL form — so
        // real SQLite rejects execution with "no such table". We assert that
        // error in real mode and the mocked row count in mock mode; either
        // way the emitted SQL is captured before execution and checked.
        ctx.mockNext(99)
        let caught: unknown
        try {
            const inserted = await ctx.conn.insertInto(tDefaultsOnly)
                .defaultValues()
                .returningLastInsertedId()
                .executeInsert()
            if (!ctx.realDbEnabled) expect(inserted).toBe(99)
        } catch (e) {
            caught = e
        }
        if (ctx.realDbEnabled) {
            expect(String(caught)).toMatch(/no such table|defaults_only_table_only_for_sql_test/)
        } else {
            expect(caught).toBeUndefined()
        }
        expect(ctx.lastSql).toMatchInlineSnapshot(`"insert into defaults_only_table_only_for_sql_test default values returning id"`)
        expect(ctx.lastParams).toMatchInlineSnapshot(`[]`)
    })
})
