-- Schema for the shared "project management" domain, mariadb dialect.
-- Idempotent: tests run setup against a fresh database each variant, but
-- having DROP IF EXISTS lets you re-apply by hand for debugging.

DROP VIEW IF EXISTS project_overview;
DROP VIEW IF EXISTS release_overview;
DROP TABLE IF EXISTS project_release;
DROP TABLE IF EXISTS webhook_event;
DROP TABLE IF EXISTS calendar_year;
DROP TABLE IF EXISTS issue_worklog;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS issue;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS organization;

CREATE TABLE organization (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    plan VARCHAR(32) NOT NULL,
    -- `verified` flag stored as Y/N so the connection.ts mapping can
    -- exercise CustomBooleanTypeAdapter on a real seed column.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    -- `verified` stored as Y/N — same CustomBooleanTypeAdapter mapping
    -- as organization.verified so cross-table comparisons need no remap.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    -- `published` flag stored as t/f, a deliberately different
    -- CustomBooleanTypeAdapter mapping than organization/app_user.verified
    -- so column-vs-column comparisons hit the remap-with-case branch.
    published VARCHAR(1) NOT NULL DEFAULT 'f',
    archived_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    UNIQUE (organization_id, slug)
);

CREATE TABLE issue (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    `number` INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NULL,
    status VARCHAR(32) NOT NULL,
    priority INT NOT NULL,
    assignee_id INT NULL,
    parent_id INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- New-type columns exercising AbstractConnection value marshalling:
    -- bigint (view_count), double (estimated_hours), uuid (external_ref).
    view_count BIGINT NOT NULL DEFAULT 0,
    estimated_hours DOUBLE,
    -- BINARY(16), not CHAR: the default MySQL uuid strategy ('binary')
    -- stores uuids as BINARY(16) and converts with UUID_TO_BIN / BIN_TO_UUID,
    -- so the column must accept the binary form uuid_to_bin(?) produces.
    external_ref BINARY(16),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (assignee_id) REFERENCES app_user(id),
    FOREIGN KEY (parent_id) REFERENCES issue(id),
    UNIQUE (project_id, `number`)
);

CREATE TABLE country (
    code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    region VARCHAR(32) NOT NULL
);

CREATE TABLE issue_worklog (
    id INT AUTO_INCREMENT PRIMARY KEY,
    issue_id INT NOT NULL,
    work_date DATE NOT NULL,
    started_at TIME,
    minutes INT DEFAULT 0,
    duration_ms BIGINT NULL,
    billable TINYINT(1) NULL,
    approved VARCHAR(1) NULL,
    activity VARCHAR(16) NOT NULL,
    -- Nullable DB-computed column (declared optionalComputedColumn).
    activity_label VARCHAR(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN UPPER(activity) ELSE NULL END) STORED,
    FOREIGN KEY (issue_id) REFERENCES issue(id)
);

-- Bigint autogenerated PK + enum-defaulted column.
CREATE TABLE webhook_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    issue_id INT NOT NULL,
    event_type VARCHAR(16) NOT NULL DEFAULT 'created',
    FOREIGN KEY (issue_id) REFERENCES issue(id)
);

-- Int caller-provided PK.
CREATE TABLE calendar_year (
    year_value INT PRIMARY KEY,
    year_label VARCHAR(64) NOT NULL
);

CREATE TABLE project_release (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    version VARCHAR(32) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    signing_key BINARY(16) NULL,
    released_on DATE NOT NULL,
    cutoff_time TIME NOT NULL,
    signed_off_at DATETIME NULL,
    notes VARCHAR(255) GENERATED ALWAYS AS (CONCAT('release-', version)) STORED,
    FOREIGN KEY (project_id) REFERENCES project(id),
    UNIQUE (project_id, version)
);

-- Stored procedures and functions exercised by
-- `exec.procedure-function.test.ts`. Each body is intentionally
-- trivial AND single-statement so the `splitStatements` helper (which
-- splits on `;\n`) ships each CREATE in one piece.
DROP PROCEDURE IF EXISTS refresh_stats;
DROP PROCEDURE IF EXISTS archive_project;
DROP FUNCTION IF EXISTS count_open_issues;
DROP FUNCTION IF EXISTS project_name;
CREATE PROCEDURE refresh_stats() SELECT 1;
CREATE PROCEDURE archive_project(IN p_id INT, IN p_reason VARCHAR(255)) UPDATE project SET archived_at = CURRENT_TIMESTAMP, name = CONCAT(name, ' [archived: ', p_reason, ']') WHERE id = p_id;
CREATE FUNCTION count_open_issues(p_id INT) RETURNS INT DETERMINISTIC RETURN (SELECT COUNT(*) FROM issue WHERE project_id = p_id AND status = 'open');
CREATE FUNCTION project_name(p_id INT) RETURNS VARCHAR(255) DETERMINISTIC RETURN (SELECT name FROM project WHERE id = p_id);
DROP FUNCTION IF EXISTS total_view_count;
DROP FUNCTION IF EXISTS latest_issue_at;
DROP FUNCTION IF EXISTS estimated_total;
CREATE FUNCTION total_view_count(p_id INT) RETURNS BIGINT DETERMINISTIC RETURN (SELECT COALESCE(SUM(view_count),0) FROM issue WHERE project_id = p_id);
CREATE FUNCTION latest_issue_at(p_id INT) RETURNS DATETIME DETERMINISTIC RETURN (SELECT MAX(created_at) FROM issue WHERE project_id = p_id);
CREATE FUNCTION estimated_total(p_id INT) RETURNS DOUBLE DETERMINISTIC RETURN (SELECT COALESCE(SUM(estimated_hours),0) FROM issue WHERE project_id = p_id);

-- A class-based SQL view exercised by `view.basic.test.ts`. A plain
-- join of project + organization (no aggregation, no casts), portable
-- across every dialect.
CREATE VIEW project_overview AS
SELECT p.id AS id,
       p.organization_id AS organization_id,
       p.name AS name,
       p.archived_at AS archived_at,
       o.name AS organization_name,
       o.plan AS organization_plan
FROM project p
INNER JOIN organization o ON o.id = p.organization_id;

-- View side of the release columns (see vReleaseOverview in connection.ts).
CREATE VIEW release_overview AS
SELECT r.id AS id,
       r.project_id AS project_id,
       r.version AS version,
       r.released_on AS released_on,
       r.signed_off_at AS signed_off_at,
       p.name AS project_name
FROM project_release r
INNER JOIN project p ON p.id = r.project_id;
