// Documentation snippets for the Columns-from-object page
// (docs/advanced/columns-from-object.md). Demonstrates the
// `extract*From` helpers that turn a table/view definition into a
// projection or name list at runtime.

import { afterAll, beforeAll, beforeEach, describe, expect, test } from '../../../../lib/testRunner.js'
import { assertType, type Exact, type Extends } from '../../../../lib/assertType.js'
import {
    extractColumnsFrom,
    extractWritableColumnsFrom,
    extractIdColumnsFrom,
    extractColumnNamesFrom,
    extractWritableShapeFrom,
} from '../../../../../src/extras/utils.js'
import { tIssue, tOrganization } from '../../domain/connection.js'
import { ctx } from './setup.js'

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    test('docs:columns-from-object/extract-columns-select-all', async () => {
        ctx.mockNext({ id: 1, name: 'Acme Corp', plan: 'pro', createdAt: new Date() })

        // doc-start
        const cols = extractColumnsFrom(tOrganization)
        const row = await ctx.conn.selectFrom(tOrganization)
            .where(tOrganization.id.equals(1))
            .select(cols)
            .executeSelectOne()
        // doc-end

        expect(ctx.lastSql).toMatchInlineSnapshot(`"select id as id, name as name, [plan] as [plan], created_at as createdAt from organization where id = @0"`)
        expect(ctx.lastParams).toMatchInlineSnapshot(`
          [
            1,
          ]
        `)
        // All columns are required so the result type is required.
        assertType<Extends<typeof row, {
            id:        number
            name:      string
            plan:      string
            createdAt: Date
        }>>()
        if (ctx.realDbEnabled) {
            expect(row.id).toBe(1)
            expect(row.name).toBe('Acme Corp')
        }
    })

    test('docs:columns-from-object/extract-columns-exclude-keys', async () => {
        // doc-start
        const cols = extractColumnsFrom(tOrganization, ['createdAt'])
        // doc-end
        // The excluded key is removed from the value type.
        assertType<Extends<typeof cols, { id: unknown; name: unknown; plan: unknown }>>()
        // And no `createdAt` key on the picked object.
        const k = Object.keys(cols)
        expect(k).toContain('id')
        expect(k).toContain('name')
        expect(k).toContain('plan')
        expect(k).not.toContain('createdAt')
    })

    test('docs:columns-from-object/extract-column-names', () => {
        // doc-start
        const names = extractColumnNamesFrom(tOrganization)
        // doc-end
        assertType<Extends<typeof names, string[]>>()
        expect(names.sort()).toEqual(['createdAt', 'id', 'name', 'plan'])
    })

    test('docs:columns-from-object/extract-writable-columns', async () => {
        // doc-start
        const cols = extractWritableColumnsFrom(tIssue)
        // doc-end
        // Every column declared on a Table — `column`, `optionalColumn`,
        // `columnWithDefaultValue`, `optionalColumnWithDefaultValue`,
        // `primaryKey` and `autogeneratedPrimaryKey` — is writable.
        // The helper omits computed columns (none on tIssue) and any
        // column belonging to a view.
        const k = Object.keys(cols).sort()
        expect(k).toEqual([
            'assigneeId',
            'body',
            'createdAt',
            'id',
            'number',
            'parentId',
            'priority',
            'projectId',
            'status',
            'title',
            'updatedAt',
        ])
    })

    test('docs:columns-from-object/extract-id-columns', () => {
        // doc-start
        const cols = extractIdColumnsFrom(tOrganization)
        // doc-end
        // The PK is `id`.
        expect(Object.keys(cols)).toEqual(['id'])
    })

    test('docs:columns-from-object/extract-writable-shape', () => {
        // doc-start
        const shape = extractWritableShapeFrom(tOrganization)
        // doc-end
        // Shape is { columnName: 'columnName' } for each writable column.
        assertType<Exact<typeof shape, {
            id:        'id'
            name:      'name'
            plan:      'plan'
            createdAt: 'createdAt'
        }>>()
        expect(shape).toEqual({
            id:        'id',
            name:      'name',
            plan:      'plan',
            createdAt: 'createdAt',
        })
    })
})
