import type { NConnection } from '../utils/sourceName.js'
import type { QueryRunner } from '../queryRunners/QueryRunner.js'
import { MariaDBSqlBuilder } from '../sqlBuilders/MariaDBSqlBuilder.js'
import type { TransactionIsolationLevel } from './AbstractConnection.js'
import { AbstractAdvancedConnection } from './AbstractAdvancedConnection.js'

export abstract class MariaDBConnection</*in|out*/ NAME extends string> extends AbstractAdvancedConnection<NConnection<'mariaDB', NAME>> {
 
    protected uuidStrategy: 'string' | 'uuid' = 'uuid'

    /**
     * Minimum MariaDB version the generated SQL must support, encoded as
     * `major * 1_000_000 + minor * 1_000 + patch` (e.g. `10_005_000` for
     * MariaDB 10.5.0, `10_003_003` for MariaDB 10.3.3, `13_000_001` for
     * MariaDB 13.0.1). Defaults to `Number.POSITIVE_INFINITY` (latest).
     *
     * Recognised breakpoints:
     * - `>= 13_000_001`: column references on a table-or-view returned by
     *   `.oldValues()` are emitted as `OLD_VALUE(col)` inside `UPDATE ... RETURNING`
     *   (added in MariaDB 13.0.1 via MDEV-5092). Bare column references on the
     *   updated table continue to mean the post-update value inside `RETURNING`,
     *   so a single statement can return both old and new values. Note: MariaDB
     *   only supports `RETURNING` on single-table `UPDATE`s; referencing old
     *   values of joined tables is not supported by the engine.
     * - `>= 10_005_000`: the `RETURNING` clause (supported on `INSERT` and
     *   `DELETE` since MariaDB 10.5) is emitted on `INSERT` to retrieve the
     *   last inserted id directly from the statement. Below this breakpoint,
     *   the last inserted id reported by the underlying connector after the
     *   query execution is used instead.
     * - `>= 10_003_003`: the `VALUE(col)` function (added in MariaDB 10.3.3 as
     *   part of MDEV-12172, renaming `VALUES(col)` to avoid the clash with the
     *   standard Table Value Constructors syntax introduced in the same
     *   release) is emitted inside `ON DUPLICATE KEY UPDATE` to reference the
     *   values being inserted. Below this breakpoint the legacy `VALUES(col)`
     *   name is emitted instead. The 10.3 line went GA at 10.3.7, so every
     *   stable 10.3 release is past this breakpoint.
     *
     * Note: `SEQUENCE` support was added in MariaDB 10.3.0 (MDEV-10139). The
     * `sequence(...)` builder and `autogeneratedPrimaryKeyBySequence(...)`
     * emit `NEXTVAL(seq)` / `LASTVAL(seq)`; both fail at the server on older
     * versions, so don't expose sequences when targeting MariaDB < 10.3.
     */
    protected override compatibilityVersion: number = Number.POSITIVE_INFINITY

    constructor(queryRunner: QueryRunner, sqlBuilder = new MariaDBSqlBuilder()) {
        super(queryRunner, sqlBuilder)
        queryRunner.useDatabase('mariaDB')
    }

    isolationLevel(level: 'read uncommitted' | 'read committed' | 'repeatable read' | 'serializable', accessMode?: 'read write' | 'read only'): TransactionIsolationLevel
    isolationLevel(accessMode: 'read write' | 'read only'): TransactionIsolationLevel
    isolationLevel(level: 'read uncommitted' | 'read committed' | 'repeatable read' | 'serializable' | 'read write' | 'read only', accessMode?: 'read write' | 'read only'): TransactionIsolationLevel {
        if (level === 'read write' || level === 'read only') {
            return [undefined, accessMode] as any
        }
        if (accessMode) {
            return [level, accessMode] as any
        }
        return [level] as any
    }
}
