import type { NAggregate, NConnection, NSource } from '../utils/sourceName.js'
import type { QueryRunner } from '../queryRunners/QueryRunner.js'
import { MariaDBSqlBuilder } from '../sqlBuilders/MariaDBSqlBuilder.js'
import type { AggregatedArrayColumns, SourceOfAggregatedArray, TransactionIsolationLevel } from './AbstractConnection.js'
import { AbstractAdvancedConnection } from './AbstractAdvancedConnection.js'
import type { AggregatedArrayValueSource, AggregatedArrayValueSourceProjectableAsNullable, IStringValueSource, IValueSource, StringValueSource, ValueSourceOf } from '../expressions/values.js'
import { __getValueSourcePrivate } from '../expressions/values.js'
import type { ResultObjectValuesForAggregatedArray } from '../complexProjections/resultWithOptionalsAsUndefined.js'
import type { ResultObjectValuesProjectedAsNullableForAggregatedArray } from '../complexProjections/resultWithOptionalsAsNull.js'
import { source, valueType } from '../utils/symbols.js'
import { AggregateFunctions1or2ValueSource, AggregateValueAsArrayValueSource } from '../internal/ValueSourceImpl.js'
import type { QueryColumns } from '../sqlBuilders/SqlBuilder.js'
import type { SameDB } from '../utils/ITableOrView.js'
import type { Default } from '../expressions/Default.js'
import { DefaultImpl } from '../expressions/Default.js'

export abstract class MariaDBConnection</*in|out*/ NAME extends string> extends AbstractAdvancedConnection<NConnection<'mariaDB', NAME>> {

    /**
     * How UUID values are stored: in MariaDB's native `UUID` column type (`'uuid'`,
     * requiring MariaDB 10.7+) or in a character column such as `CHAR(36)` (`'string'`).
     *
     * **Both strategies currently emit identical SQL, by nature and not by omission** —
     * unlike MySQL's `binary` strategy, which needs `UUID_TO_BIN` / `BIN_TO_UUID`, or
     * SQLite's and Oracle's. MariaDB's native `UUID` compares, concatenates and measures
     * exactly like a `CHAR(36)`, the driver hands both back as a string, and binding a
     * string parameter against either needs no conversion — so there is nothing for the
     * builder to do differently. The property declares the application's schema intent and
     * is kept as the seam for a future strategy that does need one; don't take the absence
     * of a `_getUuidStrategy()` on the MariaDB builder for an unwired knob.
     */
    protected uuidStrategy: 'string' | 'uuid' = 'uuid'

    /**
     * Minimum MariaDB version the generated SQL must support, encoded as
     * `major * 1_000_000 + minor * 1_000 + patch` (e.g. `10_005_000` for
     * MariaDB 10.5.0, `10_003_003` for MariaDB 10.3.3, `13_000_001` for
     * MariaDB 13.0.1). Defaults to `Number.POSITIVE_INFINITY` (latest).
     *
     * Recognised breakpoints:
     * - `>= 13_000_001`: column references on a table-or-view returned by
     *   `.oldValues()` are emitted as `OLD_VALUE(col)` inside `UPDATE ... RETURNING`
     *   (added in MariaDB 13.0.1 via MDEV-5092). Bare column references on the
     *   updated table continue to mean the post-update value inside `RETURNING`,
     *   so a single statement can return both old and new values. Note: MariaDB
     *   only supports `RETURNING` on single-table `UPDATE`s; referencing old
     *   values of joined tables is not supported by the engine.
     * - `>= 10_005_000`: the `RETURNING` clause (supported on `INSERT` and
     *   `DELETE` since MariaDB 10.5) is emitted on `INSERT` to retrieve the
     *   last inserted id directly from the statement. Below this breakpoint,
     *   the last inserted id reported by the underlying connector after the
     *   query execution is used instead.
     * - `>= 10_003_003`: the `VALUE(col)` function (added in MariaDB 10.3.3 as
     *   part of MDEV-12172, renaming `VALUES(col)` to avoid the clash with the
     *   standard Table Value Constructors syntax introduced in the same
     *   release) is emitted inside `ON DUPLICATE KEY UPDATE` to reference the
     *   values being inserted. Below this breakpoint the legacy `VALUES(col)`
     *   name is emitted instead. The 10.3 line went GA at 10.3.7, so every
     *   stable 10.3 release is past this breakpoint.
     *
     * Note: `SEQUENCE` support was added in MariaDB 10.3.0 (MDEV-10139). The
     * `sequence(...)` builder and `autogeneratedPrimaryKeyBySequence(...)`
     * emit `NEXTVAL(seq)` / `LASTVAL(seq)`; both fail at the server on older
     * versions, so don't expose sequences when targeting MariaDB < 10.3.
     */
    protected override compatibilityVersion: number = Number.POSITIVE_INFINITY

    /**
     * Use MariaDB's native, platform-dependent `round(<double>)` when applying
     * `.round()` / `.roundn(n)` to a `DOUBLE` expression (most commonly anything
     * that flows through `.divide(...)` or `.asDouble()`, which the SqlBuilder
     * casts to `DOUBLE`).
     *
     * Per the MariaDB manual, `ROUND()` over an exact-value number (DECIMAL)
     * breaks ties by rounding **away from zero** (so `round(0.5) → 1`), while over
     * an approximate-value number (DOUBLE) the result depends on the C library,
     * which rounds half to even on the usual platforms (so `round(0.5) → 0` and
     * `round(2.5) → 2`). ts-sql-query rounds away from zero on every dialect, so
     * by default the library casts the operand of `.round()` back to an exact type
     * to make the behavior portable and predictable across dialects.
     *
     * Setting this flag to `true` opts out of the cast: the result of `.round()`
     * then follows whatever `round(<double>)` does on the underlying C library.
     * Use it when you want MariaDB's native semantics — typically because the
     * application is single-dialect and prefers the IEEE 754 round-to-even
     * tie-breaking common on modern systems, or because existing queries depend
     * on it.
     */
    protected usePlatformDependentRound: boolean = false

    constructor(queryRunner: QueryRunner, sqlBuilder = new MariaDBSqlBuilder()) {
        super(queryRunner, sqlBuilder)
        queryRunner.useDatabase('mariaDB')
    }

    aggregateAsArrayDistinct<COLUMNS extends AggregatedArrayColumns<NConnection<'mariaDB', NAME>>>(columns: COLUMNS): AggregatedArrayValueSourceProjectableAsNullable<SourceOfAggregatedArray<COLUMNS> | NAggregate<NConnection<'mariaDB', NAME>>, Array<{ [P in keyof ResultObjectValuesForAggregatedArray<COLUMNS>]: ResultObjectValuesForAggregatedArray<COLUMNS>[P] }>, Array<{ [P in keyof ResultObjectValuesProjectedAsNullableForAggregatedArray<COLUMNS>]: ResultObjectValuesProjectedAsNullableForAggregatedArray<COLUMNS>[P] }>, 'required'> {
        return new AggregateValueAsArrayValueSource(columns as QueryColumns, 'InnerResultObject', 'required', true)
    }
    aggregateAsArrayOfOneColumnDistinct<VALUE extends IValueSource<any, any, any, any>>(value: VALUE): AggregatedArrayValueSource<VALUE[typeof source] | NAggregate<NConnection<'mariaDB', NAME>>, Array<VALUE[typeof valueType]>, 'required'> {
        return new AggregateValueAsArrayValueSource(value, 'InnerResultObject', 'required', true)
    }
    stringConcatDistinct<SOURCE extends NSource>(value: IStringValueSource<SOURCE, any> & SameDB<NConnection<'mariaDB', NAME>>): StringValueSource<SOURCE | NAggregate<NConnection<'mariaDB', NAME>>, 'optional'>
    stringConcatDistinct<SOURCE extends NSource>(value: IStringValueSource<SOURCE, any> & SameDB<NConnection<'mariaDB', NAME>>, separator: string): StringValueSource<SOURCE | NAggregate<NConnection<'mariaDB', NAME>>, 'optional'>
    stringConcatDistinct(value: ValueSourceOf<any>, separator?: string): ValueSourceOf<any> {
        const valuePrivate = __getValueSourcePrivate(value)
        return new AggregateFunctions1or2ValueSource('_stringConcatDistinct', separator, value, valuePrivate.__valueType, valuePrivate.__valueTypeName, 'optional', valuePrivate.__typeAdapter)
    }

    default(): Default {
        return new DefaultImpl()
    }

    isolationLevel(level: 'read uncommitted' | 'read committed' | 'repeatable read' | 'serializable', accessMode?: 'read write' | 'read only'): TransactionIsolationLevel
    isolationLevel(accessMode: 'read write' | 'read only'): TransactionIsolationLevel
    isolationLevel(level: 'read uncommitted' | 'read committed' | 'repeatable read' | 'serializable' | 'read write' | 'read only', accessMode?: 'read write' | 'read only'): TransactionIsolationLevel {
        if (level === 'read write' || level === 'read only') {
            return [undefined, level] as any
        }
        if (accessMode) {
            return [level, accessMode] as any
        }
        return [level] as any
    }
}
