// Compile-time negative tests for INSERT-shaped APIs on the sqlserver dialect.
// See `select.test.ts` for the rationale and conventions.

import { test, expect } from '../../../lib/testRunner.js'
import type { DBConnection } from '../domain/connection.js'
import { tIssue, tProject } from '../domain/connection.js'

// `connection` is type-only — the function below is checked by tsc but
// never invoked at runtime, so we don't need a real instance and don't
// open any driver-level resource just to make the file load.
declare const connection: DBConnection

function _typeNegatives() {
    // Rule: optional columns (here `body`) on an INSERT can be omitted, but
    // required columns must be present. The `status` field below is
    // required and missing, which must not compile.
    // @ts-expect-error required column `status` is missing from the INSERT
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        priority:  1,
    })

    // Rule: column value types must match. `priority` is `int`; passing a
    // string must not compile. tsgo reports the error at the offending
    // property, not at the values() call site, so the directive sits on
    // the property — see test/WRITING_TESTS.md for why this asymmetry exists.
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        status:    'open',
        // @ts-expect-error priority is int, not string
        priority:  'high',
    })

    // Rule: cannot insert columns that don't exist on the table. tsgo
    // reports the excess-property error at the property line itself —
    // directive placement matches.
    void connection.insertInto(tProject).values({
        organizationId:    1,
        name:              'x',
        slug:              'x',
        // @ts-expect-error 'nonExistentColumn' is not a column of tProject
        nonExistentColumn: 'x',
    })

    // Note: autogeneratedPrimaryKey('id', 'int') still accepts an
    // explicit id in insert values — the lib treats autogenerated as
    // "has a default" rather than "cannot be set". The schema-level
    // override holds at the SQL layer; no compile-time guard for now.
    // Rule: the conditional `disallowIfNoValueWhen(when, …)` must NOT clear a
    // missing-key obligation. `when` is a runtime value, so a column it names
    // is not statically guaranteed to have a value; the `*When` arm keeps the
    // named column in the still-missing set (like the whole `set*When` family,
    // which never narrows toward executability). Its unconditional sibling
    // `disallowIfNoValue(…)` may narrow because it throws eagerly when the
    // named column has no value.
    // Control: unconditional disallowIfNoValue narrows `projectId` out of the
    // missing set, so the later `.set(rest)` reaches an executable insert.
    void connection.insertInto(tIssue).dynamicSet()
        .disallowIfNoValue('projectId must have a value', 'projectId')
        .set({ number: 1, title: 'x', status: 'open', priority: 1 })
        .executeInsert()
    // Guard: the `*When` arm does not narrow, so `projectId` is still missing
    // after the other required columns are set and the insert is not executable.
    void connection.insertInto(tIssue).dynamicSet()
        .disallowIfNoValueWhen(false, 'projectId must have a value', 'projectId')
        .set({ number: 1, title: 'x', status: 'open', priority: 1 })
        // @ts-expect-error disallowIfNoValueWhen must not make a still-incomplete insert executable
        .executeInsert()
}

test('insert-negative-types', () => {
    expect(typeof _typeNegatives).toBe('function')
})
