// Compile-time negative tests for INSERT-shaped APIs on the mysql dialect.
// See `select.test.ts` for the rationale and conventions.

import { test, expect } from '../../../lib/testRunner.js'
import { MockQueryRunner } from '../../../../src/queryRunners/MockQueryRunner.js'
import { DBConnection, tIssue, tProject } from '../domain/connection.js'

const connection = new DBConnection(new MockQueryRunner(() => undefined, 'mySql'))

function _typeNegatives() {
    // Rule: optional columns (here `body`) on an INSERT can be omitted, but
    // required columns must be present. The `status` field below is
    // required and missing, which must not compile.
    // @ts-expect-error required column `status` is missing from the INSERT
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        priority:  1,
    })

    // Rule: column value types must match. `priority` is `int`; passing a
    // string must not compile. tsgo reports the error at the offending
    // property, not at the values() call site, so the directive sits on
    // the property — see test/MAINTAINING.md for why this asymmetry exists.
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        status:    'open',
        // @ts-expect-error priority is int, not string
        priority:  'high',
    })

    // Rule: cannot insert columns that don't exist on the table. tsgo
    // reports the excess-property error at the property line itself —
    // directive placement matches.
    void connection.insertInto(tProject).values({
        organizationId:    1,
        name:              'x',
        slug:              'x',
        // @ts-expect-error 'nonExistentColumn' is not a column of tProject
        nonExistentColumn: 'x',
    })

    // Note: autogeneratedPrimaryKey('id', 'int') still accepts an
    // explicit id in insert values — the lib treats autogenerated as
    // "has a default" rather than "cannot be set". The schema-level
    // override holds at the SQL layer; no compile-time guard for now.
}

test('insert-negative-types', () => {
    expect(typeof _typeNegatives).toBe('function')
})
