// Compile-time negative tests for INSERT-shaped APIs on the mysql dialect.
// See `select.test.ts` for the rationale and conventions.

import { test, expect } from '../../../lib/testRunner.js'
import type { DBConnection } from '../domain/connection.js'
import { tIssue, tProject } from '../domain/connection.js'
import { Table } from '../../../../src/Table.js'

// `connection` is type-only — the function below is checked by tsc but
// never invoked at runtime, so we don't need a real instance and don't
// open any driver-level resource just to make the file load.
declare const connection: DBConnection

function _typeNegatives() {
    // Rule: autogeneratedPrimaryKeyBySequence is only typed on mariaDB / oracle /
    // postgreSql / sqlServer connections; on MySqlConnection the method's
    // "this: OfDB<...>" constraint excludes it, so declaring a column with it
    // does not compile.
    class _TBySeq extends Table<DBConnection, '_TBySeq'> {
        // @ts-expect-error autogeneratedPrimaryKeyBySequence is not available on this dialect
        id = this.autogeneratedPrimaryKeyBySequence('id', 'audit_tag_seq', 'int')
        constructor() { super('audit_entry') }
    }
    void _TBySeq

    // Rule: optional columns (here `body`) on an INSERT can be omitted, but
    // required columns must be present. The `status` field below is
    // required and missing, which must not compile.
    // @ts-expect-error required column `status` is missing from the INSERT
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        priority:  1,
    })

    // Rule: column value types must match. `priority` is `int`; passing a
    // string must not compile. tsgo reports the error at the offending
    // property, not at the values() call site, so the directive sits on
    // the property — see test/WRITING_TESTS.md for why this asymmetry exists.
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        status:    'open',
        // @ts-expect-error priority is int, not string
        priority:  'high',
    })

    // Rule: cannot insert columns that don't exist on the table. tsgo
    // reports the excess-property error at the property line itself —
    // directive placement matches.
    void connection.insertInto(tProject).values({
        organizationId:    1,
        name:              'x',
        slug:              'x',
        // @ts-expect-error 'nonExistentColumn' is not a column of tProject
        nonExistentColumn: 'x',
    })

    // Note: autogeneratedPrimaryKey('id', 'int') still accepts an
    // explicit id in insert values — the lib treats autogenerated as
    // "has a default" rather than "cannot be set". The schema-level
    // override holds at the SQL layer; no compile-time guard for now.

    // Rule: MySQL's `ON DUPLICATE KEY UPDATE` has no inference target
    // (no column list, no `ON CONSTRAINT`), so `.onConflictOn(...)` is
    // not exposed on MySqlConnection; the targeted
    // `.onConflictOn(col).doUpdateSet({...})` form must not compile.
    void connection.insertInto(tProject)
        .values({ organizationId: 1, slug: 'x', name: 'y' })
        // @ts-expect-error onConflictOn is not typed on MySqlConnection
        .onConflictOn(tProject.organizationId, tProject.slug)

    // Rule: MySQL's `ON DUPLICATE KEY UPDATE` has no WHERE clause, so
    // `.where(cond)` chained after `.onConflictDoUpdateSet({...})` must
    // not compile. Runtime silently drops the WHERE — the typed surface
    // is what stops users from reaching the dropped path.
    void connection.insertInto(tProject)
        .values({ organizationId: 1, slug: 'x', name: 'y' })
        .onConflictDoUpdateSet({ name: 'z' })
        // @ts-expect-error .where after .onConflictDoUpdateSet is not typed on MySqlConnection
        .where(tProject.name.notEquals('z'))

    // Rule: after a shaped static one-shot `onConflictDoUpdateSet({renamed})` the
    // returned node stays shaped — a chained `.set(...)` and the `*When` arms accept
    // only the renamed shape keys, never the real columns.
    void connection.insertInto(tProject)
        .shapedAs({ orgId: 'organizationId', projectName: 'name', projectSlug: 'slug' })
        .set({ orgId: 1, projectName: 'a', projectSlug: 'b' })
        .onConflictDoUpdateSet({ projectName: 'one-shot' })
        // @ts-expect-error real column 'name' is not a shaped key on the chained on-conflict set
        .set({ name: 'chained' })
    void connection.insertInto(tProject)
        .shapedAs({ orgId: 'organizationId', projectName: 'name', projectSlug: 'slug' })
        .set({ orgId: 1, projectName: 'a', projectSlug: 'b' })
        .onConflictDoUpdateSet({ projectName: 'one-shot' })
        // @ts-expect-error real column 'name' is not a shaped key on the on-conflict setWhen
        .setWhen(true, { name: 'when' })

}

test('insert-negative-types', () => {
    expect(typeof _typeNegatives).toBe('function')
})
