// Rule `mirror-image` — asymmetric value validation across a `ctx.realDbEnabled`
// guard (DESIGN §1: "never guard the value assertion").
//
// A `realDbEnabled` guard splits a test into a mock path and a real-DB path.
// DESIGN §1 wants the value asserted in BOTH modes (ideally unconditionally).
// The smell is when ONE mode validates the value and the OTHER does not:
//
//   A — two-sided, weak branch (ANTIPATTERNS #1):
//     if (!ctx.realDbEnabled) expect(rows).toEqual([...])   // value
//     else                    expect(rows.length).toBeGreaterThan(0)  // shape only
//
//   B — one-sided guard (no else): the other mode gets nothing.
//     if (ctx.realDbEnabled) expect(rows.map(r => r.id).sort()).toEqual([1,2])  // mock validates nothing
//     if (!ctx.realDbEnabled) expect(rows).toEqual([...])                       // real validates nothing
//     if (ctx.realDbEnabled) return; expect(rows).toEqual([...])                // skip-real: real validates nothing
//
// Both polarities are handled. The one legitimate one-sided form is the
// real-ONLY skip `if (!ctx.realDbEnabled) return` (the whole test is real-only,
// e.g. error injection needing a live connection) — NOT flagged.
//
// A guard is NOT flagged when the test already asserts the value
// UNCONDITIONALLY (outside any guard) — then the guard is a supplementary
// real-only check, not the sole validation.
//
// Non-deterministic-result carve-out: a one-sided guard whose value assertion
// targets a result whose EXACT value depends on the real database's existing
// state is the documented-legitimate shape (EXTERNAL_CAVEATS "Could test more
// if real DB were on"). Such a value can only be pinned under the mock; on a
// real DB it would vary, and reproducing it would mean micromanaging seed data.
// The PRODUCING CALL is a syntactic anchor for that non-determinism, so the
// pattern is recognised mechanically rather than requiring a
// a suppression comment at every call site. The tolerated producers:
//   - `returningLastInsertedId()` — an engine-autogenerated id (sequence state);
//   - `executeInsert` / `executeUpdate` / `executeDelete` (EXACTLY those names,
//     not `executeInsertMany` / `executeUpdateNoneOrOne` / the `…Returning…`
//     variants) — the affected-/inserted-row COUNT, which depends on what is
//     already in the table;
//   - insert-from-select (always a subquery in this lib) also terminates in
//     `executeInsert`, so it is covered by the same anchor (and may itself be a
//     `returningLastInsertedId` insert);
//   - an INSERT whose `returning` projects ONLY the id column —
//     `returningOneColumn(t.id)` or `returning({ id: t.id })` (a single
//     property whose value is a `.id` access) — yields the same autogenerated
//     id and is how some dialects emulate `returningLastInsertedId`. Scoped to
//     INSERT (the chain calls `insertInto`): a `returning(t.id)` on an
//     UPDATE/DELETE returns a PRE-EXISTING id, which is deterministic.
// Recognised iff EVERY value assertion in the guarded branch targets an
// identifier bound from an await-chain calling one of those producers. A
// guarded assertion on something NOT from such a producer (a SELECT result, a
// `…ReturningOneRow` value, an INSERT `returning` projecting MORE than the id,
// an UPDATE/DELETE `returning(t.id)`) fails the test and stays flagged → it must
// be asserted unconditionally or carry a
// `// tests-audit-disable-next-line one-sided-guard -- <reason>`.
//
// A branch "validates the value" with deep equality, a scalar value matcher,
// or an APPROXIMATE comparison (`toBeCloseTo`, `toMatch`) — the JS-reorder
// remedy `expect([...rows].sort()).toEqual(...)` and float-precision
// `toBeCloseTo` are therefore proper value assertions, not weakenings. "Weak"
// is shape-only (`.length`, `toBeGreaterThan`, `Array.isArray`, `typeof`).
// `toBeNull` / `toBeUndefined` are SCALAR value matchers, NOT weak: `null` /
// `undefined` are single exact values (`toBe(null)`), so a branch asserting one —
// e.g. the real branch of a no-match `…NoneOrOne` query — pins the value exactly
// and is not a mirror-image weakening (verified: was a false positive on
// `delete.returning.execute-shapes.test.ts` / `delete.using.variants.test.ts`).
//
// A flagged case that is a genuine divergence carries
// `// tests-audit-disable-next-line mirror-image -- <reason>`.
//
// NOT-APPLICABLE / TODO[BUG] carve-out (mock-only only): a LIVE test marked
// `// NOT-APPLICABLE: <reason>` or `// TODO[BUG]: <reason>` (within its body or 3
// lines above) is allowed to be mock-only — either the dialect deliberately
// cannot validate it against the real engine (a dialect boundary; the test runs
// in the dialects that DO support it), or it reproduces a known bug and stays
// mock-only until the bug is fixed. Keyed on NOT-APPLICABLE/TODO[BUG] (NOT
// TODO[LIMITATION]): see `isNodeInMarkedTest` in ast.ts. It carves out only the
// `mock-only` forms (skip + swallow); `mirror-image` and `one-sided-guard`
// describe a test that DOES run in both modes, so they are not affected.

import ts from 'typescript'
import type { Finding } from '../types.js'
import { lineOf, markerLines, isNodeInMarkedTest } from '../ast.js'
import { NOT_APPLICABLE_OR_BUG_REASON } from '../reasons.js'

const DEEP = new Set(['toEqual', 'toStrictEqual', 'toMatchObject', 'toContainEqual'])
// `toBeNull` / `toBeUndefined` pin a single exact value (== `toBe(null)`), so
// they are scalar value matchers, not weak shape checks.
const SCALAR_VALUE = new Set(['toBe', 'toHaveProperty', 'toBeNull', 'toBeUndefined'])
const APPROX_VALUE = new Set(['toBeCloseTo', 'toMatch'])
const WEAK = new Set([
    'toBeGreaterThan', 'toBeGreaterThanOrEqual', 'toBeLessThan', 'toBeLessThanOrEqual',
    'toHaveLength', 'toBeDefined', 'toBeTruthy', 'toBeFalsy', 'toBeInstanceOf',
])
const SQL_GETTERS = new Set([
    'lastSql', 'lastParams', 'lastType',
    'lastNoTransactionSql', 'lastNoTransactionParams', 'lastNoTransactionType',
    'lastTransactionOpts',
])

type AssertKind = 'deep' | 'value' | 'weak'
interface Counts { deep: number, value: number, weak: number }

export function checkMirrorImage(sf: ts.SourceFile, file: string): Finding[] {
    const out: Finding[] = []
    const throwHelpers = collectThrowHelpers(sf)
    const naLines = markerLines(sf, NOT_APPLICABLE_OR_BUG_REASON)
    const visit = (n: ts.Node): void => {
        if (ts.isIfStatement(n)) inspectIf(n, sf, file, out, throwHelpers, naLines)
        if (ts.isCatchClause(n)) inspectCatch(n, sf, file, out, naLines)
        ts.forEachChild(n, visit)
    }
    visit(sf)
    return out
}

// `mock-only` (swallow form): a `catch` whose ONLY effect is
// `if (!ctx.realDbEnabled) throw e` — it rethrows under the mock but SWALLOWS
// the error on the real DB, so a real-engine failure passes as green.
function inspectCatch(cc: ts.CatchClause, sf: ts.SourceFile, file: string, out: Finding[], naLines: Set<number>): void {
    const stmts = cc.block.statements
    if (stmts.length !== 1) return
    const s = stmts[0]!
    if (!ts.isIfStatement(s) || s.elseStatement || classify(s.expression) !== 'whenFalse') return
    const thenStmts = stmtsOf(s.thenStatement)
    if (thenStmts.length !== 1 || !ts.isThrowStatement(thenStmts[0]!)) return
    // NOT-APPLICABLE / TODO[BUG] carve-out: a live test that the dialect
    // deliberately cannot validate against the real engine (NOT-APPLICABLE), or a
    // reproducible bug whose repro stays mock-only until fixed (TODO[BUG]), is
    // allowed to be mock-only here.
    if (isNodeInMarkedTest(cc, sf, naLines)) return
    out.push({
        rule: 'mock-only',
        file,
        line: lineOf(sf, cc),
        message: 'catch rethrows only under the mock (`if (!ctx.realDbEnabled) throw e`) — a real-DB error is silently swallowed, so a real-engine failure passes as green. Fix: let the real error surface and assert the result on the real engine; if the test is ABOUT the exception, assert it in both modes (`toThrow` / `expect(String(e)).toMatch(...)`) instead of swallowing on real. If this dialect deliberately cannot run it on a real engine, mark the test `// NOT-APPLICABLE: <reason>` (it runs in the dialects that support it); if it is a known reproducible bug, mark it `// TODO[BUG]: <reason>`',
    })
}

function inspectIf(ifStmt: ts.IfStatement, sf: ts.SourceFile, file: string, out: Finding[], throwHelpers: Set<string>, naLines: Set<number>): void {
    const guard = classify(ifStmt.expression)
    if (!guard) return

    const thenB = ifStmt.thenStatement
    const elseB = ifStmt.elseStatement

    const line = lineOf(sf, ifStmt)

    // --- A: two-sided guard (if/else) — `mirror-image` ---
    if (elseB) {
        let mockStmts: ts.Statement[], realStmts: ts.Statement[]
        if (guard === 'whenFalse') { mockStmts = stmtsOf(thenB); realStmts = stmtsOf(elseB) }
        else { realStmts = stmtsOf(thenB); mockStmts = stmtsOf(elseB) }
        const mock = countByClass(mockStmts)
        const real = countByClass(realStmts)
        const mockValidates = mock.deep + mock.value > 0
        const realValidates = real.deep + real.value > 0
        // Trigger on DEEP equality (a whole result set) — the ANTIPATTERNS #1
        // shape. A scalar `toBe` guard (autogen id / count) is the one-sided /
        // legitimate family, not this rule.
        if (mock.deep > 0 && !realValidates && real.weak > 0) {
            // Non-deterministic-but-BOUNDED carve-out (`random()`): the exact
            // value can't be pinned on real, but the range can — and MUST be, a
            // bare `typeof` hides real bugs. Tolerated only when the real branch
            // bounds the value (a lower AND an upper comparison); a `typeof`-only
            // real branch stays flagged with a case-specific message. See
            // AUDIT.md § mirror-image.
            if (usesRandom(ifStmt)) {
                if (hasBoundedCheck(realStmts)) return
                out.push({ rule: 'mirror-image', file, line, message: '`random()` is non-deterministic but bounded — the real-DB branch must bound the value to `[0, 1)` (`expect(r).toBeGreaterThanOrEqual(0)` and `expect(r).toBeLessThan(1)`), not just check its type. A bare `typeof` hides a real bug (a wrong function emitted, or a value out of range) — it once did (DESIGN §1)' })
            } else {
                out.push({ rule: 'mirror-image', file, line, message: 'mock branch asserts the value (deep equality) but the real-DB branch only checks shape (length/range) — a value regression slips through under --docker while the test stays green. Fix: give the real-DB branch the SAME value assertion — sort the unstable dimension in JS so one `expect(rows.slice().sort()).toEqual([...])` holds in both modes (DESIGN §1 / ANTIPATTERNS #1)' })
            }
        } else if (real.deep > 0 && !mockValidates && mock.weak > 0) {
            out.push({ rule: 'mirror-image', file, line, message: 'real-DB branch asserts the value (deep equality) but the mock branch only checks shape — the fast mock loop never validates the value, so a regression only surfaces under --docker. Fix: give the mock branch the SAME value assertion (the mock returns exactly `mockNext(...)`, so it can assert it precisely) (DESIGN §1)' })
        }
        return
    }

    // --- B: one-sided guard (no else) — `one-sided-guard` ---
    // The value must be validated in BOTH modes; a guard that gives only one
    // mode a value assertion leaves the other mode unvalidated.
    if (isBareExit(thenB)) {
        const fall = followingSiblings(ifStmt)
        if (guard === 'whenTrue') {
            // `if (ctx.realDbEnabled) return` — the test NEVER executes against the
            // real engine. The most severe form: nothing is validated on a real DB.
            // Exception-validation carve-out: a skip whose assertions are all about
            // an EXCEPTION (the lib throwing), not a result value, is tolerated
            // mock-only (see `validatesOnlyExceptions`).
            if (hasAnyAssertion(fall) && !validatesOnlyExceptions(fall, throwHelpers) && !isFileScopedMockOnly(fall, file) && !isNodeInMarkedTest(ifStmt, sf, naLines)) {
                out.push({ rule: 'mock-only', file, line, message: '`if (ctx.realDbEnabled) return` makes the test mock-only — it never executes against the real engine, so a real failure passes as green. Drive it on real (synthesise an off-shape input with fragmentWithType / rawFragment if the engine cannot produce it naturally) — DESIGN § Real-DB validation. If this dialect deliberately cannot validate it on a real engine, mark the test `// NOT-APPLICABLE: <reason>` (it runs in the dialects that support it); if it is a known reproducible bug, mark it `// TODO[BUG]: <reason>`' })
            }
        } else {
            // `if (!ctx.realDbEnabled) return` — real-only; the mock never validates.
            const c = countByClass(fall)
            if (c.deep + c.value > 0) {
                out.push({ rule: 'one-sided-guard', file, line, message: 'real-only (`if (!ctx.realDbEnabled) return`): the mock never validates the value — assert in both modes unless the mock genuinely cannot model the behaviour (DESIGN §1)' })
            }
        }
        return
    }

    const thenStmts = stmtsOf(thenB)
    const branch = countByClass(thenStmts)
    if (branch.deep + branch.value === 0) return // branch only checks shape / no value
    if (hasUnconditionalValue(ifStmt)) return    // an unconditional assertion already covers both modes
    if (isNonDeterministicResult(ifStmt, thenStmts)) return // value depends on real-DB state (autogen id / affected-row count): mock-only by nature
    const missing = guard === 'whenTrue' ? 'the mock' : 'the real DB'
    out.push({ rule: 'one-sided-guard', file, line, message: `one-sided ctx.realDbEnabled guard: ${missing} never validates the value. Assert it unconditionally (sort/ORDER BY for determinism), or give both modes a branch (DESIGN §1)` })
}

type Guard = 'whenTrue' | 'whenFalse' | null
function classify(expr: ts.Expression): Guard {
    if (isRealDbEnabled(expr)) return 'whenTrue'
    if (ts.isPrefixUnaryExpression(expr)
        && expr.operator === ts.SyntaxKind.ExclamationToken
        && isRealDbEnabled(expr.operand)) return 'whenFalse'
    if (ts.isParenthesizedExpression(expr)) return classify(expr.expression)
    return null
}
function isRealDbEnabled(e: ts.Expression): boolean {
    return ts.isPropertyAccessExpression(e) && e.name.text === 'realDbEnabled'
}

function stmtsOf(branch: ts.Statement | undefined): ts.Statement[] {
    if (!branch) return []
    return ts.isBlock(branch) ? [...branch.statements] : [branch]
}

function isBareExit(branch: ts.Statement): boolean {
    const stmts = stmtsOf(branch)
    if (stmts.length !== 1) return false
    const s = stmts[0]!
    return ts.isReturnStatement(s) || ts.isThrowStatement(s)
        || ts.isContinueStatement(s) || ts.isBreakStatement(s)
}

function followingSiblings(ifStmt: ts.IfStatement): ts.Statement[] {
    const p = ifStmt.parent
    let list: ts.NodeArray<ts.Statement> | undefined
    if (ts.isBlock(p)) list = p.statements
    else if (ts.isSourceFile(p)) list = p.statements
    if (!list) return []
    const idx = list.indexOf(ifStmt)
    return idx >= 0 ? list.slice(idx + 1) : []
}

// Does the enclosing test function assert the value OUTSIDE any realDbEnabled
// guard? If so, that unconditional assertion already covers both modes and the
// guard is supplementary — don't flag it as one-sided.
function hasUnconditionalValue(ifStmt: ts.IfStatement): boolean {
    const body = enclosingFunctionBody(ifStmt)
    if (!body) return false
    let found = false
    const visit = (n: ts.Node): void => {
        if (found) return
        if (ts.isIfStatement(n) && classify(n.expression)) return // skip guarded subtrees
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)) {
            const k = classifyAssertion(n.expression)
            if (k === 'deep' || k === 'value') { found = true; return }
        }
        ts.forEachChild(n, visit)
    }
    visit(body)
    return found
}

function enclosingFunctionBody(node: ts.Node): ts.Node | undefined {
    let p: ts.Node | undefined = node.parent
    while (p) {
        if (ts.isArrowFunction(p) || ts.isFunctionExpression(p)
            || ts.isFunctionDeclaration(p) || ts.isMethodDeclaration(p)) return p.body
        p = p.parent
    }
    return undefined
}

// The non-deterministic-result carve-out (see the header). A one-sided guard is
// NOT flagged when every value assertion in the guarded branch targets an
// identifier bound from an await-chain calling a tolerated producer.
//
// `executeInsert` / `executeUpdate` / `executeDelete` are matched EXACTLY (the
// affected-/inserted-row count); the many sibling terminals
// (`executeInsertMany`, `executeUpdateNoneOrOne`, every `…Returning…`) return
// rows/values and must NOT match.
const TOLERATED_RESULT_PRODUCERS = new Set([
    'returningLastInsertedId', 'executeInsert', 'executeUpdate', 'executeDelete',
])

function isNonDeterministicResult(ifStmt: ts.IfStatement, thenStmts: ts.Statement[]): boolean {
    const { names, impure } = guardedValueTargets(thenStmts)
    if (impure || names.length === 0) return false // a non-identifier value target can't be proven non-deterministic
    const body = enclosingFunctionBody(ifStmt)
    if (!body) return false
    return names.every((name) => bindsToleratedResult(body, name))
}

// The identifiers a guarded branch asserts the VALUE of. `impure` is set when a
// value/deep assertion targets something other than a plain identifier (a
// member access, a literal, an inline expression) — then we cannot trace it to
// a producer, so the carve-out must not apply.
function guardedValueTargets(stmts: ts.Statement[]): { names: string[], impure: boolean } {
    const names: string[] = []
    let impure = false
    const visit = (n: ts.Node): void => {
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)) {
            const kind = classifyAssertion(n.expression)
            if (kind === 'value' || kind === 'deep') {
                const arg = findExpectCall(n.expression.expression)?.arguments[0]
                if (arg && ts.isIdentifier(arg)) names.push(arg.text)
                else impure = true
            }
        }
        ts.forEachChild(n, visit)
    }
    for (const s of stmts) visit(s)
    return { names, impure }
}

// Is `name` bound from an await-chain that calls a tolerated producer? Matches
// `const name = await …producer()…` and the `name = await …` reassignment form.
function bindsToleratedResult(body: ts.Node, name: string): boolean {
    let found = false
    const visit = (n: ts.Node): void => {
        if (found) return
        if (ts.isVariableDeclaration(n) && ts.isIdentifier(n.name) && n.name.text === name
            && n.initializer && callsToleratedProducer(n.initializer)) { found = true; return }
        if (ts.isBinaryExpression(n) && n.operatorToken.kind === ts.SyntaxKind.EqualsToken
            && ts.isIdentifier(n.left) && n.left.text === name
            && callsToleratedProducer(n.right)) { found = true; return }
        ts.forEachChild(n, visit)
    }
    visit(body)
    return found
}

function callsToleratedProducer(node: ts.Node): boolean {
    let direct = false       // returningLastInsertedId / exact executeInsert|Update|Delete
    let hasInsert = false     // chain calls insertInto(...)
    let returnsIdOnly = false // returningOneColumn(t.id) / returning({ id: t.id })
    const visit = (n: ts.Node): void => {
        if (direct) return
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)) {
            const m = n.expression.name.text
            if (TOLERATED_RESULT_PRODUCERS.has(m)) { direct = true; return }
            if (m === 'insertInto') hasInsert = true
            else if (m === 'returningOneColumn' && isIdColumnRef(n.arguments[0])) returnsIdOnly = true
            else if (m === 'returning' && isOnlyIdColumn(n.arguments[0])) returnsIdOnly = true
        }
        ts.forEachChild(n, visit)
    }
    visit(node)
    // An INSERT returning only the id emulates returningLastInsertedId — tolerate
    // it the same way; an id `returning` on UPDATE/DELETE is a pre-existing id.
    return direct || (hasInsert && returnsIdOnly)
}

// A `.id` column reference (`t.id`) — the syntactic anchor for the
// autogenerated primary key (the index can't read the schema, so it keys off
// the conventional column name `id`).
function isIdColumnRef(e: ts.Expression | undefined): boolean {
    return !!e && ts.isPropertyAccessExpression(e) && e.name.text === 'id'
}

// A `returning({ id: t.id })` object that projects ONLY the id column: exactly
// one property, its value a `.id` access.
function isOnlyIdColumn(arg: ts.Expression | undefined): boolean {
    if (!arg || !ts.isObjectLiteralExpression(arg) || arg.properties.length !== 1) return false
    const p = arg.properties[0]!
    return ts.isPropertyAssignment(p) && isIdColumnRef(p.initializer)
}

// Exception-validation carve-out for the mock-only-skip form. A test whose
// purpose is to pin that the LIBRARY THROWS (not to validate a result value) is
// tolerated mock-only — forcing the throw on a real engine adds nothing the
// mock doesn't already prove. Tolerated iff the skipped body has ≥1
// exception-validation assertion and NO non-exception value/deep assertion (a
// value assertion still belongs on the real engine). An assertion validates an
// exception when it (A) uses a `toThrow`/`toThrowError` matcher or a `.rejects`
// chain, (B) targets a variable derived from a `catch` binding, or (C) targets
// the result of a same-file helper that surfaces a caught error
// (`fromDbReason`/`toDbReason` in the marshalling pattern).
// Deliberate, narrow, file-scoped mock-only exceptions: a named helper in a
// specific test file whose `if (ctx.realDbEnabled) return` skip is explicitly
// allowed. Each entry carries its reason (the suppression-comment philosophy
// at the tool level, since the file is symmetric across every cell and the
// reason is the same everywhere). Keep this list TINY — it is a hole in the
// rule. Documented in AUDIT.md § mock-only.
const FILE_SCOPED_MOCK_ONLY: ReadonlyArray<{ file: string, helper: string, reason: string }> = [
    {
        file: 'marshalling.transform-validation.test.ts',
        helper: 'fromDbValue',
        // `fromDbValue` injects (via mockNext) a representation a real driver of
        // this connector would never hand back (a JS bigint for an int column,
        // …); forcing it on a real engine via fragmentWithType is contrived and
        // cross-connector. Tolerated mock-only by project decision.
        reason: 'mock injects a driver representation the real connector never returns',
    },
]

// Every `expect(...)` in `fall` asserts on a call to the file's listed helper —
// the deliberate file-scoped exception above. Skips with a foreign assertion
// (an SQL snapshot, a different helper) are NOT covered.
function isFileScopedMockOnly(fall: ts.Node[], file: string): boolean {
    const entry = FILE_SCOPED_MOCK_ONLY.find((e) => file.endsWith('/' + e.file) || file === e.file)
    if (!entry) return false
    let count = 0
    let allMatch = true
    const visit = (n: ts.Node): void => {
        if (ts.isCallExpression(n) && ts.isIdentifier(n.expression) && n.expression.text === 'expect') {
            count++
            const arg = n.arguments[0]
            if (!arg || !callsNamedFn(arg, entry.helper)) allMatch = false
        }
        ts.forEachChild(n, visit)
    }
    for (const node of fall) visit(node)
    return count >= 1 && allMatch
}

// Unwrap `await` / parens and check the call's callee is exactly `name`.
function callsNamedFn(arg: ts.Expression, name: string): boolean {
    let cur: ts.Expression = arg
    while (ts.isAwaitExpression(cur) || ts.isParenthesizedExpression(cur)) cur = cur.expression
    return ts.isCallExpression(cur) && ts.isIdentifier(cur.expression) && cur.expression.text === name
}

// `random()` yields a non-deterministic but BOUNDED value: real can't assert
// the exact number, but it can — and must — bound it to `[0, 1)` (a bare
// `typeof === 'number'` hid a real bug once). A `random()` guard is tolerated
// only when the real-validating branch contains both a lower- and an
// upper-bound comparison.
const LOWER_BOUND = new Set(['toBeGreaterThan', 'toBeGreaterThanOrEqual'])
const UPPER_BOUND = new Set(['toBeLessThan', 'toBeLessThanOrEqual'])

function usesRandom(node: ts.Node): boolean {
    const body = enclosingFunctionBody(node)
    if (!body) return false
    let found = false
    const visit = (n: ts.Node): void => {
        if (found) return
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)
            && n.expression.name.text === 'random') { found = true; return }
        ts.forEachChild(n, visit)
    }
    visit(body)
    return found
}

function hasBoundedCheck(stmts: ts.Statement[]): boolean {
    let lo = false
    let hi = false
    const visit = (n: ts.Node): void => {
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)) {
            const m = n.expression.name.text
            if (LOWER_BOUND.has(m)) lo = true
            if (UPPER_BOUND.has(m)) hi = true
        }
        ts.forEachChild(n, visit)
    }
    for (const s of stmts) visit(s)
    return lo && hi
}

const THROW_MATCHERS = new Set(['toThrow', 'toThrowError'])

export function validatesOnlyExceptions(nodes: ts.Node[], throwHelpers: Set<string>): boolean {
    const errVars = collectErrorVars(nodes, throwHelpers)
    let exceptions = 0
    let realWorthy = 0
    const visit = (n: ts.Node): void => {
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)) {
            const expectCall = findExpectCall(n.expression.expression)
            if (expectCall) {
                if (isExceptionAssertion(n.expression, expectCall, errVars, throwHelpers)) exceptions++
                else {
                    const kind = classifyAssertion(n.expression)
                    if (kind === 'value' || kind === 'deep') realWorthy++
                }
            }
        }
        ts.forEachChild(n, visit)
    }
    for (const node of nodes) visit(node)
    return exceptions >= 1 && realWorthy === 0
}

function isExceptionAssertion(matcherAccess: ts.PropertyAccessExpression, expectCall: ts.CallExpression, errVars: Set<string>, throwHelpers: Set<string>): boolean {
    if (THROW_MATCHERS.has(matcherAccess.name.text)) return true
    if (chainHasRejects(matcherAccess.expression)) return true
    const arg = expectCall.arguments[0]
    if (!arg) return false
    return referencesAny(arg, errVars) || callsThrowHelper(arg, throwHelpers)
}

function chainHasRejects(node: ts.Expression): boolean {
    let cur: ts.Expression = node
    for (;;) {
        if (ts.isPropertyAccessExpression(cur)) {
            if (cur.name.text === 'rejects') return true
            cur = cur.expression
        } else if (ts.isCallExpression(cur)) {
            cur = cur.expression
        } else if (ts.isParenthesizedExpression(cur)) {
            cur = cur.expression
        } else return false
    }
}

// Unwrap `await` / parens and check the call's callee names a throw-helper.
function callsThrowHelper(arg: ts.Expression, throwHelpers: Set<string>): boolean {
    let cur: ts.Expression = arg
    while (ts.isAwaitExpression(cur) || ts.isParenthesizedExpression(cur)) cur = cur.expression
    return ts.isCallExpression(cur) && ts.isIdentifier(cur.expression) && throwHelpers.has(cur.expression.text)
}

// Variables that hold a caught error: each `catch (e)` binding, a value bound
// from a throw-helper call (`const reason = reasonOf(() => …)`), plus anything
// assigned/declared from one of those (`caught = e`). Bounded fixpoint.
export function collectErrorVars(nodes: ts.Node[], throwHelpers: Set<string>): Set<string> {
    const vars = new Set<string>()
    const seedCatch = (n: ts.Node): void => {
        if (ts.isCatchClause(n) && n.variableDeclaration && ts.isIdentifier(n.variableDeclaration.name)) {
            vars.add(n.variableDeclaration.name.text)
        }
        if (ts.isVariableDeclaration(n) && ts.isIdentifier(n.name) && n.initializer && callsThrowHelper(n.initializer, throwHelpers)) {
            vars.add(n.name.text)
        }
        if (ts.isBinaryExpression(n) && n.operatorToken.kind === ts.SyntaxKind.EqualsToken
            && ts.isIdentifier(n.left) && callsThrowHelper(n.right, throwHelpers)) {
            vars.add(n.left.text)
        }
        ts.forEachChild(n, seedCatch)
    }
    for (const node of nodes) seedCatch(node)
    for (let pass = 0; pass < 3; pass++) {
        let grew = false
        const propagate = (n: ts.Node): void => {
            if (ts.isBinaryExpression(n) && n.operatorToken.kind === ts.SyntaxKind.EqualsToken
                && ts.isIdentifier(n.left) && !vars.has(n.left.text) && referencesAny(n.right, vars)) {
                vars.add(n.left.text); grew = true
            }
            if (ts.isVariableDeclaration(n) && ts.isIdentifier(n.name) && !vars.has(n.name.text)
                && n.initializer && referencesAny(n.initializer, vars)) {
                vars.add(n.name.text); grew = true
            }
            ts.forEachChild(n, propagate)
        }
        for (const node of nodes) propagate(node)
        if (!grew) break
    }
    return vars
}

function referencesAny(node: ts.Node, names: Set<string>): boolean {
    let found = false
    const visit = (n: ts.Node): void => {
        if (found) return
        if (ts.isIdentifier(n) && names.has(n.text)) { found = true; return }
        ts.forEachChild(n, visit)
    }
    visit(node)
    return found
}

// Same-file functions that surface a caught error as their result — a `catch`
// whose block `return`s an expression referencing the error binding. The test
// asserting on such a call (C) is validating an exception, not a value.
export function collectThrowHelpers(sf: ts.SourceFile): Set<string> {
    const names = new Set<string>()
    const visit = (n: ts.Node): void => {
        if (ts.isFunctionDeclaration(n) && n.name && n.body && functionSurfacesError(n.body)) {
            names.add(n.name.text)
        }
        if (ts.isVariableDeclaration(n) && ts.isIdentifier(n.name) && n.initializer
            && (ts.isArrowFunction(n.initializer) || ts.isFunctionExpression(n.initializer))
            && functionSurfacesError(n.initializer.body)) {
            names.add(n.name.text)
        }
        ts.forEachChild(n, visit)
    }
    visit(sf)
    return names
}

export function functionSurfacesError(body: ts.Node): boolean {
    let found = false
    const visit = (n: ts.Node): void => {
        if (found) return
        if (ts.isCatchClause(n) && n.variableDeclaration && ts.isIdentifier(n.variableDeclaration.name)) {
            const ev = n.variableDeclaration.name.text
            let returnsErr = false
            const scan = (m: ts.Node): void => {
                if (returnsErr) return
                if (ts.isReturnStatement(m) && m.expression && referencesAny(m.expression, new Set([ev]))) { returnsErr = true; return }
                ts.forEachChild(m, scan)
            }
            scan(n.block)
            if (returnsErr) { found = true; return }
        }
        ts.forEachChild(n, visit)
    }
    visit(body)
    return found
}

// Any `expect(...)` assertion anywhere in the given statements — used to tell a
// real test body (mock-only when guarded) from a bare early-return guard.
function hasAnyAssertion(nodes: ts.Node[]): boolean {
    let found = false
    const visit = (n: ts.Node): void => {
        if (found) return
        if (ts.isCallExpression(n) && ts.isIdentifier(n.expression) && n.expression.text === 'expect') {
            found = true
            return
        }
        ts.forEachChild(n, visit)
    }
    for (const n of nodes) visit(n)
    return found
}

function countByClass(nodes: ts.Node[]): Counts {
    const c: Counts = { deep: 0, value: 0, weak: 0 }
    const visit = (n: ts.Node): void => {
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)) {
            const kind = classifyAssertion(n.expression)
            if (kind) c[kind]++
        }
        ts.forEachChild(n, visit)
    }
    for (const node of nodes) visit(node)
    return c
}

// Classify a matcher call `expect(arg).<matcher>(...)` by how strongly it
// validates the value. Returns null for non-assertions and SQL-snapshot ones.
function classifyAssertion(matcherAccess: ts.PropertyAccessExpression): AssertKind | null {
    const matcher = matcherAccess.name.text
    if (!DEEP.has(matcher) && !SCALAR_VALUE.has(matcher)
        && !APPROX_VALUE.has(matcher) && !WEAK.has(matcher)) return null

    const expectCall = findExpectCall(matcherAccess.expression)
    if (!expectCall) return null

    const arg = expectCall.arguments[0]
    if (arg && isSqlGetter(arg)) return null
    const argIsShape = arg ? isShapeArg(arg) : false

    if (WEAK.has(matcher)) return 'weak'
    if (APPROX_VALUE.has(matcher)) return 'value'   // approximate comparison still validates the value
    if (DEEP.has(matcher)) return argIsShape ? 'weak' : 'deep'
    // SCALAR_VALUE (toBe / toHaveProperty)
    return argIsShape ? 'weak' : 'value'
}

// The expect() argument is a shape probe, not the value: `x.length`,
// `typeof x`, `Array.isArray(x)`.
function isShapeArg(arg: ts.Expression): boolean {
    if (ts.isPropertyAccessExpression(arg) && arg.name.text === 'length') return true
    if (ts.isTypeOfExpression(arg)) return true
    if (ts.isCallExpression(arg) && ts.isPropertyAccessExpression(arg.expression)
        && arg.expression.name.text === 'isArray') return true
    return false
}

function findExpectCall(node: ts.Expression): ts.CallExpression | undefined {
    let cur: ts.Expression = node
    for (;;) {
        if (ts.isCallExpression(cur)) {
            if (ts.isIdentifier(cur.expression) && cur.expression.text === 'expect') return cur
            cur = cur.expression
        } else if (ts.isPropertyAccessExpression(cur)) {
            cur = cur.expression
        } else if (ts.isParenthesizedExpression(cur)) {
            cur = cur.expression
        } else {
            return undefined
        }
    }
}

function isSqlGetter(arg: ts.Expression): boolean {
    return ts.isPropertyAccessExpression(arg) && SQL_GETTERS.has(arg.name.text)
}
