// Rule `weak-matcher` — an assertion that pins shape/membership/pattern instead
// of the exact value. Strict in general (a test has no reason not to be precise),
// with limited flexibility for the one situation where exact pinning is genuinely
// impossible: reasoning about a DIAGNOSTIC text blob — an error message or a
// stack trace — where the content is partly runtime-dependent. There you match a
// pattern; everywhere else you pin the value.
//
// Two matcher families:
//   - STRUCTURAL asymmetric matchers — `expect.arrayContaining` /
//     `expect.objectContaining` / `expect.any` / `expect.anything`. They accept
//     extras / any type / a partial structure (`arrayContaining([1,2])` passes
//     for `[1,2,3]`, in any order). Flagged EVERYWHERE — they widen a *value's
//     shape*, never the right tool for a diagnostic string. Fix: the DESIGN §1
//     JS-reorder remedy `expect(rows.slice().sort()).toEqual([...])`.
//   - STRING-PATTERN matchers — `.toContain` / `.toMatch` (direct) and
//     `expect.stringMatching` (asymmetric). Weak on a value (a result that
//     contains the substring but differs elsewhere still passes). TOLERATED in
//     exactly ONE context — a DIAGNOSTIC blob, where the exact string genuinely
//     can't be pinned: an error message (`expect((e as Error).message)
//     .toContain('…')`) or a stack trace (`expect(stack).toMatch(/Query executed
//     at/)`).
//     NOT tolerated in a real-DB branch: a real-engine string value is usually
//     deterministic (known seed data) with only specific columns —  an
//     autogenerated `id`, a timestamp — varying, so the precise assertion is a
//     `toEqual` with those columns normalised/stripped (`expect(rows.map(({id,
//     ...r}) => r)).toEqual([...])`), NOT a blanket `toContain`. "Pinnable string
//     vs genuinely non-deterministic string" is not mechanically detectable, so
//     by the project principle (permit only a *detectable* valid case) the rule
//     stays strict; a genuinely-irreducible real string carries a
//     `tests-audit-disable-next-line`.
//     `toBeCloseTo` is NOT here — a float is non-pinnable even with known data
//     (rounding), so it gets its own real-branch-aware rule `close-to`.
//
// Engine: AST, no type checker. Diagnostic context is recognised structurally
// (`isDiagnosticContext`).

import ts from 'typescript'
import type { Finding } from '../types.js'
import { lineOf } from '../ast.js'

// Structure/type wideners — never legitimate for a diagnostic string, flagged
// everywhere.
const STRUCTURAL = new Set(['arrayContaining', 'objectContaining', 'any', 'anything'])
// Diagnostic-blob signals (error message OR stack trace). Property names…
const DIAG_PROP = new Set(['message', 'stack', 'cause'])
// …identifiers (prefix match, so `caught2` / `thrownErr` / `stackTrace` count)…
const DIAG_IDENT = /^(caught|thrown|error|err|reason|stack)/i
// …and helper calls that produce one (`reasonsInChain`, `getQueryExecutionStack`).
const DIAG_CALL = /reason|error|caught|thrown|stack/i

// Does the asserted expression reason about a diagnostic blob (error / stack)?
// The shared carve-out: there, pattern matching is the correct tool.
function isDiagnosticContext(node: ts.Expression): boolean {
    let found = false
    const scan = (n: ts.Node): void => {
        if (found) return
        if (ts.isPropertyAccessExpression(n) && DIAG_PROP.has(n.name.text)) { found = true; return }
        if (ts.isIdentifier(n) && DIAG_IDENT.test(n.text)) { found = true; return }
        if (ts.isCallExpression(n) && ts.isIdentifier(n.expression) && DIAG_CALL.test(n.expression.text)) { found = true; return }
        ts.forEachChild(n, scan)
    }
    scan(node)
    return found
}

// The `expect(X)` call a direct matcher property hangs off (through an optional
// `.not`), returning its actual argument X, or null.
function expectActual(receiver: ts.Expression): ts.Expression | null {
    let r = receiver
    if (ts.isPropertyAccessExpression(r) && r.name.text === 'not') r = r.expression
    if (ts.isCallExpression(r) && ts.isIdentifier(r.expression) && r.expression.text === 'expect') {
        return r.arguments[0] ?? null
    }
    return null
}

// For an asymmetric matcher nested inside `expect(X).matcher({ … })`, the actual
// X of the enclosing matcher call. `expect(X)` is the matcher call's RECEIVER, not
// an ancestor of the matcher's argument — so walk up to the nearest matcher call
// (a CallExpression with a property-access callee) and read its `expect(...)`
// receiver. Returns null if there is no enclosing `expect(...)` matcher call.
function enclosingExpectActual(node: ts.Node): ts.Expression | null {
    let p: ts.Node | undefined = node.parent
    while (p) {
        if (ts.isCallExpression(p) && ts.isPropertyAccessExpression(p.expression)) {
            const a = expectActual(p.expression.expression)
            if (a) return a
        }
        p = p.parent
    }
    return null
}

const STRING_PATTERN = new Set(['toContain', 'toMatch'])

function patternMessage(matcher: string): string {
    return `\`${matcher}\` pins only a substring/pattern, not the exact value — a result that matches but differs elsewhere still passes. Pin the value: normalise the non-deterministic columns and assert exactly (\`expect(rows.map(({ id, ...r }) => r)).toEqual([...])\`, sort an unstable order, the full SQL \`toMatchInlineSnapshot\`). Pattern matching is reserved for a diagnostic blob — an error message or a stack trace — where the exact string genuinely can't be pinned`
}

export function checkWeakMatcher(sf: ts.SourceFile, file: string): Finding[] {
    const out: Finding[] = []
    const visit = (n: ts.Node): void => {
        if (ts.isPropertyAccessExpression(n) && ts.isIdentifier(n.expression) && n.expression.text === 'expect') {
            // STRUCTURAL asymmetric matcher: `expect.arrayContaining(...)` etc. — always flagged.
            if (STRUCTURAL.has(n.name.text)) {
                out.push({
                    rule: 'weak-matcher',
                    file,
                    line: lineOf(sf, n),
                    message: `\`expect.${n.name.text}(...)\` pins only the shape/type, not the exact value — it accepts extras / any / a partial structure (e.g. \`arrayContaining([1,2])\` passes for \`[1,2,3]\`, in any order). Pin the value: sort the unstable dimension in JS and assert it exactly (\`expect(rows.slice().sort()).toEqual([...])\`)`,
                })
            }
            // Asymmetric string-pattern matcher: `expect.stringMatching(...)` —
            // tolerated only inside a diagnostic-context `expect(X)`.
            if (n.name.text === 'stringMatching') {
                const actual = enclosingExpectActual(n)
                if (!actual || !isDiagnosticContext(actual)) {
                    out.push({ rule: 'weak-matcher', file, line: lineOf(sf, n), message: patternMessage('`expect.stringMatching(...)`') })
                }
            }
        }
        // Direct string-pattern matchers `.toContain` / `.toMatch` — weak on a
        // value, tolerated on a diagnostic blob (error message / stack trace).
        if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression) && STRING_PATTERN.has(n.expression.name.text)) {
            const actual = expectActual(n.expression.expression)
            if (actual && !isDiagnosticContext(actual)) {
                out.push({ rule: 'weak-matcher', file, line: lineOf(sf, n), message: patternMessage(`\`.${n.expression.name.text}(...)\``) })
            }
        }
        ts.forEachChild(n, visit)
    }
    visit(sf)
    return out
}
