// Compile-time negative tests for INSERT-shaped APIs on the postgres dialect.
// See `select.test.ts` for the rationale and conventions.

import { test, expect } from '../../../lib/testRunner.js'
import { MockQueryRunner } from '../../../../src/queryRunners/MockQueryRunner.js'
import { DBConnection, tIssue, tOrganization, tProject } from '../domain/connection.js'

const connection = new DBConnection(new MockQueryRunner(() => undefined, 'postgreSql'))

function _typeNegatives() {
    // Rule: optional columns (here `body`) on an INSERT can be omitted, but
    // required columns must be present. The `status` field below is
    // required and missing, which must not compile.
    // @ts-expect-error required column `status` is missing from the INSERT
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        priority:  1,
    })

    // Rule: column value types must match. `priority` is `int`; passing a
    // string must not compile. The error surfaces at the values() call.
    // @ts-expect-error priority is int, not string
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        status:    'open',
        priority:  'high',
    })

    // Rule: cannot insert columns that don't exist on the table.
    // @ts-expect-error 'nonExistentColumn' is not a column of tProject
    void connection.insertInto(tProject).values({
        organizationId:    1,
        name:              'x',
        slug:              'x',
        nonExistentColumn: 'x',
    })

    // Note: autogeneratedPrimaryKey('id', 'int') still accepts an
    // explicit id in insert values — the lib treats autogenerated as
    // "has a default" rather than "cannot be set". The schema-level
    // override holds at the SQL layer; no compile-time guard for now.

    // Rule: PostgreSQL's `ON CONFLICT DO UPDATE` requires an explicit
    // conflict target — either a column list (`onConflictOn(col)`) or
    // a constraint name (`onConflictOnConstraint(name)`). The bare
    // `.onConflictDoUpdateSet({...})` / `.onConflictDoUpdateSetIfValue(...)`
    // / `.onConflictDoUpdateDynamicSet()` forms are typed only on
    // MariaDB, MySQL and SQLite (and the noopDB) — calling them on a
    // PostgreSqlConnection must not compile. Covers the .set(), .values()
    // and .from(select) entry chains so a regression in any of the three
    // shapes is caught here.
    const orgSelect = connection.selectFromNoTable().select({
        name: connection.const('x', 'string'),
        plan: connection.const('pro', 'string'),
    })
    // @ts-expect-error bare onConflictDoUpdateSet on PG via .set(...) — needs onConflictOn(col)
    void connection.insertInto(tOrganization).set({ name: 'x', plan: 'pro' }).onConflictDoUpdateSet({ plan: 'enterprise' })
    // @ts-expect-error bare onConflictDoUpdateSet on PG via .values([...]) — needs onConflictOn(col)
    void connection.insertInto(tOrganization).values([{ name: 'x', plan: 'pro' }]).onConflictDoUpdateSet({ plan: 'enterprise' })
    // @ts-expect-error bare onConflictDoUpdateSet on PG via .from(select) — needs onConflictOn(col)
    void connection.insertInto(tOrganization).from(orgSelect).onConflictDoUpdateSet({ plan: 'enterprise' })
    // @ts-expect-error bare onConflictDoUpdateSetIfValue on PG via .set(...) — needs onConflictOn(col)
    void connection.insertInto(tOrganization).set({ name: 'x', plan: 'pro' }).onConflictDoUpdateSetIfValue({ plan: 'enterprise' })
    // @ts-expect-error bare onConflictDoUpdateDynamicSet on PG via .set(...) — needs onConflictOn(col)
    void connection.insertInto(tOrganization).set({ name: 'x', plan: 'pro' }).onConflictDoUpdateDynamicSet()
}

test('insert-negative-types', () => {
    expect(typeof _typeNegatives).toBe('function')
})
