// Extract the test/ dimension, adapted for TEST questions: one row per
// test()/it() leaf (located in its matrix cell db × version × connector), plus
// the API names each leaf references. The test_ref ⋈ symbol/member join answers
// "which concrete tests exercise <symbol>, in which databases, saturated or
// not?" — the discovery/redundancy questions, at test() granularity.
//
// Parser only. Commented-out tests don't appear (they reference nothing at
// runtime); .skip/.todo/.fails are recorded with is_active = 0.

import ts from 'typescript'
import { resolve } from 'node:path'
import { walkFiles } from './walk.js'
import { resolveToken } from './resolve.js'
import type { DeclMap } from './resolve.js'
import type { Ids, TestBlockRow, TestRefRow } from './model.js'

export interface TestExtract {
    testBlocks: TestBlockRow[]
    testRefs: TestRefRow[]
}

export interface Cell { db: string, version: string, connector: string }

export function cellOf(relPath: string): Cell | null {
    // test/db/<db>/<version>/<connector>/<file>.test.ts
    // test/db/<db>/types.negative/<file>.test.ts
    const parts = relPath.split('/')
    if (parts[0] !== 'test' || parts[1] !== 'db') return null
    const db = parts[2]
    if (!db) return null
    if (parts[3] === 'types.negative') return { db, version: 'types.negative', connector: '' }
    const version = parts[3]
    const connector = parts[4]
    if (!version || !connector) return null
    return { db, version, connector }
}

const TEST_CALL = /^(test|it)$/
const INACTIVE_TAIL = /^(skip|todo|fails|skipIf)$/

// Resolve a test()/it()[.modifier] call: returns {name, active} or null.
export function asTestCall(call: ts.CallExpression): { active: boolean } | null {
    let expr = call.expression
    let active = true
    if (ts.isPropertyAccessExpression(expr)) {
        const tail = expr.name.text
        if (INACTIVE_TAIL.test(tail)) active = false
        // unwrap chained modifiers (test.skip.each etc.) down to the head
        while (ts.isPropertyAccessExpression(expr)) expr = expr.expression
    }
    if (ts.isIdentifier(expr) && TEST_CALL.test(expr.text)) return { active }
    return null
}

export function describeName(call: ts.CallExpression): string | null {
    let expr = call.expression
    while (ts.isPropertyAccessExpression(expr)) expr = expr.expression
    if (ts.isIdentifier(expr) && expr.text === 'describe') {
        const arg = call.arguments[0]
        if (arg && ts.isStringLiteralLike(arg)) return arg.text
    }
    return null
}

export function firstStringArg(call: ts.CallExpression): string | null {
    const a = call.arguments[0]
    return a && ts.isStringLiteralLike(a) ? a.text : null
}

// Collect referenced API-ish names within a node, ONE entry per OCCURRENCE with
// its 1-based line/col AND the token node (so the caller can checker-resolve it):
// bare identifiers and property-access member names (the fluent `.selectFrom`,
// `.groupBy`). Positions are taken against `sf`, so when `node` is a sub-tree of the
// whole file the coordinates are file-absolute. Filtering to real API names happens
// at query time via the join (name-based) or via the resolved FK (exact).
export interface RefPos { name: string, line: number, col: number, node: ts.Node }
export function collectRefPositions(node: ts.Node, sf: ts.SourceFile): RefPos[] {
    const out: RefPos[] = []
    const at = (token: ts.Node, name: string): void => {
        const lc = sf.getLineAndCharacterOfPosition(token.getStart(sf))
        out.push({ name, line: lc.line + 1, col: lc.character + 1, node: token })
    }
    const visit = (n: ts.Node): void => {
        if (ts.isPropertyAccessExpression(n)) {
            at(n.name, n.name.text)
            visit(n.expression)
            return
        }
        if (ts.isIdentifier(n)) at(n, n.text)
        ts.forEachChild(n, visit)
    }
    visit(node)
    return out
}

function processFile(relPath: string, ids: Ids, blocks: TestBlockRow[], refs: TestRefRow[], program: ts.Program, checker: ts.TypeChecker, declMap: DeclMap): void {
    const cell = cellOf(relPath)
    if (!cell) return
    // The autogenerated documentation cells are a SEPARATE world (extractDocTests.ts,
    // doc_test_block/doc_test_ref) — keep them out of the hand-written matrix dimension.
    if (cell.connector === 'documentation') return
    // The COMPILED source file from the unified Program — not a fresh parse.
    const sf = program.getSourceFile(resolve(relPath))
    if (!sf) return

    const stack: string[] = []
    const visit = (node: ts.Node): void => {
        if (ts.isCallExpression(node)) {
            const dn = describeName(node)
            if (dn !== null) {
                stack.push(dn)
                const cb = node.arguments.find(a => ts.isArrowFunction(a) || ts.isFunctionExpression(a))
                if (cb) ts.forEachChild(cb, visit)
                stack.pop()
                return
            }
            const tc = asTestCall(node)
            if (tc) {
                const tname = firstStringArg(node)
                if (tname !== null) {
                    const full = [...stack, tname].join(' > ')
                    const s = sf.getLineAndCharacterOfPosition(node.getStart(sf))
                    const e = sf.getLineAndCharacterOfPosition(node.getEnd())
                    const blockId = ids.next()
                    blocks.push({
                        id: blockId, file: relPath, db: cell.db, version: cell.version,
                        connector: cell.connector, name: full,
                        start_line: s.line + 1, end_line: e.line + 1, is_active: tc.active ? 1 : 0,
                    })
                    const cb = node.arguments.find(a => ts.isArrowFunction(a) || ts.isFunctionExpression(a))
                    if (cb) {
                        for (const r of collectRefPositions(cb, sf)) {
                            const res = resolveToken(checker, declMap, r.node)
                            refs.push({ test_block_id: blockId, symbol_name: r.name, line: r.line, col: r.col, resolved_symbol_id: res?.symbol_id ?? null, resolved_member_id: res?.member_id ?? null })
                        }
                    }
                }
                return
            }
        }
        ts.forEachChild(node, visit)
    }
    visit(sf)
}

export function extractTests(program: ts.Program, checker: ts.TypeChecker, declMap: DeclMap, ids: Ids): TestExtract {
    const files = walkFiles('test/db', '.test.ts')
    const testBlocks: TestBlockRow[] = []
    const testRefs: TestRefRow[] = []
    for (const f of files.sort()) processFile(f, ids, testBlocks, testRefs, program, checker, declMap)
    return { testBlocks, testRefs }
}
