// Documentation snippets for the Columns-from-object page
// (docs/advanced/columns-from-object.md). Demonstrates the
// `extract*From` helpers that turn a table/view definition into a
// projection or name list at runtime.

import { afterAll, beforeAll, beforeEach, describe, expect, test } from '../../../../lib/testRunner.js'
import { assertType, type Exact, type Extends } from '../../../../lib/assertType.js'
import {
    extractColumnsFrom,
    extractWritableColumnsFrom,
    extractWritableColumnNamesFrom,
    extractIdColumnsFrom,
    extractIdColumnNamesFrom,
    extractColumnNamesFrom,
    extractWritableShapeFrom,
    extractAutogeneratedIdColumnsFrom,
    extractAutogeneratedIdColumnNamesFrom,
    extractProvidedIdColumnsFrom,
    extractProvidedIdColumnNamesFrom,
} from '../../../../../src/extras/utils.js'
import { tCountry, tIssue, tOrganization } from '../../domain/connection.js'
import { ctx } from './setup.js'

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    test('docs:columns-from-object/extract-columns-select-all', async () => {
        ctx.mockNext({ id: 1, name: 'Acme Corp', plan: 'pro', verified: true, createdAt: new Date() })

        // doc-start
        const cols = extractColumnsFrom(tOrganization)
        const row = await ctx.conn.selectFrom(tOrganization)
            .where(tOrganization.id.equals(1))
            .select(cols)
            .executeSelectOne()
        // doc-end

        expect(ctx.lastSql).toMatchInlineSnapshot(`"select id as id, name as name, plan as plan, (verified = 'Y') as verified, created_at as "createdAt" from organization where id = $1"`)
        expect(ctx.lastParams).toMatchInlineSnapshot(`
          [
            1,
          ]
        `)
        // All columns are required so the result type is required.
        assertType<Extends<typeof row, {
            id:        number
            name:      string
            plan:      string
            verified:  boolean
            createdAt: Date
        }>>()
        expect(row.id).toBe(1)
        expect(row.name).toBe('Acme Corp')
        expect(row.plan).toBe('pro')
        expect(row.verified).toBe(true)
    })

    test('docs:columns-from-object/extract-columns-exclude-keys', async () => {
        // doc-start
        const cols = extractColumnsFrom(tOrganization, ['createdAt'])
        // doc-end
        // The excluded key is removed from the value type.
        assertType<Extends<typeof cols, { id: unknown; name: unknown; plan: unknown; verified: unknown }>>()
        expect(Object.keys(cols).sort()).toEqual(['id', 'name', 'plan', 'verified'])
    })

    test('docs:columns-from-object/extract-column-names', () => {
        // doc-start
        const names = extractColumnNamesFrom(tOrganization)
        // doc-end
        assertType<Extends<typeof names, string[]>>()
        expect(names.sort()).toEqual(['createdAt', 'id', 'name', 'plan', 'verified'])
    })

    test('docs:columns-from-object/extract-writable-columns', async () => {
        // doc-start
        const cols = extractWritableColumnsFrom(tIssue)
        // doc-end
        // Every column declared on a Table — `column`, `optionalColumn`,
        // `columnWithDefaultValue`, `optionalColumnWithDefaultValue`,
        // `primaryKey` and `autogeneratedPrimaryKey` — is writable.
        // The helper omits computed columns (none on tIssue) and any
        // column belonging to a view.
        const k = Object.keys(cols).sort()
        expect(k).toEqual([
            'assigneeId',
            'body',
            'createdAt',
            'estimatedHours',
            'externalRef',
            'id',
            'number',
            'parentId',
            'priority',
            'projectId',
            'status',
            'title',
            'updatedAt',
            'viewCount',
        ])
    })

    test('docs:columns-from-object/extract-id-columns', () => {
        // doc-start
        const cols = extractIdColumnsFrom(tOrganization)
        // doc-end
        // The PK is `id`.
        expect(Object.keys(cols)).toEqual(['id'])
    })

    test('docs:columns-from-object/extract-writable-shape', () => {
        // doc-start
        const shape = extractWritableShapeFrom(tOrganization)
        // doc-end
        // Shape is { columnName: 'columnName' } for each writable column.
        assertType<Exact<typeof shape, {
            id:        'id'
            name:      'name'
            plan:      'plan'
            verified:  'verified'
            createdAt: 'createdAt'
        }>>()
        expect(shape).toEqual({
            id:        'id',
            name:      'name',
            plan:      'plan',
            verified:  'verified',
            createdAt: 'createdAt',
        })
    })

    test('docs:columns-from-object/extract-writable-column-names', () => {
        // doc-start
        const names = extractWritableColumnNamesFrom(tOrganization)
        // doc-end
        assertType<Extends<typeof names, string[]>>()
        expect(names.sort()).toEqual(['createdAt', 'id', 'name', 'plan', 'verified'])
    })

    test('docs:columns-from-object/extract-id-column-names', () => {
        // doc-start
        const names = extractIdColumnNamesFrom(tOrganization)
        // doc-end
        expect(names).toEqual(['id'])
    })

    test('docs:columns-from-object/extract-autogenerated-id-columns', () => {
        // doc-start
        const cols = extractAutogeneratedIdColumnsFrom(tOrganization)
        // doc-end
        // tOrganization.id is autogeneratedPrimaryKey('id', 'int').
        expect(Object.keys(cols)).toEqual(['id'])
    })

    test('docs:columns-from-object/extract-autogenerated-id-column-names', () => {
        // doc-start
        const names = extractAutogeneratedIdColumnNamesFrom(tOrganization)
        // doc-end
        assertType<Extends<typeof names, string[]>>()
        expect(names).toEqual(['id'])
    })

    test('docs:columns-from-object/extract-provided-id-columns', () => {
        // doc-start
        const cols = extractProvidedIdColumnsFrom(tOrganization)
        // doc-end
        // tOrganization has no non-autogenerated PK column → empty object.
        expect(Object.keys(cols)).toEqual([])
    })

    test('docs:columns-from-object/extract-provided-id-column-names', () => {
        // doc-start
        const names = extractProvidedIdColumnNamesFrom(tOrganization)
        // doc-end
        assertType<Exact<typeof names, never[]>>()
        expect(names).toEqual([])
    })

    test('docs-extra:columns-from-object/extract-provided-id-on-a-provided-pk-table', () => {
        // tCountry.code is a provided (non-autogenerated) primary key, so the
        // provided-id helpers return it — the non-`never` branch the
        // autogenerated-PK tables (tOrganization above) never reach. The
        // name-returning helper's element type is now `'code'`, not the
        // `never` it collapses to for an autogenerated PK.
        const cols  = extractProvidedIdColumnsFrom(tCountry)
        const names = extractProvidedIdColumnNamesFrom(tCountry)
        expect(Object.keys(cols)).toEqual(['code'])
        assertType<Exact<typeof names, 'code'[]>>()
        expect(names).toEqual(['code'])
        // Symmetric exclusion: a provided PK is NOT an autogenerated id.
        expect(Object.keys(extractAutogeneratedIdColumnsFrom(tCountry))).toEqual([])
        expect(extractAutogeneratedIdColumnNamesFrom(tCountry)).toEqual([])
        // It IS a plain id column.
        expect(extractIdColumnNamesFrom(tCountry)).toEqual(['code'])
    })

    test('docs-extra:columns-from-object/extract-helpers-honor-the-exclude-argument', () => {
        // The docs page documents that EVERY `extract*From` helper accepts an
        // optional second argument — an array of property names to exclude
        // from the result. `extractColumnsFrom`'s exclude is shown above; this
        // pins the same exclude path for the rest of the family. The excluded
        // keys are dropped from both the value and (via `Exclude<…>`) the type.

        // Column-returning helpers.
        expect(Object.keys(extractWritableColumnsFrom(tIssue, ['body', 'assigneeId'])).sort()).toEqual([
            'createdAt', 'estimatedHours', 'externalRef', 'id', 'number', 'parentId',
            'priority', 'projectId', 'status', 'title', 'updatedAt', 'viewCount',
        ])
        expect(Object.keys(extractIdColumnsFrom(tOrganization, ['id']))).toEqual([])
        expect(Object.keys(extractAutogeneratedIdColumnsFrom(tOrganization, ['id']))).toEqual([])
        expect(Object.keys(extractProvidedIdColumnsFrom(tOrganization, ['name']))).toEqual([])

        // Name-returning helpers.
        expect(extractColumnNamesFrom(tOrganization, ['createdAt']).sort()).toEqual(['id', 'name', 'plan', 'verified'])
        expect(extractWritableColumnNamesFrom(tOrganization, ['createdAt']).sort()).toEqual(['id', 'name', 'plan', 'verified'])
        expect(extractIdColumnNamesFrom(tOrganization, ['id'])).toEqual([])
        expect(extractAutogeneratedIdColumnNamesFrom(tOrganization, ['id'])).toEqual([])
        expect(extractProvidedIdColumnNamesFrom(tOrganization, ['name'])).toEqual([])

        // Shape-returning helper.
        const shape = extractWritableShapeFrom(tOrganization, ['createdAt'])
        assertType<Exact<typeof shape, { id: 'id'; name: 'name'; plan: 'plan'; verified: 'verified' }>>()
        expect(shape).toEqual({ id: 'id', name: 'name', plan: 'plan', verified: 'verified' })
    })

})
