// Documentation snippets for the Utility types page
// (docs/advanced/utility-types.md). These are pure compile-time type
// utilities; the test bodies are mostly `assertType<Exact<...>>` so
// regressions in the public type surface are caught immediately.

import { beforeAll, afterAll, beforeEach, describe, test } from '../../../../lib/testRunner.js'
import { assertType, type Exact, type Extends } from '../../../../lib/assertType.js'
import type {
    ColumnKeys, WritableColumnKeys, WritableShapeFor,
    IdColumnKeys, AutogeneratedIdColumnKeys, ProvidedIdColumnKeys,
    InsertableValues, InsertableRow,
    UpdatableValues, UpdatableRow,
    SelectedValues, SelectedRow,
    UpdatableOnInsertConflictValues, UpdatableOnInsertConflictRow,
} from '../../../../../src/extras/types.js'
import { tIssue, tOrganization, tProject } from '../../domain/connection.js'
import { ctx } from './setup.js'

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    test('docs:utility-types/column-keys', () => {
        // doc-start
        type OrgColumns = ColumnKeys<typeof tOrganization>
        // doc-end
        assertType<Exact<OrgColumns, 'id' | 'name' | 'plan' | 'verified' | 'createdAt'>>()
    })

    test('docs:utility-types/writable-column-keys', () => {
        // doc-start
        type OrgWritable = WritableColumnKeys<typeof tOrganization>
        // doc-end
        // All columns of tOrganization are writable (no computed/virtual).
        assertType<Exact<OrgWritable, 'id' | 'name' | 'plan' | 'verified' | 'createdAt'>>()
    })

    test('docs:utility-types/writable-shape', () => {
        // doc-start
        type OrgShape = WritableShapeFor<typeof tOrganization>
        // doc-end
        assertType<Exact<OrgShape, {
            id:        'id'
            name:      'name'
            plan:      'plan'
            verified:  'verified'
            createdAt: 'createdAt'
        }>>()
    })

    test('docs:utility-types/id-column-keys', () => {
        // doc-start
        type OrgId = IdColumnKeys<typeof tOrganization>
        // doc-end
        assertType<Exact<OrgId, 'id'>>()
    })

    test('docs:utility-types/autogenerated-id-keys', () => {
        // doc-start
        type OrgAuto = AutogeneratedIdColumnKeys<typeof tOrganization>
        // doc-end
        // The id is autogenerated via autogeneratedPrimaryKey('id', 'int').
        // It also includes columns with defaults (verified, createdAt) by
        // the current implementation — the type matches
        // `WritableDBColumnWithDefaultValue` not strictly PK.
        assertType<Extends<'id', OrgAuto>>()
        assertType<Extends<OrgAuto, 'id' | 'verified' | 'createdAt'>>()
    })

    test('docs:utility-types/provided-id-keys', () => {
        // doc-start
        type OrgProvided = ProvidedIdColumnKeys<typeof tOrganization>
        // doc-end
        // No non-autogenerated PK columns → never.
        assertType<Exact<OrgProvided, never>>()
    })

    test('docs-extra:utility-types/insertable-values', () => {
        // The insert API requires the writable, non-autogenerated, non-
        // default fields. For tOrganization those are name and plan
        // (id is autogenerated, createdAt has a default).
        type OrgInsert = InsertableValues<typeof tOrganization>
        // Sanity check at least one mandatory field
        assertType<Extends<OrgInsert, { name: string }>>()
    })

    test('docs-extra:utility-types/insertable-row-accepts-value-sources', () => {
        // InsertableRow is the looser variant that also accepts
        // IValueSource expressions (e.g. tProject.organizationId).
        type ProjInsertRow = InsertableRow<typeof tProject>
        // Use Extends in this direction — the type is broader than
        // InsertableValues.
        const probe: ProjInsertRow = {
            organizationId: 1,
            slug:           'demo',
            name:           'demo',
        }
        void probe
    })

    test('docs-extra:utility-types/updatable-values', () => {
        type IssueUpdate = UpdatableValues<typeof tIssue>
        assertType<Extends<{ status: string }, IssueUpdate>>()
    })

    test('docs-extra:utility-types/updatable-row-accepts-value-sources', () => {
        type IssueUpdateRow = UpdatableRow<typeof tIssue>
        // Same logic as InsertableRow — UpdatableRow accepts value
        // sources in addition to literals.
        const probe: IssueUpdateRow = {
            title: 'new title',
        }
        void probe
    })

    test('docs-extra:utility-types/selected-values', () => {
        // SelectedValues mirrors the result type of `selectFrom(t).select(...)`
        // with all columns picked.
        type OrgSelected = SelectedValues<typeof tOrganization>
        // The selected type contains required fields for required cols.
        assertType<Extends<OrgSelected, { id: number; name: string; plan: string }>>()
    })

    test('docs-extra:utility-types/selected-row-is-alias', () => {
        type A = SelectedRow<typeof tOrganization>
        type B = SelectedValues<typeof tOrganization>
        assertType<Exact<A, B>>()
    })

    test('docs:utility-types/updatable-on-insert-conflict-values', () => {
        // Section "Updatable values in case of conflict on insert" — the
        // type of the object accepted by `.onConflictDoUpdateSet({...})`
        // when no value-sources are supplied.
        // doc-start
        type OrgUpsert = UpdatableOnInsertConflictValues<typeof tOrganization>
        // doc-end
        const probe: OrgUpsert = { plan: 'enterprise' }
        void probe
    })

    test('docs:utility-types/updatable-on-insert-conflict-row', () => {
        // Section "Updatable row in case of conflict on insert" — same
        // intent as the *Values type but also accepts SQL value-sources.
        // doc-start
        type OrgUpsertRow = UpdatableOnInsertConflictRow<typeof tOrganization>
        // doc-end
        const probe: OrgUpsertRow = { plan: 'enterprise' }
        void probe
    })
})
