-- Schema for the shared "project management" domain, oracle dialect.
-- Uses IDENTITY columns (Oracle 12c+).
--
-- "organization", "plan", "number" and "body" are Oracle reserved
-- keywords, so the library emits them double-quoted (case-sensitive
-- identifiers). The DDL must create them with the matching quoted
-- form or the lookup fails with ORA-00942 / ORA-00904.

BEGIN EXECUTE IMMEDIATE 'DROP VIEW project_overview'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE issue CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE project CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_user CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "organization" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;

CREATE TABLE "organization" (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    "plan" VARCHAR2(32) NOT NULL,
    -- `verified` flag stored as Y/N so the connection.ts mapping can
    -- exercise CustomBooleanTypeAdapter on a real seed column.
    verified VARCHAR2(1) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE app_user (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    full_name VARCHAR2(255) NOT NULL,
    -- `verified` stored as Y/N — same CustomBooleanTypeAdapter mapping
    -- as organization.verified so cross-table comparisons need no remap.
    verified VARCHAR2(1) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE project (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    organization_id NUMBER NOT NULL,
    name VARCHAR2(255) NOT NULL,
    slug VARCHAR2(64) NOT NULL,
    -- `published` flag stored as t/f, a deliberately different
    -- CustomBooleanTypeAdapter mapping than organization/app_user.verified
    -- so column-vs-column comparisons hit the remap-with-case branch.
    published VARCHAR2(1) DEFAULT 'f' NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_project_org FOREIGN KEY (organization_id) REFERENCES "organization"(id),
    CONSTRAINT uk_project_slug UNIQUE (organization_id, slug)
);

CREATE TABLE issue (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    "number" NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    -- VARCHAR2 (not CLOB) so the driver returns strings directly; we don't
    -- need a Lob/stream here, and CLOB columns force `oracledb.fetchAsString
    -- = [oracledb.CLOB]` or per-column metadata setup before the value is
    -- usable.
    "body" VARCHAR2(4000),
    status VARCHAR2(32) NOT NULL,
    priority NUMBER NOT NULL,
    assignee_id NUMBER,
    parent_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- New-type columns exercising AbstractConnection value marshalling:
    -- bigint (view_count), double (estimated_hours), uuid (external_ref).
    view_count NUMBER(19) DEFAULT 0 NOT NULL,
    estimated_hours BINARY_DOUBLE,
    -- RAW(16), not VARCHAR2: the default Oracle uuid strategy ('built-in')
    -- stores uuids as RAW(16) and converts with UUID_TO_RAW / RAW_TO_UUID,
    -- so the column must accept RAW for raw_to_uuid(external_ref) to work.
    external_ref RAW(16),
    CONSTRAINT fk_issue_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_issue_assignee FOREIGN KEY (assignee_id) REFERENCES app_user(id),
    CONSTRAINT fk_issue_parent FOREIGN KEY (parent_id) REFERENCES issue(id),
    CONSTRAINT uk_issue_number UNIQUE (project_id, "number")
);

-- Stored procedures and functions exercised by
-- `exec.procedure-function.test.ts`. PL/SQL bodies contain internal
-- `;` so each block is kept as one statement by the
-- `CREATE [OR REPLACE] (PROCEDURE|FUNCTION)` branch of `splitStatements`
-- in `test/db/oracle/runners.ts`. Blank lines act as block delimiters
-- so each CREATE stays in its own block.

CREATE OR REPLACE PROCEDURE refresh_stats AS BEGIN NULL; END;

CREATE OR REPLACE PROCEDURE archive_project(p_id IN NUMBER, p_reason IN VARCHAR2) AS BEGIN UPDATE project SET archived_at = CURRENT_TIMESTAMP, name = name || ' [archived: ' || p_reason || ']' WHERE id = p_id; END;

CREATE OR REPLACE FUNCTION count_open_issues(p_id IN NUMBER) RETURN NUMBER AS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM issue WHERE project_id = p_id AND status = 'open'; RETURN v; END;

CREATE OR REPLACE FUNCTION project_name(p_id IN NUMBER) RETURN VARCHAR2 AS v VARCHAR2(255); BEGIN SELECT name INTO v FROM project WHERE id = p_id; RETURN v; END;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE issue_id_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE audit_tag_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;

CREATE SEQUENCE issue_id_seq START WITH 1;

CREATE SEQUENCE audit_tag_seq START WITH 1;

-- A class-based SQL view exercised by `view.basic.test.ts`. A plain
-- join of project + organization (no aggregation, no casts). The
-- `organization` table and its `plan` column are Oracle reserved words
-- so they stay double-quoted; the view's own output columns are plain
-- (unquoted) identifiers matching the View mapping in connection.ts.
CREATE OR REPLACE VIEW project_overview AS
SELECT p.id AS id,
       p.organization_id AS organization_id,
       p.name AS name,
       p.archived_at AS archived_at,
       o.name AS organization_name,
       o."plan" AS organization_plan
FROM project p
INNER JOIN "organization" o ON o.id = p.organization_id;
