-- Schema for the shared "project management" domain, oracle dialect.
-- Uses IDENTITY columns (Oracle 12c+).
--
-- "organization", "plan", "number" and "body" are Oracle reserved
-- keywords, so the library emits them double-quoted (case-sensitive
-- identifiers). The DDL must create them with the matching quoted
-- form or the lookup fails with ORA-00942 / ORA-00904.

BEGIN EXECUTE IMMEDIATE 'DROP VIEW project_overview'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP VIEW release_overview'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP VIEW col_matrix_view'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE project_review CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE project_release CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE audit_entry CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE webhook_event CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE calendar_year CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE invoice CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ledger_entry CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE issue_worklog CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE col_matrix CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE country CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE issue CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE project CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_user CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "organization" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE release_draft CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
CREATE TABLE "organization" (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    "plan" VARCHAR2(32) NOT NULL,
    -- `verified` flag stored as Y/N so the connection.ts mapping can
    -- exercise CustomBooleanTypeAdapter on a real seed column.
    verified VARCHAR2(1) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE app_user (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    full_name VARCHAR2(255) NOT NULL,
    -- `verified` stored as Y/N — same CustomBooleanTypeAdapter mapping
    -- as organization.verified so cross-table comparisons need no remap.
    verified VARCHAR2(1) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE project (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    organization_id NUMBER NOT NULL,
    name VARCHAR2(255) NOT NULL,
    slug VARCHAR2(64) NOT NULL,
    -- `published` flag stored as t/f, a deliberately different
    -- CustomBooleanTypeAdapter mapping than organization/app_user.verified
    -- so column-vs-column comparisons hit the remap-with-case branch.
    published VARCHAR2(1) DEFAULT 'f' NOT NULL,
    archived_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_project_org FOREIGN KEY (organization_id) REFERENCES "organization"(id),
    CONSTRAINT uk_project_slug UNIQUE (organization_id, slug)
);

CREATE TABLE issue (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    "number" NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    -- VARCHAR2 (not CLOB) so the driver returns strings directly; we don't
    -- need a Lob/stream here, and CLOB columns force `oracledb.fetchAsString
    -- = [oracledb.CLOB]` or per-column metadata setup before the value is
    -- usable.
    "body" VARCHAR2(4000),
    status VARCHAR2(32) NOT NULL,
    priority NUMBER NOT NULL,
    assignee_id NUMBER,
    parent_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- New-type columns exercising AbstractConnection value marshalling:
    -- bigint (view_count), double (estimated_hours), uuid (external_ref).
    view_count NUMBER(19) DEFAULT 0 NOT NULL,
    estimated_hours BINARY_DOUBLE,
    -- RAW(16), not VARCHAR2: the default Oracle uuid strategy ('built-in')
    -- stores uuids as RAW(16) and converts with UUID_TO_RAW / RAW_TO_UUID,
    -- so the column must accept RAW for raw_to_uuid(external_ref) to work.
    external_ref RAW(16),
    CONSTRAINT fk_issue_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_issue_assignee FOREIGN KEY (assignee_id) REFERENCES app_user(id),
    CONSTRAINT fk_issue_parent FOREIGN KEY (parent_id) REFERENCES issue(id),
    CONSTRAINT uk_issue_number UNIQUE (project_id, "number")
);

CREATE TABLE country (
    code VARCHAR2(2) PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    region VARCHAR2(32) NOT NULL
);

CREATE TABLE issue_worklog (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    work_date DATE NOT NULL,
    -- Oracle has no TIME type; localTime is carried in a TIMESTAMP.
    started_at TIMESTAMP,
    minutes NUMBER DEFAULT 0,
    duration_ms NUMBER(19),
    billable NUMBER(1),
    approved VARCHAR2(1),
    -- billed amount per worklog (customDouble 'Money') and an `invoiced`
    -- flag stored as int 1/0 (numeric CustomBooleanTypeAdapter overload).
    billed_amount BINARY_DOUBLE DEFAULT 0 NOT NULL,
    invoiced NUMBER(1) DEFAULT 0 NOT NULL,
    cost_cents NUMBER(10) DEFAULT 0 NOT NULL,
    activity VARCHAR2(16) NOT NULL,
    -- Nullable DB-computed column (declared optionalComputedColumn).
    activity_label VARCHAR2(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN UPPER(activity) ELSE NULL END) VIRTUAL,
    tag_label VARCHAR2(16) GENERATED ALWAYS AS (UPPER(activity)) VIRTUAL,
    tag_label_optional VARCHAR2(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN LOWER(activity) ELSE NULL END) VIRTUAL,
    CONSTRAINT fk_worklog_issue FOREIGN KEY (issue_id) REFERENCES issue(id) ON DELETE CASCADE
);

-- Bigint autogenerated PK + enum-defaulted column.
CREATE TABLE webhook_event (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    event_type VARCHAR2(16) DEFAULT 'created' NOT NULL,
    CONSTRAINT fk_webhook_issue FOREIGN KEY (issue_id) REFERENCES issue(id) ON DELETE CASCADE
);

-- Int caller-provided PK.
CREATE TABLE calendar_year (
    year_value NUMBER PRIMARY KEY,
    year_label VARCHAR2(64) NOT NULL
);

-- Int caller-provided PK carrying a scaling TypeAdapter (invoice_no stored x10).
CREATE TABLE invoice (
    invoice_no NUMBER PRIMARY KEY,
    total NUMBER NOT NULL
);

-- Every column factory carries its trailing-TypeAdapter overload.
-- entry_no autogenerated (plusOffsetAdapter, read +1000); amount/memo carry
-- scaledTenthAdapter (stored x10, read /10) over a DB DEFAULT; tag is virtual
-- (no DB column).
CREATE TABLE ledger_entry (
    entry_no NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    amount NUMBER DEFAULT 100 NOT NULL,
    memo NUMBER DEFAULT 50,
    discount NUMBER
);

CREATE TABLE project_release (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    version VARCHAR2(32) NOT NULL,
    channel VARCHAR2(16) NOT NULL,
    signing_key RAW(16),
    released_on DATE NOT NULL,
    cutoff_time TIMESTAMP NOT NULL,
    signed_off_at TIMESTAMP,
    -- REQUIRED customLocalDateTime twin of signed_off_at.
    published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_signed NUMBER(1),
    download_count NUMBER(19),
    avg_rating BINARY_DOUBLE,
    notes VARCHAR2(255) GENERATED ALWAYS AS ('release-' || version) VIRTUAL,
    CONSTRAINT fk_release_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT uk_release_version UNIQUE (project_id, version)
);

-- Project review fixture: non-boolean per-column TypeAdapter on score (int,
-- stored x10) + reviewer_code (string, bracketed), an OPTIONAL localDate
-- (review_date) and a REQUIRED localTime (review_time).
CREATE TABLE project_review (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    reviewer_code VARCHAR2(32) NOT NULL,
    score NUMBER NOT NULL,
    review_date DATE,
    review_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_review_project FOREIGN KEY (project_id) REFERENCES project(id)
);


-- Stored procedures and functions exercised by
-- `exec.procedure-function.test.ts`. PL/SQL bodies contain internal
-- `;` so each block is kept as one statement by the
-- `CREATE [OR REPLACE] (PROCEDURE|FUNCTION)` branch of `splitStatements`
-- in `test/db/oracle/runners.ts`. Blank lines act as block delimiters
-- so each CREATE stays in its own block.

CREATE OR REPLACE PROCEDURE refresh_stats AS BEGIN NULL; END;

CREATE OR REPLACE PROCEDURE archive_project(p_id IN NUMBER, p_reason IN VARCHAR2) AS BEGIN UPDATE project SET archived_at = CURRENT_TIMESTAMP, name = name || ' [archived: ' || p_reason || ']' WHERE id = p_id; END;

CREATE OR REPLACE FUNCTION count_open_issues(p_id IN NUMBER) RETURN NUMBER AS v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM issue WHERE project_id = p_id AND status = 'open'; RETURN v; END;

CREATE OR REPLACE FUNCTION project_name(p_id IN NUMBER) RETURN VARCHAR2 AS v VARCHAR2(255); BEGIN SELECT name INTO v FROM project WHERE id = p_id; RETURN v; END;

CREATE OR REPLACE FUNCTION total_view_count(p_id IN NUMBER) RETURN NUMBER AS v NUMBER; BEGIN SELECT COALESCE(SUM(view_count),0) INTO v FROM issue WHERE project_id = p_id; RETURN v; END;

CREATE OR REPLACE FUNCTION latest_issue_at(p_id IN NUMBER) RETURN TIMESTAMP AS v TIMESTAMP; BEGIN SELECT MAX(created_at) INTO v FROM issue WHERE project_id = p_id; RETURN v; END;

CREATE OR REPLACE FUNCTION estimated_total(p_id IN NUMBER) RETURN BINARY_DOUBLE AS v BINARY_DOUBLE; BEGIN SELECT COALESCE(SUM(estimated_hours),0) INTO v FROM issue WHERE project_id = p_id; RETURN v; END;

-- Constant-returning functions, one per remaining executeFunction return kind.
-- Oracle has no TIME type (localTime rides in a TIMESTAMP) and no SQL boolean
-- (booleans are NUMBER 0/1). ret_uuid returns the string form.

CREATE OR REPLACE FUNCTION ret_flag(p_id IN NUMBER) RETURN NUMBER AS BEGIN RETURN 1; END;

CREATE OR REPLACE FUNCTION ret_uuid(p_id IN NUMBER) RETURN VARCHAR2 AS BEGIN RETURN '0a8f9c1e-1111-4222-8333-444455556666'; END;

CREATE OR REPLACE FUNCTION ret_day(p_id IN NUMBER) RETURN DATE AS BEGIN RETURN DATE '2024-02-03'; END;

CREATE OR REPLACE FUNCTION ret_clock(p_id IN NUMBER) RETURN TIMESTAMP AS BEGIN RETURN TIMESTAMP '1970-01-01 14:25:36'; END;

CREATE OR REPLACE FUNCTION ret_activity(p_id IN NUMBER) RETURN VARCHAR2 AS BEGIN RETURN 'coding'; END;

CREATE OR REPLACE FUNCTION ret_channel(p_id IN NUMBER) RETURN VARCHAR2 AS BEGIN RETURN 'stable'; END;

CREATE OR REPLACE FUNCTION ret_semver(p_id IN NUMBER) RETURN VARCHAR2 AS BEGIN RETURN '1.0.0'; END;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE issue_id_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE audit_tag_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;

CREATE SEQUENCE issue_id_seq START WITH 1;

CREATE SEQUENCE audit_tag_seq START WITH 1;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE release_tag_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;

CREATE SEQUENCE release_tag_seq START WITH 1;

-- A class-based SQL view exercised by `view.basic.test.ts`. A plain
-- join of project + organization (no aggregation, no casts). The
-- `organization` table and its `plan` column are Oracle reserved words
-- so they stay double-quoted; the view's own output columns are plain
-- (unquoted) identifiers matching the View mapping in connection.ts.
CREATE TABLE audit_entry (
    id NUMBER PRIMARY KEY,
    action VARCHAR2(255) NOT NULL
);

CREATE OR REPLACE VIEW project_overview AS
SELECT p.id AS id,
       p.organization_id AS organization_id,
       p.name AS name,
       p.archived_at AS archived_at,
       o.name AS organization_name,
       o."plan" AS organization_plan
FROM project p
INNER JOIN "organization" o ON o.id = p.organization_id;

-- View side of the release columns (see vReleaseOverview in connection.ts).
CREATE OR REPLACE VIEW release_overview AS
SELECT r.id AS id,
       r.project_id AS project_id,
       r.version AS version,
       r.released_on AS released_on,
       r.signed_off_at AS signed_off_at,
       r.published_at AS published_stamp,
       r.published_at AS published_stamp_plain,
       r.version AS version_bracketed,
       CASE WHEN r.channel <> 'beta' THEN r.channel ELSE NULL END AS channel_bracketed,
       r.cutoff_time AS cutoff_clock,
       r.is_signed AS is_signed,
       r.download_count AS download_count,
       r.avg_rating AS avg_rating,
       r.signing_key AS signing_uuid,
       r.released_on AS release_day_plain,
       r.cutoff_time AS cutoff_plain,
       r.id AS release_ordinal,
       CASE WHEN r.download_count IS NOT NULL THEN r.id ELSE NULL END AS optional_release_ordinal,
       p.name AS project_name
FROM project_release r
INNER JOIN project p ON p.id = r.project_id;

-- release_draft: OPTIONAL enum/custom/customComparable columns so the
-- Nullable family reaches a real NULL row. Caller-provided int PK (no identity).
CREATE TABLE release_draft (
    id NUMBER PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    stage VARCHAR2(16),
    channel VARCHAR2(16),
    min_version VARCHAR2(32),
    budget BINARY_DOUBLE,
    target_day DATE,
    cutoff TIMESTAMP,
    scaled_cost NUMBER(10) DEFAULT 250 NOT NULL,
    shifted_amount BINARY_DOUBLE DEFAULT 300 NOT NULL,
    bracket_version VARCHAR2(32) DEFAULT '2.0.0' NOT NULL,
    bracket_channel VARCHAR2(16) DEFAULT 'stable' NOT NULL,
    bracket_activity VARCHAR2(16) DEFAULT 'coding' NOT NULL,
    shifted_stamp TIMESTAMP DEFAULT TIMESTAMP '2024-06-01 10:00:00' NOT NULL,
    shifted_count NUMBER(19) DEFAULT 5000 NOT NULL,
    shifted_rating BINARY_DOUBLE DEFAULT 4.5 NOT NULL,
    bracket_signing_key RAW(16) DEFAULT HEXTORAW('00000000000040008000000000000000') NOT NULL,
    shifted_release_day DATE DEFAULT DATE '2025-03-01' NOT NULL,
    shifted_cutoff TIMESTAMP DEFAULT TIMESTAMP '1970-01-01 09:00:00' NOT NULL
);

-- col_matrix: one plain, NOT NULL column per base kind. Every
-- tColMatrix* Table / the vColMatrix View reads these SAME columns through a
-- DIFFERENT column factory; the optionality/default/computed/pk distinction is
-- type-level only. Oracle has no TIME type — localTime is carried in a TIMESTAMP
-- (mirrors project_release.cutoff_time). uuid is RAW(16) (built-in strategy).
-- Caller-provided int PK (no IDENTITY).
CREATE TABLE col_matrix (
    id NUMBER PRIMARY KEY,
    m_int NUMBER NOT NULL,
    m_bigint NUMBER(19) NOT NULL,
    m_double BINARY_DOUBLE NOT NULL,
    m_bool NUMBER(1) NOT NULL,
    m_uuid RAW(16) NOT NULL,
    m_date DATE NOT NULL,
    m_time TIMESTAMP NOT NULL,
    m_datetime TIMESTAMP NOT NULL,
    m_str VARCHAR2(64) NOT NULL
);

CREATE OR REPLACE VIEW col_matrix_view AS
SELECT id, m_int, m_bigint, m_double, m_bool, m_uuid, m_date, m_time, m_datetime, m_str
FROM col_matrix;

-- Zero-arg function per base value kind. Custom kinds reuse the
-- base-kind function. One PL/SQL block per line (blank-line separated, matching
-- the other functions). m_uuid is RAW(16); cm_uuid converts it to the hyphenated
-- string via the built-in RAW_TO_UUID (inverse of the seed's UUID_TO_RAW). Oracle
-- has no TIME/native boolean: localTime rides in TIMESTAMP, boolean in NUMBER 0/1.

CREATE OR REPLACE FUNCTION cm_int RETURN NUMBER AS v NUMBER; BEGIN SELECT m_int INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_bigint RETURN NUMBER AS v NUMBER; BEGIN SELECT m_bigint INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_double RETURN BINARY_DOUBLE AS v BINARY_DOUBLE; BEGIN SELECT m_double INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_bool RETURN NUMBER AS v NUMBER; BEGIN SELECT m_bool INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_uuid RETURN VARCHAR2 AS v VARCHAR2(36); BEGIN SELECT RAW_TO_UUID(m_uuid) INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_date RETURN DATE AS v DATE; BEGIN SELECT m_date INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_time RETURN TIMESTAMP AS v TIMESTAMP; BEGIN SELECT m_time INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_datetime RETURN TIMESTAMP AS v TIMESTAMP; BEGIN SELECT m_datetime INTO v FROM col_matrix WHERE id = 1; RETURN v; END;

CREATE OR REPLACE FUNCTION cm_str RETURN VARCHAR2 AS v VARCHAR2(64); BEGIN SELECT m_str INTO v FROM col_matrix WHERE id = 1; RETURN v; END;
