-- Canonical seed dataset shared by every oracle variant. We insert explicit
-- IDs; the IDENTITY's internal sequence auto-aligns under
-- `GENERATED BY DEFAULT ON NULL`.

INSERT INTO organization (id, name, plan) VALUES (1, 'Acme Corp', 'pro');
INSERT INTO organization (id, name, plan) VALUES (2, 'Globex Ltd', 'free');

INSERT INTO app_user (id, email, full_name) VALUES (1, 'ada@acme.test',    'Ada Lovelace');
INSERT INTO app_user (id, email, full_name) VALUES (2, 'grace@acme.test',  'Grace Hopper');
INSERT INTO app_user (id, email, full_name) VALUES (3, 'alan@globex.test', 'Alan Turing');

INSERT INTO project (id, organization_id, name, slug) VALUES (1, 1, 'Marketing site',  'mktg-site');
INSERT INTO project (id, organization_id, name, slug) VALUES (2, 1, 'Internal tools',  'tools');
INSERT INTO project (id, organization_id, name, slug) VALUES (3, 2, 'Public API',      'public-api');
INSERT INTO project (id, organization_id, name, slug, archived_at) VALUES (4, 2, 'Legacy app', 'legacy', CURRENT_TIMESTAMP);

INSERT INTO issue (id, project_id, "NUMBER", title, body, status, priority, assignee_id) VALUES
    (1, 1, 1, 'Update hero copy',     NULL,            'open',        2, 1);
INSERT INTO issue (id, project_id, "NUMBER", title, body, status, priority, assignee_id) VALUES
    (2, 1, 2, 'Redesign navbar',      'Use new tokens', 'in_progress', 1, 2);
INSERT INTO issue (id, project_id, "NUMBER", title, body, status, priority, assignee_id) VALUES
    (3, 2, 1, 'Migrate to ESM',       NULL,            'open',        3, NULL);
INSERT INTO issue (id, project_id, "NUMBER", title, body, status, priority, assignee_id) VALUES
    (4, 3, 1, 'Document /v2/users',   'See ADR-014',   'closed',      2, 3);

-- Realign the identity sequences past the manually-set IDs.
ALTER TABLE organization MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
ALTER TABLE app_user MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
ALTER TABLE project MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
ALTER TABLE issue MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
