-- Canonical seed dataset shared by every oracle variant. We insert explicit
-- IDs; the IDENTITY's internal sequence auto-aligns under
-- `GENERATED BY DEFAULT ON NULL`.

INSERT INTO "organization" (id, name, "plan", verified) VALUES (1, 'Acme Corp', 'pro',  'Y');
INSERT INTO "organization" (id, name, "plan", verified) VALUES (2, 'Globex Ltd', 'free', 'N');

INSERT INTO app_user (id, email, full_name, verified) VALUES (1, 'ada@acme.test',    'Ada Lovelace', 'Y');
INSERT INTO app_user (id, email, full_name, verified) VALUES (2, 'grace@acme.test',  'Grace Hopper', 'Y');
INSERT INTO app_user (id, email, full_name, verified) VALUES (3, 'alan@globex.test', 'Alan Turing',  'N');

INSERT INTO project (id, organization_id, name, slug, published) VALUES (1, 1, 'Marketing site',  'mktg-site',  't');
INSERT INTO project (id, organization_id, name, slug, published) VALUES (2, 1, 'Internal tools',  'tools',      'f');
INSERT INTO project (id, organization_id, name, slug, published) VALUES (3, 2, 'Public API',      'public-api', 't');
INSERT INTO project (id, organization_id, name, slug, published, archived_at) VALUES (4, 2, 'Legacy app', 'legacy', 'f', CURRENT_TIMESTAMP);

-- Issues 1 and 2 carry a uuid `external_ref`; 3 and 4 leave it NULL. The
-- column is RAW(16), so the seed stores the uuid via UUID_TO_RAW — the same
-- built-in the default uuid strategy uses (RAW_TO_UUID reads it back). Both
-- values are UUID v4, which UUID_TO_RAW requires. The two uuids differ in
-- every substring the insensitive-`like` tests probe and neither contains the
-- `abc` token the dynamic-condition tests filter on.
INSERT INTO issue (id, project_id, "number", title, "body", status, priority, assignee_id, external_ref) VALUES
    (1, 1, 1, 'Update hero copy',     NULL,            'open',        2, 1,    UUID_TO_RAW('0a8f9c1e-1111-4222-8333-444455556666'));
INSERT INTO issue (id, project_id, "number", title, "body", status, priority, assignee_id, external_ref) VALUES
    (2, 1, 2, 'Redesign navbar',      'Use new tokens', 'in_progress', 1, 2,   UUID_TO_RAW('7b3e9d20-2222-4c55-9b66-dddd00009999'));
INSERT INTO issue (id, project_id, "number", title, "body", status, priority, assignee_id) VALUES
    (3, 2, 1, 'Migrate to ESM',       NULL,            'open',        3, NULL);
INSERT INTO issue (id, project_id, "number", title, "body", status, priority, assignee_id) VALUES
    (4, 3, 1, 'Document /v2/users',   'See ADR-014',   'closed',      2, 3);

-- Realign the identity sequences past the manually-set IDs.
ALTER TABLE "organization" MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
ALTER TABLE app_user MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
ALTER TABLE project MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
ALTER TABLE issue MODIFY (id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE);
