-- Schema for the shared "project management" domain, postgres dialect.
-- Idempotent: tests run setup against a fresh database each variant, but
-- having DROP IF EXISTS lets you re-apply by hand for debugging.

DROP VIEW IF EXISTS project_overview;
DROP VIEW IF EXISTS release_overview;
DROP VIEW IF EXISTS col_matrix_view;
DROP TABLE IF EXISTS project_review CASCADE;
DROP TABLE IF EXISTS project_release CASCADE;
DROP TABLE IF EXISTS audit_entry CASCADE;
DROP TABLE IF EXISTS webhook_event CASCADE;
DROP TABLE IF EXISTS calendar_year CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS ledger_entry CASCADE;
DROP TABLE IF EXISTS issue_worklog CASCADE;
DROP TABLE IF EXISTS col_matrix CASCADE;
DROP TABLE IF EXISTS temporal_precision CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS issue CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS organization CASCADE;

DROP TABLE IF EXISTS release_draft;
CREATE TABLE organization (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    plan VARCHAR(32) NOT NULL,
    -- `verified` flag stored as Y/N so the connection.ts mapping can
    -- exercise CustomBooleanTypeAdapter on a real seed column.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_user (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    -- `verified` stored as Y/N — same CustomBooleanTypeAdapter mapping
    -- as organization.verified so cross-table comparisons need no remap.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project (
    id SERIAL PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    -- `published` flag stored as t/f, a deliberately different
    -- CustomBooleanTypeAdapter mapping than organization/app_user.verified
    -- so column-vs-column comparisons hit the remap-with-case branch.
    published VARCHAR(1) NOT NULL DEFAULT 'f',
    archived_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, slug)
);

CREATE TABLE issue (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES project(id),
    number INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT,
    status VARCHAR(32) NOT NULL,
    priority INTEGER NOT NULL,
    assignee_id INTEGER REFERENCES app_user(id),
    parent_id INTEGER REFERENCES issue(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- New-type columns exercising AbstractConnection value marshalling:
    -- bigint (view_count), double (estimated_hours), uuid (external_ref).
    view_count BIGINT NOT NULL DEFAULT 0,
    estimated_hours DOUBLE PRECISION,
    external_ref VARCHAR(36),
    UNIQUE (project_id, number)
);

CREATE TABLE country (
    code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    region VARCHAR(32) NOT NULL
);

CREATE TABLE issue_worklog (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER NOT NULL REFERENCES issue(id) ON DELETE CASCADE,
    work_date DATE NOT NULL,
    started_at TIME,
    minutes INTEGER DEFAULT 0,
    duration_ms BIGINT,
    billable BOOLEAN,
    approved VARCHAR(1),
    -- billed amount per worklog (customDouble 'Money') and an `invoiced`
    -- flag stored as int 1/0 (numeric CustomBooleanTypeAdapter overload).
    billed_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    invoiced INTEGER NOT NULL DEFAULT 0,
    cost_cents INTEGER NOT NULL DEFAULT 0,
    activity VARCHAR(16) NOT NULL,
    -- Nullable DB-computed column (declared optionalComputedColumn).
    activity_label VARCHAR(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN UPPER(activity) ELSE NULL END) STORED,
    tag_label VARCHAR(16) GENERATED ALWAYS AS (UPPER(activity)) STORED,
    tag_label_optional VARCHAR(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN LOWER(activity) ELSE NULL END) STORED
);

-- Bigint autogenerated PK + enum-defaulted column.
CREATE TABLE webhook_event (
    id BIGSERIAL PRIMARY KEY,
    issue_id INTEGER NOT NULL REFERENCES issue(id) ON DELETE CASCADE,
    event_type VARCHAR(16) NOT NULL DEFAULT 'created'
);

-- Int caller-provided PK.
CREATE TABLE calendar_year (
    year_value INTEGER PRIMARY KEY,
    year_label VARCHAR(64) NOT NULL
);

-- Int caller-provided PK carrying a scaling TypeAdapter (invoice_no stored x10).
CREATE TABLE invoice (
    invoice_no INTEGER PRIMARY KEY,
    total INTEGER NOT NULL
);

-- Every column factory carries its trailing-TypeAdapter overload.
-- entry_no autogenerated (plusOffsetAdapter, read +1000); amount/memo carry
-- scaledTenthAdapter (stored x10, read /10) over a DB DEFAULT; tag is virtual
-- (no DB column).
CREATE TABLE ledger_entry (
    entry_no SERIAL PRIMARY KEY,
    amount INTEGER NOT NULL DEFAULT 100,
    memo INTEGER DEFAULT 50,
    discount INTEGER
);

CREATE TABLE project_release (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES project(id),
    version VARCHAR(32) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    signing_key VARCHAR(36),
    released_on DATE NOT NULL,
    cutoff_time TIME NOT NULL,
    signed_off_at TIMESTAMP,
    -- REQUIRED customLocalDateTime twin of signed_off_at.
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Plain-kind sources for the release_overview VIEW's per-kind read columns
    -- (boolean/bigint/double). uuid/localDate/localTime reuse signing_key/
    -- released_on/cutoff_time; the custom+adapter column reuses id.
    is_signed BOOLEAN,
    download_count BIGINT,
    avg_rating DOUBLE PRECISION,
    notes VARCHAR(255) GENERATED ALWAYS AS ('release-' || version) STORED,
    UNIQUE (project_id, version)
);

-- Project review fixture: hosts the column-factory kinds the other tables
-- don't expose — a non-boolean per-column TypeAdapter on `score` (int, stored
-- ×10 fixed-point) and `reviewer_code` (string, bracketed on read), an OPTIONAL
-- plain `localDate` (review_date) and a REQUIRED plain `localTime` (review_time).
CREATE TABLE project_review (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES project(id),
    reviewer_code VARCHAR(32) NOT NULL,
    score INTEGER NOT NULL,
    review_date DATE,
    review_time TIME NOT NULL
);

-- Stored procedures and functions exercised by
-- `exec.procedure-function.test.ts`. Each body is intentionally
-- trivial: the tests only assert on the SQL the SqlBuilder emits and
-- the round-trip through the driver / `executeProcedure` /
-- `executeFunction` plumbing.

DROP PROCEDURE IF EXISTS refresh_stats();
DROP PROCEDURE IF EXISTS archive_project(integer, varchar);
DROP FUNCTION IF EXISTS count_open_issues(integer);
DROP FUNCTION IF EXISTS project_name(integer);

CREATE PROCEDURE refresh_stats()
LANGUAGE plpgsql AS $$ BEGIN NULL; END; $$;

CREATE PROCEDURE archive_project(p_id integer, p_reason varchar)
LANGUAGE sql AS $$
    UPDATE project
       SET archived_at = CURRENT_TIMESTAMP,
           name        = name || ' [archived: ' || p_reason || ']'
     WHERE id = p_id
$$;

CREATE FUNCTION count_open_issues(p_id integer) RETURNS integer
LANGUAGE sql AS $$
    SELECT COUNT(*)::int FROM issue WHERE project_id = p_id AND status = 'open'
$$;

CREATE FUNCTION project_name(p_id integer) RETURNS varchar
LANGUAGE sql AS $$
    SELECT name FROM project WHERE id = p_id
$$;

DROP FUNCTION IF EXISTS total_view_count(integer);
DROP FUNCTION IF EXISTS latest_issue_at(integer);
DROP FUNCTION IF EXISTS estimated_total(integer);

CREATE FUNCTION total_view_count(p_id integer) RETURNS bigint
LANGUAGE sql AS $$ SELECT COALESCE(SUM(view_count), 0)::bigint FROM issue WHERE project_id = p_id $$;

CREATE FUNCTION latest_issue_at(p_id integer) RETURNS timestamp
LANGUAGE sql AS $$ SELECT MAX(created_at) FROM issue WHERE project_id = p_id $$;

CREATE FUNCTION estimated_total(p_id integer) RETURNS double precision
LANGUAGE sql AS $$ SELECT COALESCE(SUM(estimated_hours), 0)::double precision FROM issue WHERE project_id = p_id $$;

-- Null-propagating min/max helpers for the `minValueFunction` / `maxValueFunction`
-- opt-in (config.min-max-null-handling.test.ts). PostgreSQL's native `least` / `greatest`
-- IGNORE a NULL operand; these poison it to NULL instead, so a user who prefers the
-- function form over the CASE the builder emits by default can name them. `anycompatible`
-- keeps the operand's numeric type (int stays int, double stays double) — the same helper
-- the docs (postgresql.md) tell users to create.
DROP FUNCTION IF EXISTS greatest_strict(anycompatible, anycompatible);
DROP FUNCTION IF EXISTS least_strict(anycompatible, anycompatible);

CREATE FUNCTION greatest_strict(a anycompatible, b anycompatible) RETURNS anycompatible
LANGUAGE sql IMMUTABLE AS $$ SELECT CASE WHEN a IS NULL OR b IS NULL THEN NULL ELSE greatest(a, b) END $$;

CREATE FUNCTION least_strict(a anycompatible, b anycompatible) RETURNS anycompatible
LANGUAGE sql IMMUTABLE AS $$ SELECT CASE WHEN a IS NULL OR b IS NULL THEN NULL ELSE least(a, b) END $$;

-- Constant-returning functions, one per remaining executeFunction return kind
-- (boolean / uuid / date / time / and the varchar bases behind enum / custom /
-- customComparable). Each takes an ignored int arg to keep the `select fn($1)`
-- call shape identical to the functions above. The uuid function returns the
-- string form (not a native uuid/raw) so the value reaches the driver already
-- unwrapped.
DROP FUNCTION IF EXISTS ret_flag(integer);
DROP FUNCTION IF EXISTS ret_uuid(integer);
DROP FUNCTION IF EXISTS ret_day(integer);
DROP FUNCTION IF EXISTS ret_clock(integer);
DROP FUNCTION IF EXISTS ret_activity(integer);
DROP FUNCTION IF EXISTS ret_channel(integer);
DROP FUNCTION IF EXISTS ret_semver(integer);

CREATE FUNCTION ret_flag(p_id integer) RETURNS boolean
LANGUAGE sql AS $$ SELECT true $$;

CREATE FUNCTION ret_uuid(p_id integer) RETURNS varchar
LANGUAGE sql AS $$ SELECT CAST('0a8f9c1e-1111-4222-8333-444455556666' AS varchar) $$;

CREATE FUNCTION ret_day(p_id integer) RETURNS date
LANGUAGE sql AS $$ SELECT DATE '2024-02-03' $$;

CREATE FUNCTION ret_clock(p_id integer) RETURNS time
LANGUAGE sql AS $$ SELECT TIME '14:25:36' $$;

CREATE FUNCTION ret_activity(p_id integer) RETURNS varchar
LANGUAGE sql AS $$ SELECT CAST('coding' AS varchar) $$;

CREATE FUNCTION ret_channel(p_id integer) RETURNS varchar
LANGUAGE sql AS $$ SELECT CAST('stable' AS varchar) $$;

CREATE FUNCTION ret_semver(p_id integer) RETURNS varchar
LANGUAGE sql AS $$ SELECT CAST('1.0.0' AS varchar) $$;

-- Sequences exercised by `sequence.next-current-value.test.ts`.
-- `issueIdSeq` (typed `'int'`) reuses the sequence implicitly
-- created by `issue.id SERIAL` (PostgreSQL names it `issue_id_seq`);
-- dropping it explicitly would fail because `issue.id` depends on
-- it (2BP01). `auditTagSeq` (typed `'bigint'`) is independent and
-- created here. PostgreSQL sequences are 64-bit internally
-- regardless of the type hint, which only affects deserialization.

DROP SEQUENCE IF EXISTS audit_tag_seq;

CREATE SEQUENCE audit_tag_seq START 1;

DROP SEQUENCE IF EXISTS release_tag_seq;
CREATE SEQUENCE release_tag_seq START 1;

-- A class-based SQL view exercised by `view.basic.test.ts`. A plain
-- join of project + organization (no aggregation, no casts) so the
-- same shape is portable across every dialect.
CREATE TABLE audit_entry (
    id integer PRIMARY KEY,
    action VARCHAR(255) NOT NULL
);

CREATE VIEW project_overview AS
SELECT p.id AS id,
       p.organization_id AS organization_id,
       p.name AS name,
       p.archived_at AS archived_at,
       o.name AS organization_name,
       o.plan AS organization_plan
FROM project p
INNER JOIN organization o ON o.id = p.organization_id;

-- View side of the release columns (see vReleaseOverview in connection.ts).
CREATE VIEW release_overview AS
SELECT r.id AS id,
       r.project_id AS project_id,
       r.version AS version,
       r.released_on AS released_on,
       r.signed_off_at AS signed_off_at,
       r.published_at AS published_stamp,
       r.published_at AS published_stamp_plain,
       r.version AS version_bracketed,
       CASE WHEN r.channel <> 'beta' THEN r.channel ELSE NULL END AS channel_bracketed,
       r.cutoff_time AS cutoff_clock,
       r.is_signed AS is_signed,
       r.download_count AS download_count,
       r.avg_rating AS avg_rating,
       r.signing_key AS signing_uuid,
       r.released_on AS release_day_plain,
       r.cutoff_time AS cutoff_plain,
       r.id AS release_ordinal,
       CASE WHEN r.download_count IS NOT NULL THEN r.id ELSE NULL END AS optional_release_ordinal,
       p.name AS project_name
FROM project_release r
INNER JOIN project p ON p.id = r.project_id;

-- release_draft: OPTIONAL enum/custom/customComparable columns so the
-- Nullable family reaches a real NULL row. Caller-provided int PK (no identity).
CREATE TABLE release_draft (
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    stage VARCHAR(16),
    channel VARCHAR(16),
    min_version VARCHAR(32),
    budget DOUBLE PRECISION,
    target_day DATE,
    cutoff TIME,
    scaled_cost INTEGER NOT NULL DEFAULT 250,
    shifted_amount DOUBLE PRECISION NOT NULL DEFAULT 300,
    bracket_version VARCHAR(32) NOT NULL DEFAULT '2.0.0',
    bracket_channel VARCHAR(16) NOT NULL DEFAULT 'stable',
    bracket_activity VARCHAR(16) NOT NULL DEFAULT 'coding',
    shifted_stamp TIMESTAMP NOT NULL DEFAULT '2024-06-01 10:00:00',
    shifted_count BIGINT NOT NULL DEFAULT 5000,
    shifted_rating DOUBLE PRECISION NOT NULL DEFAULT 4.5,
    bracket_signing_key VARCHAR(36) NOT NULL DEFAULT '00000000-0000-4000-8000-000000000000',
    shifted_release_day DATE NOT NULL DEFAULT '2025-03-01',
    shifted_cutoff TIME NOT NULL DEFAULT '09:00:00'
);

-- col_matrix: one plain, NOT NULL column per base value kind.
-- Every tColMatrix* Table class and the vColMatrix View read these SAME columns
-- through a DIFFERENT column factory (column / optionalColumn /
-- columnWithDefaultValue / optionalColumnWithDefaultValue / computedColumn /
-- optionalComputedColumn / primaryKey + View column / optionalColumn). The
-- optionality / default / computed / primary-key distinction is type-level only,
-- so a single plain row drives every factory's per-kind read path. Caller-provided
-- int PK (no identity) keeps the per-dialect reset trivial.
CREATE TABLE col_matrix (
    id INTEGER PRIMARY KEY,
    m_int INTEGER NOT NULL,
    m_bigint BIGINT NOT NULL,
    m_double DOUBLE PRECISION NOT NULL,
    m_bool BOOLEAN NOT NULL,
    m_uuid VARCHAR(36) NOT NULL,
    m_date DATE NOT NULL,
    m_time TIME NOT NULL,
    m_datetime TIMESTAMP NOT NULL,
    m_str VARCHAR(64) NOT NULL
);

-- temporal_precision: a single microsecond-precision localDateTime column. Its
-- seed instant (12:30:59.999600) cannot be reached by the const-based subsecond
-- test — a JS Date only carries milliseconds — so this column is the only way to
-- lock the date-part getters' SQL-side truncation on a real microsecond value:
-- getSeconds() must stay 59 (not round to 60) and getMilliseconds() must stay 999
-- (not round to 1000, nor wrap to 0). Caller-provided int PK keeps reset trivial.
CREATE TABLE temporal_precision (
    id INTEGER PRIMARY KEY,
    micro_stamp TIMESTAMP NOT NULL
);

-- View side of col_matrix — surfaces the same per-kind read marshalling through
-- the View column / optionalColumn factories (vColMatrix).
CREATE VIEW col_matrix_view AS
SELECT id, m_int, m_bigint, m_double, m_bool, m_uuid, m_date, m_time, m_datetime, m_str
FROM col_matrix;

-- One zero-arg function per base value kind, each returning the col_matrix row-1
-- value of that kind (executeFunction return-kind + trailing
-- adapter fan-out, exercised by `exec.function-value-kinds.test.ts`). Custom
-- kinds reuse the base-kind function (customInt→cm_int, customDouble→cm_double,
-- customUuid→cm_uuid, customLocalDate→cm_date, customLocalTime→cm_time,
-- customLocalDateTime→cm_datetime, enum/custom/customComparable→cm_str). These
-- are declared AFTER col_matrix because a `LANGUAGE sql` body is parsed and
-- validated against the referenced table at CREATE time.
DROP FUNCTION IF EXISTS cm_int();
DROP FUNCTION IF EXISTS cm_bigint();
DROP FUNCTION IF EXISTS cm_double();
DROP FUNCTION IF EXISTS cm_bool();
DROP FUNCTION IF EXISTS cm_uuid();
DROP FUNCTION IF EXISTS cm_date();
DROP FUNCTION IF EXISTS cm_time();
DROP FUNCTION IF EXISTS cm_datetime();
DROP FUNCTION IF EXISTS cm_str();

CREATE FUNCTION cm_int() RETURNS integer
LANGUAGE sql AS $$ SELECT m_int FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_bigint() RETURNS bigint
LANGUAGE sql AS $$ SELECT m_bigint FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_double() RETURNS double precision
LANGUAGE sql AS $$ SELECT m_double FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_bool() RETURNS boolean
LANGUAGE sql AS $$ SELECT m_bool FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_uuid() RETURNS varchar
LANGUAGE sql AS $$ SELECT m_uuid FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_date() RETURNS date
LANGUAGE sql AS $$ SELECT m_date FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_time() RETURNS time
LANGUAGE sql AS $$ SELECT m_time FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_datetime() RETURNS timestamp
LANGUAGE sql AS $$ SELECT m_datetime FROM col_matrix WHERE id = 1 $$;

CREATE FUNCTION cm_str() RETURNS varchar
LANGUAGE sql AS $$ SELECT m_str FROM col_matrix WHERE id = 1 $$;
