import { SqliteConnection } from '../../../src/connections/SqliteConnection.js'
import { MockQueryRunner } from '../../../src/queryRunners/MockQueryRunner.js'
import { Table } from '../../../src/Table.js'
import { CustomBooleanTypeAdapter } from '../../../src/TypeAdapter.js'
import { View } from '../../../src/View.js'

import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'
import { PrismaClient } from '../../../src/examples/prisma/generated/sqlite/client.js'
import { PrismaQueryRunner } from '../../../src/queryRunners/PrismaQueryRunner.js'

import { BetterSqlite3QueryRunner } from '../../../src/queryRunners/BetterSqlite3QueryRunner.js'
import { Sqlite3QueryRunner } from '../../../src/queryRunners/Sqlite3QueryRunner.js'
import { BunSqliteQueryRunner } from '../../../src/queryRunners/BunSqliteQueryRunner.js'
import { BunSqlSqliteQueryRunner } from '../../../src/queryRunners/BunSqlSqliteQueryRunner.js'
import { NodeSqliteQueryRunner } from '../../../src/queryRunners/NodeSqliteQueryRunner.js'
import sqlite3InitModule from '@sqlite.org/sqlite-wasm'
import { Sqlite3WasmOO1QueryRunner } from '../../../src/queryRunners/Sqlite3WasmOO1QueryRunner.js'
import { SQL } from 'bun'
import { sync } from '../../../src/extras/sync.js'
import { SynchronousPromise } from "synchronous-promise";
import { parse as uuidParse, stringify as uuidStringify, v7 as uuidv7 } from "uuid";
import { type SqliteDateTimeFormat, type SqliteDateTimeFormatType } from "../../../src/connections/SqliteConfiguration.js";

class DBConnection extends SqliteConnection<'DBConnection'> {
    // insensitiveCollation = 'acs'

    protected override getDateTimeFormat() {
        return 'UTC as text using T separator and Z timezone' as const
    }

    bitwiseShiftLeft = this.buildFragmentWithArgs(
        this.arg('int', 'required'),
        this.arg('int', 'required')
    ).as((left, right) => {
        // The fragment here is: ${left} << ${right}
        // Could be another fragment like a function call: myFunction(${left}, ${right})
        return this.fragmentWithType('int', 'required').sql`${left} << ${right}`
    })

    bitwiseShiftLeft2 = this.buildFragmentWithMaybeOptionalArgs(
        this.arg('int', 'optional'),
        this.arg('int', 'optional')
    ).as((left, right) => {
        // The fragment here is: ${left} << ${right}
        // Could be another fragment like a function call: myFunction(${left}, ${right})
        return this.fragmentWithType('int', 'optional').sql`${left} << ${right}`
    })

    valuePlusOneEqualsIfValue = this.buildFragmentWithArgsIfValue(
        this.arg('int', 'required'),
        this.valueArg('int', 'optional')
    ).as((left, right) => {
        // The fragment here is: ${left} + 1 = ${right}
        // Could be another fragment like a function call: myFunction(${left}, ${right})
        return this.fragmentWithType('boolean', 'required').sql`${left} + 1 = ${right}`
    })

    forSystemTimeBetween = this.createTableOrViewCustomization<Date, Date>((table, alias, fromDate, toDate) => {
        const from = this.const(fromDate, 'localDateTime')
        const to = this.const(toDate, 'localDateTime')
        return this.rawFragment`${table} for system_time between ${from} and ${to} ${alias}`
    }) 

    myOwnProcedure(param1: number) {
        return this.executeProcedure('myOwnprocedure', [this.const(param1, 'int')]);
    }
     
    myOwnFunction(param1: number) {
        return this.executeFunction('myOwnFunction', [this.const(param1, 'int')], 'int', 'required');
    }
}

const tCompany = new class TCompany extends Table<DBConnection, 'TCompany'> {
    id = this.autogeneratedPrimaryKey('id', 'int')
    name = this.column('name', 'string')
    parentId = this.optionalColumn('parent_id', 'int')
    favouriteCustomerId = this.optionalColumn('parent_id', 'int')
    ubicationLatitude = this.optionalColumn('ubication_latitude', 'string')
    ubicationLongitude = this.optionalColumn('ubication_longitude', 'string')
    ubicationComment = this.optionalColumn('ubication_comment', 'string')
    constructor() {
        super('company'); // table name in the database
    }
}()

const tCustomer = new class TCustomer extends Table<DBConnection, 'TCustomer'> {
    id = this.autogeneratedPrimaryKey('id', 'int')
    firstName = this.column('first_name', 'string')
    lastName = this.column('last_name', 'string')
    birthday = this.optionalColumn('birthday', 'localDate')
    companyId = this.column('company_id', 'int')
    name = this.firstName.concat(' ').concat(this.lastName)
    age = this.optionalVirtualColumnFromFragment('int', (fragment) => {
        return fragment.sql`calculateAge(${this.birthday})`
    })
    constructor() {
        super('customer'); // table name in the database
    }
}()

const vCustomerAndCompany = new class VCustomerAndCompany extends View<DBConnection, 'VCustomerAndCompany'> {
    companyId = this.column('company_id', 'int')
    companyName = this.column('company_name', 'string')
    customerId = this.column('customer_id', 'int')
    customerFirstName = this.column('customer_first_name', 'string')
    customerLastName = this.column('customer_last_name', 'string')
    customerBirthday = this.optionalColumn('customer_birthday', 'localDate')
    constructor() {
        super('customer_company')
    }
}()
vCustomerAndCompany.as('testView')

const tCustomCompany = new class TCustomCompany extends Table<DBConnection, 'TCustomCompany'> {
    id = this.autogeneratedPrimaryKey('id', 'int');
    name = this.column('name', 'string');
    isBig = this.column('is_big', 'boolean', new CustomBooleanTypeAdapter('Y', 'N'));
    constructor() {
        super('custom_company'); // table name in the database
    }
}()

const tRecord = new class TRecord extends Table<DBConnection, 'TRecord'> {
    id = this.primaryKey('id', 'uuid');
    title = this.column('title', 'string');
    constructor() {
        super('record'); // table name in the database
    }
}()

const connection = new DBConnection(new MockQueryRunner(() => { }))
let options: any = {}

/******************** 
 * Generated code
 */

// Generated code here

/******************** 
 * Noops to make the compiler happy
 */
class Database {
    constructor(_1: any, _2?: any) {}
    function(_1: any, _2: any) {}
}
void Database

// node:sql
type SQLInputValue = any
type SQLOutputValue = any
class DatabaseSync {
    constructor(_1: any, _2?: any) {}
    function(_1: any, _2: any) {}
}

void DatabaseSync
void function(
    _siv: SQLInputValue,
    _sov: SQLOutputValue
) {}

void tCompany
void tCustomer
void tCustomCompany
void tRecord
void connection
void options

void PrismaBetterSqlite3
void PrismaClient
void PrismaQueryRunner

void BetterSqlite3QueryRunner
void Sqlite3QueryRunner
void BunSqliteQueryRunner
void BunSqlSqliteQueryRunner
void NodeSqliteQueryRunner
void SQL
void sync
void SynchronousPromise
void sqlite3InitModule
void Sqlite3WasmOO1QueryRunner

void uuidParse
void uuidStringify
void uuidv7

void function(
    _sdtf: SqliteDateTimeFormat,
    _sdtft: SqliteDateTimeFormatType
) {}