import type { AnyTableOrView } from './ITableOrView.js'
import type { ToSql } from '../sqlBuilders/SqlBuilder.js'
import type { AnyValueSource, __ValueSourcePrivate } from '../expressions/values.js'
import type { autogeneratedPrimaryKeyValue, hasDefaultValue, primaryKeyValue, type, writable } from './symbols.js'
import { isColumnObject } from './symbols.js'

/*
 * Column markers — the model, so this doesn't mislead us again.
 *
 * A column is, first, an `AnyValueSource` (an expression producing a value).
 * On top of that these markers answer TWO independent questions:
 *
 *   1. IDENTITY — `DBColumn` (`[type]: 'column'`): "is this a real, named
 *      column of a data source?" A computed/derived value source (declared with
 *      `computedColumn(...)` / `virtualColumnFromFragment(...)`) is NOT a
 *      `DBColumn` — it stays a bare value source.
 *
 *   2. WRITABILITY — `WritableDBColumn` (adds `[writable]: true`): "does the
 *      user supply a value for this column?" i.e. it takes part in a write
 *      position: an INSERT/UPDATE `SET`, or a `VALUES` row.
 *
 * IMPORTANT — "writable" means "receives a value", NOT "its source can be
 * mutated". Whether you can `insertInto` / `update` / `deleteFrom` a source is
 * gated separately, by the SOURCE type (`ITable`), never by these column
 * markers. So a `Values` view's columns ARE writable (you provide their value
 * in the rows passed to `Values.create`) even though you can never run an
 * UPDATE against a `Values` view.
 *
 * Who carries what (see `Table.ts` / `View.ts` / `Values.ts`):
 *   - Table  `column`/`optionalColumn`/`primaryKey`/... → writable (`Column`,
 *     `PrimaryKeyColumn`, ...). Runtime: `__writable = true`.
 *   - Values `column`/`optionalColumn` → writable (`Column`). Runtime:
 *     `__writable = true` — a `Values` view behaves like a table for writing,
 *     only its write mechanism (constant rows) differs.
 *   - View / WITH columns → read-only: intentionally left UNMARKED (a bare value
 *     source). Runtime: `__writable = false`. The design marks only what is
 *     writable, so a read-only column is modelled as "not a writable column"
 *     rather than as a distinct read-only-column type. `DBColumn` on its own is
 *     therefore rarely used as a type discriminant; it mainly backs the runtime
 *     `isColumn(...)` guard and internal column sets.
 *   - `computedColumn` / `virtualColumnFromFragment` → a bare value source
 *     (neither identity nor writability marker).
 *
 * Runtime mirror: `__ColumnPrivate` (below) carries `__writable` / `__isComputed`
 * / `__hasDefault` / `__isPrimaryKey` — the runtime twin of these type brands.
 * `__writable` is the mirror of `WritableDBColumn`; the `extras/utils` writable
 * extractors filter on it, so it MUST agree with the type marker on every source
 * kind (table, values, view, with) — keep the `__as*Column()` wiring in
 * `Table`/`View`/`Values` in sync with the marker each method's type declares.
 */

// Represents any column in the database (identity marker; see the note above)
export interface DBColumn extends AnyValueSource {
    [type]: 'column'
}

// A column the user supplies a value for (INSERT/UPDATE set or VALUES row).
// NOT the same as "its source can be mutated" — see the note above.
export interface WritableDBColumn extends DBColumn {
    [writable]: true
}

export interface WritableDBPrimaryKeyColumn extends WritableDBColumn {
    [primaryKeyValue]: true
}

export interface WritableDBColumnWithDefaultValue extends WritableDBColumn {
    [hasDefaultValue]: true
}

export interface WritableDBColumnWithoutDefaultValue extends WritableDBColumn {
    [hasDefaultValue]: false
}

export interface WritableDBPrimaryKeyColumnWithDefaultValue extends WritableDBColumnWithDefaultValue, WritableDBPrimaryKeyColumn {
    [primaryKeyValue]: true
    [autogeneratedPrimaryKeyValue]: true
}

export interface WritableDBPrimaryKeyColumnWithoutDefaultValue extends WritableDBColumnWithoutDefaultValue, WritableDBPrimaryKeyColumn {
    [primaryKeyValue]: true
    [autogeneratedPrimaryKeyValue]: true
}

export interface Column extends WritableDBColumnWithoutDefaultValue {
}

export interface ColumnWithDefaultValue extends WritableDBColumnWithDefaultValue {
}

export interface PrimaryKeyColumn extends WritableDBPrimaryKeyColumnWithoutDefaultValue {
    [primaryKeyValue]: true
}

export interface PrimaryKeyAutogeneratedColumn extends WritableDBPrimaryKeyColumnWithDefaultValue {
    [primaryKeyValue]: true
    [autogeneratedPrimaryKeyValue]: true
}

export interface __ColumnPrivate extends __ValueSourcePrivate {
    [isColumnObject]: true
    __name: string
    __tableOrView: AnyTableOrView
    __hasDefault: boolean
    __isPrimaryKey: boolean
    __isAutogeneratedPrimaryKey: boolean
    __isComputed: boolean
    __sequenceName?: string | undefined
    __writable: boolean
}

export function isColumn(value: any): value is DBColumn {
    if (value === undefined || value === null) {
        return false
    }
    if (typeof value === 'object') {
        return !!value[isColumnObject]
    }
    return false
}

export function __getColumnPrivate(column: DBColumn): __ColumnPrivate {
    return column as any
}

export function __getColumnOfObject(obj: AnyTableOrView | { [property: string] : DBColumn}, column: string): (DBColumn & ToSql) | undefined {
    const result = (obj as any)[column]
    if (!result) {
        return undefined
    }
    if (typeof result !== 'object') {
        return undefined
    }
    if (result[isColumnObject]) {
        return result as any
    } else {
        return undefined
    }
}