-- Schema for the shared "project management" domain, sqlite dialect.
-- Idempotent: tests run setup against a fresh database each variant, but
-- having DROP IF EXISTS lets you re-apply by hand for debugging.

DROP VIEW IF EXISTS release_overview;
DROP VIEW IF EXISTS project_overview;
DROP TABLE IF EXISTS project_release;
DROP TABLE IF EXISTS webhook_event;
DROP TABLE IF EXISTS calendar_year;
DROP TABLE IF EXISTS issue_worklog;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS issue;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS organization;

CREATE TABLE organization (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    plan VARCHAR(32) NOT NULL,
    -- `verified` flag stored as Y/N so the connection.ts mapping can
    -- exercise CustomBooleanTypeAdapter on a real seed column.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    -- `verified` stored as Y/N — same CustomBooleanTypeAdapter mapping
    -- as organization.verified so cross-table comparisons need no remap.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organization(id),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    -- `published` flag stored as t/f, a deliberately different
    -- CustomBooleanTypeAdapter mapping than organization/app_user.verified
    -- so column-vs-column comparisons hit the remap-with-case branch.
    published VARCHAR(1) NOT NULL DEFAULT 'f',
    archived_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, slug)
);

CREATE TABLE issue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES project(id),
    number INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT,
    status VARCHAR(32) NOT NULL,
    priority INTEGER NOT NULL,
    assignee_id INTEGER REFERENCES app_user(id),
    parent_id INTEGER REFERENCES issue(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- New-type columns exercising AbstractConnection value marshalling:
    -- bigint (view_count), double (estimated_hours), uuid (external_ref).
    view_count INTEGER NOT NULL DEFAULT 0,
    estimated_hours REAL,
    external_ref TEXT,
    UNIQUE (project_id, number)
);

-- A lookup table whose primary key is CALLER-PROVIDED (an ISO 3166-1
-- alpha-2 code), not autogenerated. Exercises `primaryKey(...)` /
-- ProvidedIdColumnKeys (required on insert, surfaced by the
-- extractProvidedId* helpers) on a meaningful domain entity.
CREATE TABLE country (
    code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    region VARCHAR(32) NOT NULL
);

-- Time tracking: a worklog entry recording effort spent on an issue.
-- Carries the date-only / time-only / nullable-bigint / nullable-boolean
-- (no adapter) / optional-with-default / plain-enum column kinds the rest
-- of the domain doesn't expose.
CREATE TABLE issue_worklog (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    issue_id INTEGER NOT NULL REFERENCES issue(id) ON DELETE CASCADE,
    work_date DATE NOT NULL,
    started_at TIME,
    -- nullable AND defaulted: a running timer leaves minutes NULL; the
    -- DEFAULT applies when the column is omitted on insert.
    minutes INTEGER DEFAULT 0,
    duration_ms INTEGER,
    -- plain nullable boolean (0/1) — no CustomBooleanTypeAdapter, unlike
    -- organization/project.verified/published which store Y/N - t/f.
    billable INTEGER,
    -- nullable custom-boolean stored as A/R (CustomBooleanTypeAdapter).
    approved VARCHAR(1),
    -- billed amount per worklog (customDouble 'Money') and an `invoiced`
    -- flag stored as int 1/0 (numeric CustomBooleanTypeAdapter overload).
    billed_amount REAL NOT NULL DEFAULT 0,
    invoiced INTEGER NOT NULL DEFAULT 0,
    cost_cents INTEGER NOT NULL DEFAULT 0,
    activity VARCHAR(16) NOT NULL,
    -- Nullable DB-computed column (declared optionalComputedColumn).
    activity_label VARCHAR(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN UPPER(activity) ELSE NULL END) STORED
);

-- Bigint autogenerated PK + enum-defaulted column.
CREATE TABLE webhook_event (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    issue_id INTEGER NOT NULL REFERENCES issue(id) ON DELETE CASCADE,
    event_type VARCHAR(16) NOT NULL DEFAULT 'created'
);

-- Int caller-provided PK.
CREATE TABLE calendar_year (
    year_value INTEGER PRIMARY KEY,
    year_label VARCHAR(64) NOT NULL
);

-- A published release of a project. Carries branded custom types
-- (semantic version, channel, signing key) and custom date/time columns,
-- a genuinely DB-computed column (`notes`) and is the table side of the
-- computed/virtual-vs-writable split.
CREATE TABLE project_release (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL REFERENCES project(id),
    version VARCHAR(32) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    signing_key TEXT,
    released_on DATE NOT NULL,
    cutoff_time TIME NOT NULL,
    signed_off_at DATETIME,
    -- DB-computed column: never written by the app (declared
    -- `computedColumn` in connection.ts, so it is excluded from the
    -- insert/update shape).
    notes TEXT GENERATED ALWAYS AS ('release-' || version) STORED,
    UNIQUE (project_id, version)
);

-- A class-based SQL view exercised by `view.basic.test.ts`. A plain
-- join of project + organization (no aggregation, no casts), portable
-- across every dialect.
CREATE VIEW project_overview AS
SELECT p.id AS id,
       p.organization_id AS organization_id,
       p.name AS name,
       p.archived_at AS archived_at,
       o.name AS organization_name,
       o.plan AS organization_plan
FROM project p
INNER JOIN organization o ON o.id = p.organization_id;

-- A second class-based view (`vReleaseOverview`) surfacing the branded
-- custom / custom-date-time columns of project_release on the View source
-- (so the per-type ValueSource dispatch is covered View-side, not only
-- Table-side).
CREATE VIEW release_overview AS
SELECT r.id AS id,
       r.project_id AS project_id,
       r.version AS version,
       r.released_on AS released_on,
       r.signed_off_at AS signed_off_at,
       p.name AS project_name
FROM project_release r
INNER JOIN project p ON p.id = r.project_id;

-- Stored procedures and functions exercised by
-- `exec.procedure-function.test.ts` on every other dialect. SQLite
-- has no SQL-side DDL for either, so the corresponding cell keeps
-- every test commented out (see test/db/sqlite/<connector>/exec.procedure-function.test.ts).
-- The DDL stubs below are kept for parity with the other dialect
-- schemas — i.e. they describe what would live here if SQLite ever
-- gained `CREATE PROCEDURE` / `CREATE FUNCTION`. Statement
-- terminators are intentionally omitted because the harness'
-- `splitStatements` regex doesn't respect SQL comments and would
-- hand SQLite a comment-only fragment that the engine rejects with
-- "no valid SQL statement"
--
--   CREATE PROCEDURE refresh_stats() ...
--   CREATE PROCEDURE archive_project(p_id INTEGER, p_reason TEXT)
--       UPDATE project
--          SET archived_at = CURRENT_TIMESTAMP,
--              name        = name || ' [archived: ' || p_reason || ']'
--        WHERE id = p_id
--   CREATE FUNCTION count_open_issues(p_id INTEGER) RETURNS INTEGER
--       SELECT COUNT(*) FROM issue WHERE project_id = p_id AND status = 'open'
--   CREATE FUNCTION project_name(p_id INTEGER) RETURNS TEXT
--       SELECT name FROM project WHERE id = p_id
