// Behavioral coverage of `connection.insertInto(t).defaultValues()`,
// which triggers `_buildInsertDefaultValues` in each SqlBuilder. Each
// dialect emits its own form, pinned per cell by the snapshot below.

import { afterAll, beforeAll, beforeEach, describe, expect, test } from '../../../../lib/testRunner.js'
import { Table } from '../../../../../src/Table.js'
import { DBConnection } from '../../domain/connection.js'
import { ctx } from './setup.js'

// Local-only table whose only column is an autogenerated PK. On MySQL the
// id of a `.defaultValues()` insert can't be returned through the typed
// surface (see the NOT-APPLICABLE block below), so the DEFAULT VALUES test
// is skipped here; the fixture is kept for symmetry with the cells where
// the test runs.
class TDefaultsOnly extends Table<DBConnection, 'TDefaultsOnly'> {
    id = this.autogeneratedPrimaryKey('id', 'int')
    constructor() { super('defaults_only_table_only_for_sql_test') }
}
const tDefaultsOnly = new TDefaultsOnly()
// Referenced only from the commented-out NOT-APPLICABLE block below.
void test; void expect; void tDefaultsOnly

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    // NOT-APPLICABLE: on MySQL the id of a `.defaultValues()` insert can't be returned through the typed surface. `.returning(...)`/`.returningOneColumn(...)` are `never` (MySQL has no RETURNING clause), and `.returningLastInsertedId()` is `never` too: `.defaultValues()` reuses the post-on-conflict returning surface, whose `returningLastInsertedId` (`OnConflictReturningLastInsertedIdType`) excludes MySQL on purpose — `LAST_INSERT_ID()` after `ON DUPLICATE KEY UPDATE` is ambiguous.
    /*
    test('insert default values', async () => {
        ctx.mockNext(99)
        let id: number | undefined
        let thrownError: unknown
        try {
            id = await ctx.conn.insertInto(tDefaultsOnly)
                .defaultValues()
                .returningLastInsertedId()
                .executeInsert()
        } catch (e) {
            // The table is absent from the schema, so the real INSERT fails
            // referencing the missing relation.
            thrownError = e
        }
        expect(ctx.lastSql).toMatchInlineSnapshot(`"insert into defaults_only_table_only_for_sql_test () values ()"`)
        expect(ctx.lastParams).toMatchInlineSnapshot(`[]`)
        if (ctx.realDbEnabled) {
            expect((thrownError as Error).message).toMatch(/doesn't exist|defaults_only_table_only_for_sql_test/)
        } else {
            expect(id).toBe(99)
        }
    })
    */

    // NOT-APPLICABLE: MySQL has no RETURNING clause, so `.defaultValues().returning(...)` types as `never` (like the disabled `insert default values` test above).
    /*
    test('default values returning an object', async () => {
        // `insert into <t> default values returning <cols>` — the object-projection
        // returning path on a DEFAULT VALUES insert (distinct from the
        // returningLastInsertedId path above).
        ctx.mockNext([{ amount: 100 }])
        await ctx.withRollback(async () => {
            const rows = await ctx.conn.insertInto(tLedgerEntry)
                .defaultValues()
                .returning({ amount: tLedgerEntry.amount })
                .executeInsertMany()
            expect(ctx.lastSql).toMatchInlineSnapshot()
            expect(ctx.lastParams).toMatchInlineSnapshot()
            assertType<Exact<typeof rows, Array<{ amount: number }>>>()
            expect(rows).toEqual([{ amount: 10 }])
        })
    })
    */

    // NOT-APPLICABLE: MySQL has no RETURNING clause, so `.defaultValues().returningOneColumn(...)` types as `never` (like the disabled `insert default values` test above).
    /*
    test('default values returning one column', async () => {
        // `insert into <t> default values returning <col>` — the single-column
        // returning path on a DEFAULT VALUES insert; the result is a bare array of
        // the column's type.
        ctx.mockNext([100])
        await ctx.withRollback(async () => {
            const rows = await ctx.conn.insertInto(tLedgerEntry)
                .defaultValues()
                .returningOneColumn(tLedgerEntry.amount)
                .executeInsertMany()
            expect(ctx.lastSql).toMatchInlineSnapshot()
            expect(ctx.lastParams).toMatchInlineSnapshot()
            assertType<Exact<typeof rows, number[]>>()
            expect(rows).toEqual([10])
        })
    })
    */

    // NOT-APPLICABLE: MySQL has no RETURNING clause, so `.defaultValues().returningLastInsertedId()` types as `never` (like the disabled `insert default values` test above).
    /*
    test('default values returning last inserted id', async () => {
        // `defaultValues().returningLastInsertedId()` on the seeded ledger_entry (every
        // column defaulted): the DEFAULT VALUES insert returns the autogenerated
        // entry_no. entry_no carries plusOffsetAdapter (read +1000), so the returned id
        // surfaces offset.
        ctx.mockNext(1)
        await ctx.withRollback(async () => {
            const id = await ctx.conn.insertInto(tLedgerEntry)
                .defaultValues()
                .returningLastInsertedId()
                .executeInsert()
            expect(ctx.lastSql).toMatchInlineSnapshot()
            expect(ctx.lastParams).toMatchInlineSnapshot()
            assertType<Exact<typeof id, number>>()
            if (ctx.realDbEnabled) {
                // The engine assigns entry_no from its sequence; plusOffsetAdapter
                // shifts the read by +1000, so the returned id clears 1000. The exact
                // value is not pinned (the sequence advances across runs).
                expect(typeof id).toBe('number')
                expect(id).toBeGreaterThan(1000)
            } else {
                // Mock raw entry_no 1 → read +1000 = 1001.
                expect(id).toBe(1001)
            }
        })
    })
    */
})
