// PostgreSQL-only coverage of a USER-defined TypeAdapter that overrides the
// optional `transformPlaceholder` hook to rewrite the bound placeholder.
// The built-in `ForceTypeCast` only flips the force-cast flag and defers to
// the default placeholder; this exercises a user adapter that rewrites the
// placeholder itself (the `transformPlaceholder?` hook is otherwise only
// `void`-stubbed in the docs). The `::varchar(64)` cast is PostgreSQL syntax,
// so this file is postgres-specific — its name embeds `postgres`, which
// excludes it from the cross-dialect symmetry audit.

import { afterAll, beforeAll, beforeEach, describe, expect, test } from '../../../../lib/testRunner.js'
import { assertType, type Exact } from '../../../../lib/assertType.js'
import { CustomBooleanTypeAdapter, type DefaultTypeAdapter, type TypeAdapter } from '../../../../../src/TypeAdapter.js'
import { Table } from '../../../../../src/Table.js'
import { DBConnection } from '../../domain/connection.js'
import { ctx } from './setup.js'

// A CustomBooleanTypeAdapter subclass that ALSO defines `transformPlaceholder`.
// When a column carrying this adapter is re-projected through a CTE,
// `createColumnsFrom` wraps it in a `ProxyTypeAdapter` (so the outer reference
// is not re-treated as a custom boolean). The proxy must FORWARD
// `transformPlaceholder` to this adapter — the regression test below pins that.
class CastingBooleanAdapter extends CustomBooleanTypeAdapter {
    constructor() { super('Y', 'N') }
    transformPlaceholder(placeholder: string, type: string, forceTypeCast: boolean, valueSentToDB: unknown, next: DefaultTypeAdapter): string {
        if (type === 'boolean') {
            return placeholder + '::boolean'
        }
        return next.transformPlaceholder(placeholder, type, forceTypeCast, valueSentToDB)
    }
}
const castingBool = new CastingBooleanAdapter()

// `organization.verified` re-mapped with the casting custom-boolean adapter.
const tOrgCastingBool = new class TOrgCastingBool extends Table<DBConnection, 'TOrgCastingBool'> {
    id       = this.autogeneratedPrimaryKey('id', 'int')
    name     = this.column('name', 'string')
    verified = this.column('verified', 'boolean', castingBool)
    constructor() { super('organization') }
}()

// A user adapter whose `transformPlaceholder` emits an explicit PostgreSQL cast
// for the type it handles and DELEGATES to `next` for every other type — the
// idiomatic shape documented in docs/configuration/column-types.md. It is
// observably different from both the default (no cast) and `ForceTypeCast`
// (which only sets forceTypeCast = true and defers to the default placeholder).
const castVarchar64: TypeAdapter = {
    transformValueFromDB(value, type, next) { return next.transformValueFromDB(value, type) },
    transformValueToDB(value, type, next) { return next.transformValueToDB(value, type) },
    transformPlaceholder(placeholder, type, forceTypeCast, valueSentToDB, next) {
        if (type === 'string') {
            return placeholder + '::varchar(64)'
        }
        return next.transformPlaceholder(placeholder, type, forceTypeCast, valueSentToDB)
    },
}

// Re-maps the shared `project` table (same columns/rows as `tProject`), with
// `name` backed by the user placeholder adapter. Using the same physical table
// keeps real-DB execution trivial; the only observable change is the bound
// placeholder syntax for the `name` column.
const tProjectCustomPlaceholder = new class TProjectCustomPlaceholder extends Table<DBConnection, 'TProjectCustomPlaceholder'> {
    id   = this.column('id', 'int')
    name = this.column('name', 'string', castVarchar64)
    constructor() { super('project') }
}()

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    test('user-type-adapter-transform-placeholder-emits-custom-cast', async () => {
        // The user adapter on `name` rewrites every bound placeholder for that
        // column to `$N::varchar(64)` (the default PG placeholder is a bare
        // `$N`). Project 1 is 'Marketing site', so the cast still matches and
        // the row comes back.
        ctx.mockNext([{ id: 1 }])
        const rows = await ctx.conn.selectFrom(tProjectCustomPlaceholder)
            .where(tProjectCustomPlaceholder.name.equals('Marketing site'))
            .select({ id: tProjectCustomPlaceholder.id })
            .executeSelectMany()
        expect(ctx.lastSql).toMatchInlineSnapshot(`"select id as id from project where name = $1::varchar(64)"`)
        expect(ctx.lastParams).toMatchInlineSnapshot(`
          [
            "Marketing site",
          ]
        `)
        expect(rows).toEqual([{ id: 1 }])
    })

    test('proxy-type-adapter-forwards-transform-placeholder-through-cte', async () => {
        // Regression for ProxyTypeAdapter: a CustomBooleanTypeAdapter subclass
        // that defines `transformPlaceholder`, re-projected through a CTE, is
        // wrapped in a ProxyTypeAdapter. The proxy must FORWARD
        // transformPlaceholder to the wrapped adapter, so the placeholder bound
        // for the filtered value carries the custom `::boolean` cast. Before the
        // fix the proxy dropped the hook and the cast was lost (`$1` instead of
        // `$1::boolean`). organization 1 is verified ('Y'); organization 2 is not.
        const connection = ctx.conn
        const castingOrgs = connection.selectFrom(tOrgCastingBool)
            .select({
                id:       tOrgCastingBool.id,
                name:     tOrgCastingBool.name,
                verified: tOrgCastingBool.verified,
            })
            .forUseInQueryAs('castingOrgs')

        const expected = [{ id: 1, name: 'Acme Corp' }]
        ctx.mockNext(expected)
        const rows = await connection.selectFrom(castingOrgs)
            .where(castingOrgs.verified.equals(true))
            .select({ id: castingOrgs.id, name: castingOrgs.name })
            .orderBy('id')
            .executeSelectMany()

        expect(ctx.lastSql).toMatchInlineSnapshot(`"with castingOrgs as (select id as id, name as name, (verified = 'Y') as verified from organization) select id as id, name as name from castingOrgs where verified = $1::boolean order by id"`)
        expect(ctx.lastParams).toMatchInlineSnapshot(`
          [
            true,
          ]
        `)
        assertType<Exact<typeof rows, Array<{ id: number; name: string }>>>()
        expect(rows).toEqual(expected)
    })
})
