// `tTable.oldValues()` exposes the row state BEFORE the UPDATE is applied,
// so a single statement can `RETURNING { old: oldX, new: newX }` for
// audit / event-sourcing flows.
//
// API surface: [src/Table.ts:56-68](../../../../../src/Table.ts#L56-L68) —
// typed on `sqlServer` and `mariaDB` unconditionally; on `postgreSql`
// only when the table has an autogenerated primary key; typed `never`
// on `mySql`, `sqlite`, and `oracle`.
//
// Build path: [src/sqlBuilders/AbstractSqlBuilder.ts:2195-2263](../../../../../src/sqlBuilders/AbstractSqlBuilder.ts#L2195-L2263) —
// `_buildOldValuesForUpdate` emits a synthetic FROM-subquery that
// pre-projects the target table aliased as `_old_` so the RETURNING
// clause can refer to its columns alongside the freshly-updated row.
// PostgreSQL emits this as
// `update t set ... from (select _old_.*, ... from t _old_ where ...) _old_ where t.id = _old_.id returning ...`;
// SQL Server uses an OUTPUT-based variant. The 30 lines of emission
// are entirely uncovered by the matrix as of Wave 73.
//
// Active in postgres + sqlserver + mariadb cells; commented out in
// sqlite/mysql/oracle (typed `never`).

import { afterAll, beforeAll, beforeEach, describe, expect, test } from '../../../../lib/testRunner.js'
import { assertType, type Exact } from '../../../../lib/assertType.js'
import { tProject } from '../../domain/connection.js'
import { ctx } from './setup.js'

describe(ctx.label, () => {
    beforeAll(() => ctx.up(), ctx.timeoutMs)
    afterAll(() => ctx.down(), ctx.timeoutMs)
    beforeEach(() => { ctx.reset() })

    test('returning-old-and-new-single-column-via-oldValues', async () => {
        // Update project 1's name; return both the previous and the
        // new name in one round-trip. Seed: project 1 is 'Marketing
        // site'. After the update its name is 'Mktg site v2'.
        ctx.mockNext({ oldName: 'Marketing site', newName: 'Mktg site v2' })

        await ctx.withRollback(async () => {
            const oldProject = tProject.oldValues()
            const row = await ctx.conn.update(tProject)
                .set({ name: 'Mktg site v2' })
                .where(tProject.id.equals(1))
                .returning({
                    oldName: oldProject.name,
                    newName: tProject.name,
                })
                .executeUpdateOne()

            expect(ctx.lastSql).toMatchInlineSnapshot(`"update project as _new_ set name = $1 from (select _old_.* from project as _old_ where _old_.id = $2 for no key update of _old_) as _old_ where _new_.id = _old_.id returning _old_.name as "oldName", _new_.name as "newName""`)
            expect(ctx.lastParams).toMatchInlineSnapshot(`
              [
                "Mktg site v2",
                1,
              ]
            `)
            assertType<Exact<typeof row, { oldName: string; newName: string }>>()
            if (!ctx.realDbEnabled) {
                expect(row).toEqual({ oldName: 'Marketing site', newName: 'Mktg site v2' })
            } else {
                expect(row.oldName).toBe('Marketing site')
                expect(row.newName).toBe('Mktg site v2')
            }
        })
    })

    test('returning-old-and-new-two-columns-via-oldValues', async () => {
        // Two-column audit projection: pre/post name and pre/post
        // slug. The emission must reference `_old_.name`, `_old_.slug`
        // inside the synthesised FROM-subquery and the matching live
        // columns on the target table.
        ctx.mockNext({
            id: 2,
            oldName: 'Internal tools',
            newName: 'Internal apps',
            oldSlug: 'tools',
            newSlug: 'apps',
        })

        await ctx.withRollback(async () => {
            const oldProject = tProject.oldValues()
            const row = await ctx.conn.update(tProject)
                .set({ name: 'Internal apps', slug: 'apps' })
                .where(tProject.id.equals(2))
                .returning({
                    id:      tProject.id,
                    oldName: oldProject.name,
                    newName: tProject.name,
                    oldSlug: oldProject.slug,
                    newSlug: tProject.slug,
                })
                .executeUpdateOne()

            expect(ctx.lastSql).toMatchInlineSnapshot(`"update project as _new_ set name = $1, slug = $2 from (select _old_.* from project as _old_ where _old_.id = $3 for no key update of _old_) as _old_ where _new_.id = _old_.id returning _new_.id as id, _old_.name as "oldName", _new_.name as "newName", _old_.slug as "oldSlug", _new_.slug as "newSlug""`)
            expect(ctx.lastParams).toMatchInlineSnapshot(`
              [
                "Internal apps",
                "apps",
                2,
              ]
            `)
            assertType<Exact<typeof row, {
                id: number
                oldName: string
                newName: string
                oldSlug: string
                newSlug: string
            }>>()
            if (!ctx.realDbEnabled) {
                expect(row).toEqual({
                    id: 2,
                    oldName: 'Internal tools',
                    newName: 'Internal apps',
                    oldSlug: 'tools',
                    newSlug: 'apps',
                })
            } else {
                expect(row.id).toBe(2)
                expect(row.oldName).toBe('Internal tools')
                expect(row.newName).toBe('Internal apps')
                expect(row.oldSlug).toBe('tools')
                expect(row.newSlug).toBe('apps')
            }
        })
    })
})
