// Aggregated public API for cross-database use. Database-specific entry points
// (connections/*, queryRunners/*) and IDEncrypter remain only at their subpath.

export type { Connection, TransactionIsolationLevel } from './Connection.js'

export { Table } from './Table.js'

export { View } from './View.js'

export { CustomBooleanTypeAdapter, ForceTypeCast } from './TypeAdapter.js'
export type { DefaultTypeAdapter, TypeAdapter } from './TypeAdapter.js'

export { Values } from './Values.js'
export type { OpaqueValues } from './Values.js'

export { TsSqlError, TsSqlQueryExecutionError, TsSqlProcessingError, QueryExecutionSource } from './TsSqlError.js'
export type { TsSqlDatabaseErrorCode, TsSqlDatabaseErrorNumber, TsSqlInternalErrorReason, TsSqlErrorReason } from './TsSqlError.js'

export {
    dynamicPick,
    dynamicPickPaths,
    expandTypeFromDynamicPickPaths,
    expandTypeProjectedAsNullableFromDynamicPickPaths
} from './dynamicCondition.js'
export type {
    DynamicCondition,
    Pickable,
    DynamicPick,
    DynamicPickPaths,
    PickValuesPath,
    PickValuesPathWitAllProperties,
    PickValuesPathProjectedAsNullable,
    PickValuesPathWitAllPropertiesProjectedAsNullable
} from './dynamicCondition.js'

export { fromRef } from './extras/types.js'
export type {
    SelectedRow,
    SelectedValues,
    SelectedRowProjectedAsNullable,
    SelectedValuesProjectedAsNullable,
    InsertableRow,
    InsertableValues,
    UpdatableOnInsertConflictRow,
    UpdatableOnInsertConflictValues,
    InsertableRowShapedAs,
    InsertableValuesShapedAs,
    UpdatableOnInsertConflictRowShapedAs,
    UpdatableOnInsertConflictValuesShapedAs,
    UpdatableRow,
    UpdatableValues,
    UpdatableRowShapedAs,
    UpdatableValuesShapedAs,
    WritableShapeFor,
    ColumnKeys,
    WritableColumnKeys,
    IdColumnKeys,
    AutogeneratedIdColumnKeys,
    ProvidedIdColumnKeys,
    TableOrViewOf,
    TableOrViewLeftJoinOf
} from './extras/types.js'

export {
    extractColumnsFrom,
    extractWritableColumnsFrom,
    extractIdColumnsFrom,
    extractAutogeneratedIdColumnsFrom,
    extractProvidedIdColumnsFrom,
    extractColumnNamesFrom,
    extractWritableColumnNamesFrom,
    extractIdColumnNamesFrom,
    extractAutogeneratedIdColumnNamesFrom,
    extractProvidedIdColumnNamesFrom,
    extractWritableShapeFrom
} from './extras/utils.js'
