// Compile-time negative tests for INSERT-shaped APIs on the mariadb dialect.
// See `select.test.ts` for the rationale and conventions.

import { test, expect } from '../../../lib/testRunner.js'
import type { DBConnection } from '../domain/connection.js'
import { tOrganization, tIssue, tProject } from '../domain/connection.js'

// `connection` is type-only — the function below is checked by tsc but
// never invoked at runtime, so we don't need a real instance and don't
// open any driver-level resource just to make the file load.
declare const connection: DBConnection

function _typeNegatives() {
    // Rule: optional columns (here `body`) on an INSERT can be omitted, but
    // required columns must be present. The `status` field below is
    // required and missing, which must not compile.
    // @ts-expect-error required column `status` is missing from the INSERT
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        priority:  1,
    })

    // Rule: column value types must match. `priority` is `int`; passing a
    // string must not compile. tsgo reports the error at the offending
    // property, not at the values() call site, so the directive sits on
    // the property — see test/WRITING_TESTS.md for why this asymmetry exists.
    void connection.insertInto(tIssue).values({
        projectId: 1,
        number:    1,
        title:     'x',
        status:    'open',
        // @ts-expect-error priority is int, not string
        priority:  'high',
    })

    // Rule: cannot insert columns that don't exist on the table. tsgo
    // reports the excess-property error at the property line itself —
    // directive placement matches.
    void connection.insertInto(tProject).values({
        organizationId:    1,
        name:              'x',
        slug:              'x',
        // @ts-expect-error 'nonExistentColumn' is not a column of tProject
        nonExistentColumn: 'x',
    })

    // Note: autogeneratedPrimaryKey('id', 'int') still accepts an
    // explicit id in insert values — the lib treats autogenerated as
    // "has a default" rather than "cannot be set". The schema-level
    // override holds at the SQL layer; no compile-time guard for now.

    // Rule: MariaDB's `ON DUPLICATE KEY UPDATE` has no inference target
    // (no column list, no `ON CONSTRAINT`), so `.onConflictOn(...)` is
    // not exposed on MariaDBConnection; the targeted
    // `.onConflictOn(col).doUpdateSet({...})` form must not compile.
    void connection.insertInto(tProject)
        .values({ organizationId: 1, slug: 'x', name: 'y' })
        // @ts-expect-error onConflictOn is not typed on MariaDBConnection
        .onConflictOn(tProject.organizationId, tProject.slug)

    // Rule: MariaDB's `ON DUPLICATE KEY UPDATE` has no WHERE clause, so
    // `.where(cond)` chained after `.onConflictDoUpdateSet({...})` must
    // not compile. Runtime silently drops the WHERE — the typed surface
    // is what stops users from reaching the dropped path.
    void connection.insertInto(tProject)
        .values({ organizationId: 1, slug: 'x', name: 'y' })
        .onConflictDoUpdateSet({ name: 'z' })
        // @ts-expect-error .where after .onConflictDoUpdateSet is not typed on MariaDBConnection
        .where(tProject.name.notEquals('z'))

    // Rule: after a shaped static one-shot `onConflictDoUpdateSet({renamed})` the
    // returned node stays shaped — a chained `.set(...)` and the `*When` arms accept
    // only the renamed shape keys, never the real columns.
    void connection.insertInto(tProject)
        .shapedAs({ orgId: 'organizationId', projectName: 'name', projectSlug: 'slug' })
        .set({ orgId: 1, projectName: 'a', projectSlug: 'b' })
        .onConflictDoUpdateSet({ projectName: 'one-shot' })
        // @ts-expect-error real column 'name' is not a shaped key on the chained on-conflict set
        .set({ name: 'chained' })
    void connection.insertInto(tProject)
        .shapedAs({ orgId: 'organizationId', projectName: 'name', projectSlug: 'slug' })
        .set({ orgId: 1, projectName: 'a', projectSlug: 'b' })
        .onConflictDoUpdateSet({ projectName: 'one-shot' })
        // @ts-expect-error real column 'name' is not a shaped key on the on-conflict setWhen
        .setWhen(true, { name: 'when' })

    // Rule: the conditional `disallowIfNoValueWhen(when, …)` must NOT clear a
    // missing-key obligation. `when` is a runtime value, so a column it names
    // is not statically guaranteed to have a value; the `*When` arm keeps the
    // named column in the still-missing set (like the whole `set*When` family,
    // which never narrows toward executability). Its unconditional sibling
    // `disallowIfNoValue(…)` may narrow because it throws eagerly when the
    // named column has no value.
    // Control: unconditional disallowIfNoValue narrows `projectId` out of the
    // missing set, so the later `.set(rest)` reaches an executable insert.
    void connection.insertInto(tIssue).dynamicSet()
        .disallowIfNoValue('projectId must have a value', 'projectId')
        .set({ number: 1, title: 'x', status: 'open', priority: 1 })
        .executeInsert()
    // Guard: the `*When` arm does not narrow, so `projectId` is still missing
    // after the other required columns are set and the insert is not executable.
    void connection.insertInto(tIssue).dynamicSet()
        .disallowIfNoValueWhen(false, 'projectId must have a value', 'projectId')
        .set({ number: 1, title: 'x', status: 'open', priority: 1 })
        // @ts-expect-error disallowIfNoValueWhen must not make a still-incomplete insert executable
        .executeInsert()

    // Rule: `executeInsertOne` is not exposed on the optional-returning path.
    // `onConflictDoNothing().returning(...)` yields an ExecutableInsertReturningOptional
    // — an ON CONFLICT DO NOTHING may insert zero rows, so "exactly one row" is unsound;
    // only executeInsertNoneOrOne / executeInsertMany are available. A plain
    // `.returning(...)` (required) does expose executeInsertOne.
    // Control: the NoneOrOne arm remains available on the optional path.
    void connection.insertInto(tOrganization).values({ name: 'x', plan: 'free' })
        .onConflictDoNothing().returning({ id: tOrganization.id }).executeInsertNoneOrOne()
    void connection.insertInto(tOrganization).values({ name: 'x', plan: 'free' })
        .onConflictDoNothing().returning({ id: tOrganization.id })
        // @ts-expect-error executeInsertOne is dropped on the optional-returning (onConflictDoNothing) path
        .executeInsertOne()

    // Rule: INSERT's `ignoreIfHasValue` /
    // `ignoreIfHasNoValue` accept only OPTIONAL columns
    // (`OptionalColumnsForSetOf`), whereas UPDATE's accept ALL settable columns
    // (`ColumnsForSetOf`). A REQUIRED column (`title`) is therefore rejected on
    // INSERT but accepted on UPDATE — this locks that intentional param-type
    // divergence. Control: an optional column (`body`) is accepted on INSERT.
    void connection.insertInto(tIssue)
        .values({ projectId: 1, number: 1, title: 'x', status: 'open', priority: 1 })
        .ignoreIfHasValue('body')
    void connection.insertInto(tIssue)
        .values({ projectId: 1, number: 1, title: 'x', status: 'open', priority: 1 })
        // @ts-expect-error `title` is required, so it is not in OptionalColumnsForSetOf on INSERT
        .ignoreIfHasValue('title')
    void connection.insertInto(tIssue)
        .values({ projectId: 1, number: 1, title: 'x', status: 'open', priority: 1 })
        // @ts-expect-error `title` is required, so it is not in OptionalColumnsForSetOf on INSERT
        .ignoreIfHasNoValue('title')
    // Positive companion — UPDATE's `ignoreIfHasValue` / `ignoreIfHasNoValue`
    // accept the same required column (ColumnsForSetOf includes required columns).
    void connection.update(tIssue).set({ title: 'x' }).ignoreIfHasValue('title')
    void connection.update(tIssue).set({ title: 'x' }).ignoreIfHasNoValue('title')

    // Rule: `extendShape({...})` on the shaped on-conflict dynamic set returns a
    // DE-EXECUTED node on purpose — the freshly-mapped key must be staged by a
    // following `.set(...)` before the insert is executable, so a bare
    // `.executeInsert()` right after `extendShape` must NOT typecheck. This pins
    // the intentional de-execution against a future change that re-adds `& NEXT`.
    // Control: with the intervening `.set({ archived: null })` the insert executes.
    void connection.insertInto(tProject)
        .shapedAs({ orgId: 'organizationId', projectName: 'name', projectSlug: 'slug' })
        .set({ orgId: 1, projectName: 'a', projectSlug: 'b' })
        .onConflictDoUpdateDynamicSet({ projectName: 'Reactivated' })
        .extendShape({ archived: 'archivedAt' })
        .set({ archived: null })
        .executeInsert()
    // Guard: without the intervening `.set(...)`, the de-executed node exposes no executeInsert.
    void connection.insertInto(tProject)
        .shapedAs({ orgId: 'organizationId', projectName: 'name', projectSlug: 'slug' })
        .set({ orgId: 1, projectName: 'a', projectSlug: 'b' })
        .onConflictDoUpdateDynamicSet({ projectName: 'Reactivated' })
        .extendShape({ archived: 'archivedAt' })
        // @ts-expect-error extendShape de-executes the shaped on-conflict node; a bare executeInsert (no intervening set) is not allowed
        .executeInsert()
}

test('insert-negative-types', () => {
    expect(typeof _typeNegatives).toBe('function')
})
