-- Schema for the shared "project management" domain, mariadb dialect.
-- Idempotent: tests run setup against a fresh database each variant, but
-- having DROP IF EXISTS lets you re-apply by hand for debugging.

DROP VIEW IF EXISTS project_overview;
DROP VIEW IF EXISTS release_overview;
DROP VIEW IF EXISTS col_matrix_view;
DROP TABLE IF EXISTS project_review;
DROP TABLE IF EXISTS project_release;
DROP TABLE IF EXISTS audit_entry;
DROP TABLE IF EXISTS webhook_event;
DROP TABLE IF EXISTS calendar_year;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS ledger_entry;
DROP TABLE IF EXISTS issue_worklog;
DROP TABLE IF EXISTS col_matrix;
DROP TABLE IF EXISTS temporal_precision;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS issue;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS organization;

DROP TABLE IF EXISTS release_draft;
CREATE TABLE organization (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    plan VARCHAR(32) NOT NULL,
    -- `verified` flag stored as Y/N so the connection.ts mapping can
    -- exercise CustomBooleanTypeAdapter on a real seed column.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    -- `verified` stored as Y/N — same CustomBooleanTypeAdapter mapping
    -- as organization.verified so cross-table comparisons need no remap.
    verified VARCHAR(1) NOT NULL DEFAULT 'N',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    -- `published` flag stored as t/f, a deliberately different
    -- CustomBooleanTypeAdapter mapping than organization/app_user.verified
    -- so column-vs-column comparisons hit the remap-with-case branch.
    published VARCHAR(1) NOT NULL DEFAULT 'f',
    archived_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    UNIQUE (organization_id, slug)
);

CREATE TABLE issue (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    `number` INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NULL,
    status VARCHAR(32) NOT NULL,
    priority INT NOT NULL,
    assignee_id INT NULL,
    parent_id INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- New-type columns exercising AbstractConnection value marshalling:
    -- bigint (view_count), double (estimated_hours), uuid (external_ref).
    view_count BIGINT NOT NULL DEFAULT 0,
    estimated_hours DOUBLE,
    external_ref CHAR(36),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (assignee_id) REFERENCES app_user(id),
    FOREIGN KEY (parent_id) REFERENCES issue(id),
    UNIQUE (project_id, `number`)
);

CREATE TABLE country (
    code VARCHAR(2) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    region VARCHAR(32) NOT NULL
);

CREATE TABLE issue_worklog (
    id INT AUTO_INCREMENT PRIMARY KEY,
    issue_id INT NOT NULL,
    work_date DATE NOT NULL,
    started_at TIME,
    minutes INT DEFAULT 0,
    duration_ms BIGINT NULL,
    billable TINYINT(1) NULL,
    approved VARCHAR(1) NULL,
    -- billed amount per worklog (customDouble 'Money') and an `invoiced`
    -- flag stored as int 1/0 (numeric CustomBooleanTypeAdapter overload).
    billed_amount DOUBLE NOT NULL DEFAULT 0,
    invoiced INT NOT NULL DEFAULT 0,
    cost_cents INT NOT NULL DEFAULT 0,
    activity VARCHAR(16) NOT NULL,
    -- Nullable DB-computed column (declared optionalComputedColumn).
    activity_label VARCHAR(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN UPPER(activity) ELSE NULL END) STORED,
    tag_label VARCHAR(16) GENERATED ALWAYS AS (UPPER(activity)) STORED,
    tag_label_optional VARCHAR(16) GENERATED ALWAYS AS (CASE WHEN minutes IS NOT NULL THEN LOWER(activity) ELSE NULL END) STORED,
    FOREIGN KEY (issue_id) REFERENCES issue(id) ON DELETE CASCADE
);

-- Bigint autogenerated PK + enum-defaulted column.
CREATE TABLE webhook_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    issue_id INT NOT NULL,
    event_type VARCHAR(16) NOT NULL DEFAULT 'created',
    FOREIGN KEY (issue_id) REFERENCES issue(id) ON DELETE CASCADE
);

-- Int caller-provided PK.
CREATE TABLE calendar_year (
    year_value INT PRIMARY KEY,
    year_label VARCHAR(64) NOT NULL
);

-- Int caller-provided PK carrying a scaling TypeAdapter (invoice_no stored x10).
CREATE TABLE invoice (
    invoice_no INT PRIMARY KEY,
    total INT NOT NULL
);

-- Every column factory carries its trailing-TypeAdapter overload.
-- entry_no autogenerated (plusOffsetAdapter, read +1000); amount/memo carry
-- scaledTenthAdapter (stored x10, read /10) over a DB DEFAULT; tag is virtual
-- (no DB column).
CREATE TABLE ledger_entry (
    entry_no INT AUTO_INCREMENT PRIMARY KEY,
    amount INT NOT NULL DEFAULT 100,
    memo INT DEFAULT 50,
    discount INT
);

CREATE TABLE project_release (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    version VARCHAR(32) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    signing_key CHAR(36) NULL,
    released_on DATE NOT NULL,
    cutoff_time TIME NOT NULL,
    signed_off_at DATETIME NULL,
    -- REQUIRED customLocalDateTime twin of signed_off_at.
    published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_signed TINYINT(1),
    download_count BIGINT,
    avg_rating DOUBLE,
    notes VARCHAR(255) GENERATED ALWAYS AS (CONCAT('release-', version)) STORED,
    FOREIGN KEY (project_id) REFERENCES project(id),
    UNIQUE (project_id, version)
);

-- Project review fixture: non-boolean per-column TypeAdapter on score (int,
-- stored x10) + reviewer_code (string, bracketed), an OPTIONAL localDate
-- (review_date) and a REQUIRED localTime (review_time).
CREATE TABLE project_review (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id INT NOT NULL,
    reviewer_code VARCHAR(32) NOT NULL,
    score INT NOT NULL,
    review_date DATE,
    review_time TIME NOT NULL,
    FOREIGN KEY (project_id) REFERENCES project(id)
);


-- Stored procedures and functions exercised by
-- `exec.procedure-function.test.ts`. Each body is intentionally
-- trivial AND single-statement so the `splitStatements` helper (which
-- splits on `;\n`) ships each CREATE in one piece. Procedures avoid
-- `BEGIN ... END` by leaning on MariaDB's single-statement body form;
-- functions use the `RETURN (<scalar subquery>)` shortcut for the
-- same reason.
DROP PROCEDURE IF EXISTS refresh_stats;
DROP PROCEDURE IF EXISTS archive_project;
DROP FUNCTION IF EXISTS count_open_issues;
DROP FUNCTION IF EXISTS project_name;
CREATE PROCEDURE refresh_stats() SELECT 1;
CREATE PROCEDURE archive_project(IN p_id INT, IN p_reason VARCHAR(255)) UPDATE project SET archived_at = CURRENT_TIMESTAMP, name = CONCAT(name, ' [archived: ', p_reason, ']') WHERE id = p_id;
CREATE FUNCTION count_open_issues(p_id INT) RETURNS INT DETERMINISTIC RETURN (SELECT COUNT(*) FROM issue WHERE project_id = p_id AND status = 'open');
CREATE FUNCTION project_name(p_id INT) RETURNS VARCHAR(255) DETERMINISTIC RETURN (SELECT name FROM project WHERE id = p_id);
DROP FUNCTION IF EXISTS total_view_count;
DROP FUNCTION IF EXISTS latest_issue_at;
DROP FUNCTION IF EXISTS estimated_total;
CREATE FUNCTION total_view_count(p_id INT) RETURNS BIGINT DETERMINISTIC RETURN (SELECT COALESCE(SUM(view_count),0) FROM issue WHERE project_id = p_id);
CREATE FUNCTION latest_issue_at(p_id INT) RETURNS DATETIME DETERMINISTIC RETURN (SELECT MAX(created_at) FROM issue WHERE project_id = p_id);
CREATE FUNCTION estimated_total(p_id INT) RETURNS DOUBLE DETERMINISTIC RETURN (SELECT COALESCE(SUM(estimated_hours),0) FROM issue WHERE project_id = p_id);
DROP FUNCTION IF EXISTS ret_flag;
DROP FUNCTION IF EXISTS ret_uuid;
DROP FUNCTION IF EXISTS ret_day;
DROP FUNCTION IF EXISTS ret_clock;
DROP FUNCTION IF EXISTS ret_activity;
DROP FUNCTION IF EXISTS ret_channel;
DROP FUNCTION IF EXISTS ret_semver;
-- Constant-returning functions, one per remaining executeFunction return kind.
-- boolean rides in TINYINT(1); ret_uuid returns the string form (not BINARY).
CREATE FUNCTION ret_flag(p_id INT) RETURNS TINYINT(1) DETERMINISTIC RETURN 1;
CREATE FUNCTION ret_uuid(p_id INT) RETURNS CHAR(36) DETERMINISTIC RETURN '0a8f9c1e-1111-4222-8333-444455556666';
CREATE FUNCTION ret_day(p_id INT) RETURNS DATE DETERMINISTIC RETURN DATE '2024-02-03';
CREATE FUNCTION ret_clock(p_id INT) RETURNS TIME DETERMINISTIC RETURN TIME '14:25:36';
CREATE FUNCTION ret_activity(p_id INT) RETURNS VARCHAR(16) DETERMINISTIC RETURN 'coding';
CREATE FUNCTION ret_channel(p_id INT) RETURNS VARCHAR(16) DETERMINISTIC RETURN 'stable';
CREATE FUNCTION ret_semver(p_id INT) RETURNS VARCHAR(32) DETERMINISTIC RETURN '1.0.0';

-- Sequences exercised by `sequence.next-current-value.test.ts`.
-- MariaDB has named sequences since 10.3 (typed via the connection's
-- `'int'` / `'bigint'` adapter; the engine's CREATE SEQUENCE default
-- is `BIGINT`, the type hint only affects deserialization).

DROP SEQUENCE IF EXISTS issue_id_seq;
DROP SEQUENCE IF EXISTS audit_tag_seq;

CREATE SEQUENCE issue_id_seq START WITH 1;
CREATE SEQUENCE audit_tag_seq START WITH 1;
DROP SEQUENCE IF EXISTS release_tag_seq;
CREATE SEQUENCE release_tag_seq START WITH 1;

-- A class-based SQL view exercised by `view.basic.test.ts`. A plain
-- join of project + organization (no aggregation, no casts), portable
-- across every dialect.
CREATE TABLE audit_entry (
    id INT PRIMARY KEY,
    action VARCHAR(255) NOT NULL
);

CREATE VIEW project_overview AS
SELECT p.id AS id,
       p.organization_id AS organization_id,
       p.name AS name,
       p.archived_at AS archived_at,
       o.name AS organization_name,
       o.plan AS organization_plan
FROM project p
INNER JOIN organization o ON o.id = p.organization_id;

-- View side of the release columns (see vReleaseOverview in connection.ts).
CREATE VIEW release_overview AS
SELECT r.id AS id,
       r.project_id AS project_id,
       r.version AS version,
       r.released_on AS released_on,
       r.signed_off_at AS signed_off_at,
       r.published_at AS published_stamp,
       r.published_at AS published_stamp_plain,
       r.version AS version_bracketed,
       CASE WHEN r.channel <> 'beta' THEN r.channel ELSE NULL END AS channel_bracketed,
       r.cutoff_time AS cutoff_clock,
       r.is_signed AS is_signed,
       r.download_count AS download_count,
       r.avg_rating AS avg_rating,
       r.signing_key AS signing_uuid,
       r.released_on AS release_day_plain,
       r.cutoff_time AS cutoff_plain,
       r.id AS release_ordinal,
       CASE WHEN r.download_count IS NOT NULL THEN r.id ELSE NULL END AS optional_release_ordinal,
       p.name AS project_name
FROM project_release r
INNER JOIN project p ON p.id = r.project_id;

-- release_draft: OPTIONAL enum/custom/customComparable columns so the
-- Nullable family reaches a real NULL row. Caller-provided int PK (no identity).
CREATE TABLE release_draft (
    id INT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    stage VARCHAR(16),
    channel VARCHAR(16),
    min_version VARCHAR(32),
    budget DOUBLE,
    target_day DATE,
    cutoff TIME,
    scaled_cost INT NOT NULL DEFAULT 250,
    shifted_amount DOUBLE NOT NULL DEFAULT 300,
    bracket_version VARCHAR(32) NOT NULL DEFAULT '2.0.0',
    bracket_channel VARCHAR(16) NOT NULL DEFAULT 'stable',
    bracket_activity VARCHAR(16) NOT NULL DEFAULT 'coding',
    shifted_stamp DATETIME NOT NULL DEFAULT '2024-06-01 10:00:00',
    shifted_count BIGINT NOT NULL DEFAULT 5000,
    shifted_rating DOUBLE NOT NULL DEFAULT 4.5,
    bracket_signing_key CHAR(36) NOT NULL DEFAULT '00000000-0000-4000-8000-000000000000',
    shifted_release_day DATE NOT NULL DEFAULT '2025-03-01',
    shifted_cutoff TIME NOT NULL DEFAULT '09:00:00'
);

-- col_matrix: one plain, NOT NULL column per base kind. Every
-- tColMatrix* Table / the vColMatrix View reads these SAME columns through a
-- DIFFERENT column factory; the optionality/default/computed/pk distinction is
-- type-level only. Caller-provided int PK (no AUTO_INCREMENT).
CREATE TABLE col_matrix (
    id INT PRIMARY KEY,
    m_int INT NOT NULL,
    m_bigint BIGINT NOT NULL,
    m_double DOUBLE NOT NULL,
    m_bool TINYINT(1) NOT NULL,
    m_uuid CHAR(36) NOT NULL,
    m_date DATE NOT NULL,
    m_time TIME NOT NULL,
    m_datetime DATETIME NOT NULL,
    m_str VARCHAR(64) NOT NULL
);

-- temporal_precision: a microsecond-precision localDateTime column (DATETIME(6))
-- seeded with a sub-millisecond instant (12:30:59.999600) that a JS Date cannot
-- express. Locks the date-part getters' SQL-side truncation on a real microsecond
-- value: getSeconds() must stay 59 (not round to 60) and getMilliseconds() must
-- stay 999 (floor(microsecond / 1000), not a round up to 1000). Int PK, no identity.
CREATE TABLE temporal_precision (
    id INT PRIMARY KEY,
    micro_stamp DATETIME(6) NOT NULL
);

CREATE VIEW col_matrix_view AS
SELECT id, m_int, m_bigint, m_double, m_bool, m_uuid, m_date, m_time, m_datetime, m_str
FROM col_matrix;

-- Zero-arg function per base value kind, each returning the col_matrix row-1
-- value (executeFunction return-kind + trailing-adapter
-- fan-out, exercised by `exec.function-value-kinds.test.ts`). Custom kinds reuse
-- the base-kind function. Declared AFTER col_matrix (the body reads it). m_uuid
-- is CHAR(36) (plain string), so cm_uuid reads it directly.
DROP FUNCTION IF EXISTS cm_int;
DROP FUNCTION IF EXISTS cm_bigint;
DROP FUNCTION IF EXISTS cm_double;
DROP FUNCTION IF EXISTS cm_bool;
DROP FUNCTION IF EXISTS cm_uuid;
DROP FUNCTION IF EXISTS cm_date;
DROP FUNCTION IF EXISTS cm_time;
DROP FUNCTION IF EXISTS cm_datetime;
DROP FUNCTION IF EXISTS cm_str;
CREATE FUNCTION cm_int() RETURNS INT DETERMINISTIC RETURN (SELECT m_int FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_bigint() RETURNS BIGINT DETERMINISTIC RETURN (SELECT m_bigint FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_double() RETURNS DOUBLE DETERMINISTIC RETURN (SELECT m_double FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_bool() RETURNS TINYINT(1) DETERMINISTIC RETURN (SELECT m_bool FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_uuid() RETURNS CHAR(36) DETERMINISTIC RETURN (SELECT m_uuid FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_date() RETURNS DATE DETERMINISTIC RETURN (SELECT m_date FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_time() RETURNS TIME DETERMINISTIC RETURN (SELECT m_time FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_datetime() RETURNS DATETIME DETERMINISTIC RETURN (SELECT m_datetime FROM col_matrix WHERE id = 1);
CREATE FUNCTION cm_str() RETURNS VARCHAR(64) DETERMINISTIC RETURN (SELECT m_str FROM col_matrix WHERE id = 1);
