on:
  push:
    branches: [master, v1]
  pull_request:

name: CI

jobs:
  build:
    name: build library
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [20.x, 22.x, 24.x]
    steps:
      # Setup environment
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build
      - name: Prepare
        run: npm run generate-prisma
      - name: Build
        run: npm run build

      # Light tests (docker tests not supported yet)
      - name: Light tests
        run: npm run no-docker-examples
